### ISSUE TITLE
Use of URN-style links does not work in descriptions of baseResource

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-docs-kit#1020]
We tried to have flexible description on each API endpoint similar to the string "Query by ID" in the [API Smoke Test](https://commercetools-docs-kit-git-ao-document-lin-07a241-commercetools.vercel.app/api-docs-smoke-test/endpoints/methods#get-resource-by-id)

This string should be rendered d[ynamically from RAML](https://github.com/commercetools/commercetools-api-reference/blob/a886bb877c582dd19ededa057d361025151de96b/api-specs/api/api.raml#L65) where we have specified the following description:
Without using links at all rendering works fine.
Get `<<resourceType>>` by ``<<uriParameterName>>``
<img width="529" alt="Screen Shot 2021-07-09 at 11 29 08" src="https://user-images.githubusercontent.com/900598/125056834-ec637280-e0a8-11eb-85fe-4f2db7320841.png">

Bit if I try to link to the respective resource representation by using URN-style link:

Get `[<<resourceType>>](ctp:api:type:<<resourceType>>)` by `<<uriParameterName>>`
I get following Gatsby exception:
<img width="747" alt="Screen Shot 2021-07-09 at 11 19 28" src="https://user-images.githubusercontent.com/900598/125056884-f6857100-e0a8-11eb-904d-4e97b28dae05.png">

I tried a workaround with specifying the anchor:
Get `[<<resourceType>>](#<<resourceType>>)` by `<<uriParameterName>>`

but it leads to broken link `/projects/customerGroups#CustomerGroup` due to case sensitive rendering.

We would like to have the same capability for  the description of [URI parameters](https://github.com/commercetools/commercetools-api-reference/blob/a886bb877c582dd19ededa057d361025151de96b/api-specs/api/api.raml#L59).

description: "`<<uriParameterName>>` of the [`<<resourceType>>](ctp:api:type:<<resourceType>>`)"

Where I get the same error from Gatsby.

Likely to be fixed by #1018

**Comment by davifantasia** [comment]
This [PR](https://github.com/commercetools/commercetools-docs-kit/pull/1018) should fix this.

**Comment by davifantasia** [comment]
Fixed with [PR](https://github.com/commercetools/commercetools-docs-kit/pull/1018)
