### ISSUE TITLE
Request for separate color for PUT requests. - 1

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#1024]
Difference between making a `PUT` or `POST` request for against object:

* `PUT` creates/overwrites an object
* `POST` describes a set of changes to an object

This is the current place we have a `PUT` request rendered:

https://docs.commercetools.com/import-api/import-sink#update-an-importsink

Here are the current request colours from the designs:

https://commercetools.invisionapp.com/console/commercetools-API-DOCS---Component-V2-ckem9zrer39id01z90qsjc8iy/ckfgsvr4d00iv0107dlle7ww3/play

**Comment by Shecki** [comment]
Please use this Color for PUT:
#B866FF
