### ISSUE TITLE
Firefox: Very long Type names wrap over to the next column in the ChildSectionNavigator

### ISSUE THREAD

**Issue by adinakleine** [commercetools/commercetools-docs-kit#1052]
If the name of a representation gets too long it uses the next column. This happens if the representation is the last entry in a column. 
Find an example [here](https://github.com/commercetools/commercetools-docs/pull/1192#issuecomment-887347568).

Firefox renders:
![image](https://user-images.githubusercontent.com/4006139/127155163-10b3cf70-3cd2-4bac-8637-551b32919ef5.png)

Chrome renders:
![image](https://user-images.githubusercontent.com/4006139/127155188-8a20a835-f8bc-418b-87d1-f8f954b5c9ed.png)

**Comment by nkuehn** [comment]
@adinakleine  I took the freedom to give the issue a more specific name

**Comment by nkuehn** [comment]
https://developer.mozilla.org/de/docs/Web/CSS/break-inside 

Firefox does not support the official instruction but the compatibility notes point out that the legacy `page-break-inside: avoid;` instruction works and can be added manually in addition.   (I tried, it does - on the div that is the first child level in the colums)
