### ISSUE TITLE
Search dialog shows css props in result list unintentionally

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#1053]
We've noticed that the search dialog renders css properties as text in the search results on multiple places. This happens most of the time before a section of the result list ends.

<img width="800" alt="Bildschirmfoto 2021-07-27 um 11 48 15" src="https://user-images.githubusercontent.com/31767369/127133893-55f4f797-c24a-4db1-991d-fa71928b0c5f.png">

**Comment by molly-jones** [comment]
This has finally been reported by a customer, now, as well. https://jira.commercetools.com/browse/SUPPORT-13176

Support will follow this ticket for a resolution.

**Comment by davifantasia** [comment]
Hey Timon after the latest merge of the release with the fix you did, the bug is still not fixed. See the PR here:

https://github.com/commercetools/commercetools-docs/pull/1271

**Comment by emmenko** [comment]
I checked the live docs, the issue is gone now! 🎉
