### ISSUE TITLE
Keyboard accessibility not working

### ISSUE THREAD

**Issue by peter-empen** [commercetools/commercetools-docs-kit#1054]
I am missing browser page navigation by the Pos1/End/PgUp/PgDn keys for a long time. I am used to these keys since they work on virtually every page in the browser.
Would you mind supporting/not disabling these keys to make navigation in ct documentation a more fluent experience?

**Comment by emmenko** [comment]
Thanks for reporting this.

We haven't focused much on accessibility to be honest and as a result most of the keyboard accessibility interactions are either broken or not working properly (page navigation, link navigation, etc).

This is obviously not good and we do want to provide full accessibility support and thus a good experience.

We'll try to prioritize this whenever possible and improve things.

**Comment by jenschude** [comment]
Just a side note:

I tried it with disabled javascript and the keyboard navigation is not working.

Found out when I click a anchor link e.g. for the Representations the keyboard navigation on a page is working again. Seems that the scroll focus is not in the content pane after clicking a navigation link.

**Comment by emmenko** [comment]
@jenschude Thanks, that's a good find!

**Comment by jenschude** [comment]
Another thing:

The keyboard navigation is working at the front page. So it must be the sidebar navigation in a content page.

**Comment by emmenko** [comment]
I think we're missing some kind of `tabindex=0` on the main page element.

**Comment by jenschude** [comment]
There is only a `tabindex: -1` and a `tabindex: 1` defined. Adding `tabindex:0` to `<main>` or `<article>` tag fixes the keyboard navigation.

**Comment by peter-empen** [comment]
💯 Amazing, thank you!
