### ISSUE TITLE
Render a dash only if there is no content in the description

### ISSUE THREAD

**Issue by TohruKohrita** [commercetools/commercetools-docs-kit#1061]
This is an example from a query parameter doc.
<img width="780" alt="Screenshot 2021-07-29 at 16 27 45" src="https://user-images.githubusercontent.com/63338357/127510404-ce5e2526-90a8-4a5d-baf2-e814a2d2a31c.png">

We want the dash only if the description is completely empty, i.e. **no text and no blue box**.

**Comment by nkuehn** [comment]
For clarification:  The description english grammar caused some confusion because it was ambiguous.  
> We want the dash only if the description is completely empty
"only if"  vs.  "dash only"  the reference of "only"? 

from context it's clear.   Let's just not render that dash at all any more.
