### ISSUE TITLE
Remove @commercetools-docs/ramldoc-generator package from the repository

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#1065]
`@commercetools-docs/ramldoc-generator`  has been replaced with `@commercetools-docs/rmf-codegen` but because it still exist in this repository it is still installed as a dependency and fails intermittently. Hence the need to completely remove it.

**Comment by davifantasia** [comment]
@nkuehn  what do you think about removing `@commercetools-docs/ramldoc-generator` package?

**Comment by nkuehn** [comment]
yes please!
