### ISSUE TITLE
Scrolling through release notes topics is not working

### ISSUE THREAD

**Issue by adinakleine** [commercetools/commercetools-docs-kit#1100]
When opening https://docs.commercetools.com/api/releases on a smaller screen (e.g. laptop) it is not possible to scroll through the **Filter By Topics** section. Due to this it is not possible to filter by a topic at the end of the list.

<img width="1412" alt="Screenshot 2021-09-01 at 09 33 46" src="https://user-images.githubusercontent.com/58512719/131631761-8d51c25e-7547-4aed-acc3-f4bec341908b.png">

**Comment by nkuehn** [comment]
This should be doable, but not via making the topics themselves scrollable but by making the complete sidebar behave like the sidebar on the content pages.  I.e. the whole sidebar scrolls full height once the page header is out of view.
