### ISSUE TITLE
Reorder `maximum`, `minimum` tags

### ISSUE THREAD

**Issue by naveenchkrvrthy** [commercetools/commercetools-docs-kit#1102]
When tags like `minLength`, `maxLength`, `minimum`, `maximum` are modeled in RAML, the max value appears before the min value. 

![eg1](https://user-images.githubusercontent.com/70849970/131645890-fd90018f-ce6d-4b50-9c90-8324312e1834.png)
![eg2](https://user-images.githubusercontent.com/70849970/131646337-b743f34d-faaf-49ef-8f8e-798807235068.png)

**_We would want the min value to appear before the max value._**

**Comment by timonrey** [comment]
@adinakleine @naveenchkrvrthy We can do this but could you give us the exact order of the whole tag list how you would want to display them? Then we would always display them in the same order.

**Comment by timonrey** [comment]
That is the code where it has to be implemented:
https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-theme-api-docs/src/utils/extract-additional-info.js

**Comment by TohruKohrita** [comment]
I see that we have the following tags: MinItems, MaxItems, UniqueItems, MaxLength, MinLength, Default, Pattern, Can be. 

Is it enough to give you the ordering of these tags or are there other tags we need to consider? @timonrey

**Comment by timonrey** [comment]
@TohruKohrita We can start with these tags. If there are other important tags, we can still reorder it if necessary.

**Comment by nkuehn** [comment]
Let's not overengineer the ordering discussion.   Some of these cannot happen together anyways and the only practical complaint is that max / min are not consistent.  

The reference for available constraints is https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#built-in-types 

Most cases can never happen together anyways,  so let's focus on ordering them only inside of where they can happen. The implementation can be pretty dumb then

Proposal: 
 * Anything:
    1. `default` (should be first anyways)
 * [Object](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#object-type):
    1. `minProperties`
    2. `maxProperties`
 * [Array](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#array-type):
    1. `minItems`
    2. `maxItems`
    3. `uniqueItems`
 * [String](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#string):
    1. `minLength`
    2. `maxLength`
    3. `pattern`
 * [Number](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#number): 
     1. `minimum`
     2. `maximum`
  
(the others in the spec are either filtered out or not relevant to us)

Looking at the above list I propose to either just make them one big list to order by or to do the following reordering steps statically to achieve  "default" -> "min*" -> "max*" -> all the others ordering. 
 1. move anythign starting "max" to the front
 2. move anything starting "min" to the front
 3. move "default" to the front.

**Comment by adinakleine** [comment]
> Let's not overengineer the ordering discussion. Some of these cannot happen together anyways and the only practical complaint is that max / min are not consistent.
> 
> The reference for available constraints is https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#built-in-types
> 
> Most cases can never happen together anyways, so let's focus on ordering them only inside of where they can happen. The implementation can be pretty dumb then
> 
> Proposal:
> 
> * Anything:
>   
>   1. `default` (should be first anyways)
> * [Object](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#object-type):
>   
>   1. `minProperties`
>   2. `maxProperties`
> * [Array](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#array-type):
>   
>   1. `minItems`
>   2. `maxItems`
>   3. `uniqueItems`
> * [String](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#string):
>   
>   1. `minLength`
>   2. `maxLength`
>   3. `pattern`
> * [Number](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#number):
>   
>   1. `minimum`
>   2. `maximum`
> 
> (the others in the spec are either filtered out or not relevant to us)
> 
> Looking at the above list I propose to either just make them one big list to order by or to do the following reordering steps statically to achieve "default" -> "min*" -> "max*" -> all the others ordering.
> 
> 1. move anythign starting "max" to the front
> 2. move anything starting "min" to the front
> 3. move "default" to the front.

@TohruKohrita and @stmeissner Please leave a reaction here 👍 / 👎

**Comment by TohruKohrita** [comment]
I think NIkolaus's proposal good. I have no additional input.
