### ISSUE TITLE
HTTP API release notes page very slow

### ISSUE THREAD

**Issue by yacx** [commercetools/commercetools-docs-kit#1114]
I noticed that the HTTP API Release Notes page is extremely slow - to the point that it’s barely usable. It takes a couple of seconds (sometimes even longer) to react to a click on a filter, the search bar, or any link.

Probably due to the large amount of release notes on the page. The MC release notes work fine.

**Comment by yacx** [comment]
Looks good now

**Comment by adinakleine** [comment]
> Looks good now
Perfect, I will close this issue then.
