### ISSUE TITLE
RAMLdoc: Render displayName of type instead of type name

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-docs-kit#1131]
Considering following use case:

There is a RAML spec with a field definition with a type called `StateRoleEnum`.

```
roles:
    type: array
    items:
      type: StateRoleEnum
```
When rendered in the API endpoint, it looks like this:
<img width="147" alt="Screenshot 2021-10-28 at 16 35 27" src="https://user-images.githubusercontent.com/900598/139278335-9e15fb15-ee24-4dc7-a58a-825152ea79d5.png">

In the RAML type definition for `StateRoleEnum` we have specified a `displayName: StateRole` 

```
#%RAML 1.0 DataType
displayName: StateRole
type: string

```
that we would like to appear in the API endpoint instead of the type name.
<img width="147" alt="Screenshot 2021-10-28 at 16 35 27" src="https://user-images.githubusercontent.com/900598/139281064-287bbf5a-b759-4818-8862-9933708494e7.png">

So, the desired feature will render the [displayName](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#type-declarations) in the documentation instead of the type name in case a displayName is set for the type of the field. If no displayName is present the specification of the field type, its name should be rendered as fallback.

**Comment by nkuehn** [comment]
@TohruKohrita @stmeissner  are we sure this kind of topic is right addressed in the website frontend?  

We did change the architecture to have all the "smart" understanding of API specs and how they are resolved towards documentation in the `rmf-codegen` to be sure that SDKs and Docs don't drift 

Also, it ensures that people that are really good at working with the API modeling do the logic, i.e. the clients team.  The docs kit is totally "dumb" now.  It reads the `RAML_DOC` output as a YAML file with zero understanding of the logic. 

@jenschude do you remember our "policy" conversation about display names?  I think we discussed something around not knowing the name of a type beyond the file name and a general notion of deviating display name from the file name not being a really good idea anyways.

**Comment by jenschude** [comment]
The SDKs are using the types name for the generated classes & interfaces. And we agreed that the displayname could be different if necessary. I already changed the small helper script in the docs repo so that it doesn't enforce the matching names any more

**Comment by jenschude** [comment]
The thing is that the type naming has to be unique and one word without special characters. Where as the display name allows more freedom. For the uniqueness constraint we made used the convention to add the domain as a prefix to distinguish between structurally same but logically different types e.g. all Update and UpdateAction types.

For the docs not all of them may be necessary and you may want to use different namings for a more speaking name or even use whitespaces in the displayname. With the requested feature this would be made possible.

**Comment by nkuehn** [comment]
@jenschude  thanks for your input. 

I do not think it's a good idea to introduce **name duplications** in the docs (and it's not the use case discussed here, too)
 * using full text search for a certain type that you used in the SDK or the GraphQL API should be unambiguous
 * confusion in general
 * will be different than GraphQL and we want to keep  the surface difference to GraphQL as low as possible.  
 
**"structurally same but logically different"**:  docs is now moving to the domain specific update action naming to get rid of the inconsistency

**whitespace / special characters:** not a good idea, too IMHO. Chapter titles are handwritten markdown in the docs anyways, if we want to add explanatory context, e.g. "MyShoppingBasket (a Cart)" we can do that in content. 

In general my view is cycling arond the same general topic: Any naming differences for a given concept are unnecessary mental load.  A "beautiful" name is usually not making up for that.  

----

Concerning the specific
 1. the current handwritten docs call it "StateRole" . https://docs.commercetools.com/api/projects/states#staterole 
 2. It's "StateRole" in GraphQL (hardest to change of any of the places) https://github.com/commercetools/commercetools-docs/blob/5c057df1d69aef570e3fc461eb4b9bf4c8c6adc1/api-specs/graphql/schema.sdl#L9478 
 3. For reasons client team knows better it was decided to name it differently for the SDKs in the RAML spec.  

Isn't this rather a situation where the API spec RAML master name should be changed to "StateRole" and have an override for compatible legacy SDKs?  Next major SDK could change the name to the common name.

**Comment by jenschude** [comment]
Yeah good question why i made the decision back in 2017 to suffix it with Enum 😆 

The legacy SDKs use StateRole. Only the v2s use StateRoleEnum. I'm fine with cleaning up, but then we should do it imho all at once and not like today StateRole and next week some Attribute/CustomField enum. Cause the name changes will be breaking and there is no good way to circumvent this in a backwards compatible way.

**Comment by nkuehn** [comment]
Short summary of my conversation with @jenschude yesterday:  It will be done either by changing the name in the RAML to the common name in GraphQL and docs and accepting that it's a breaking SDK version then or by adjusting the RMF-Codegen to output a structure to RAML_DOC that uses the display name for both file name, display name and name so that it's unambiguous.  

-> not done in this repository in any case.  Please close once you have tracked it somewhere else @stmeissner , thanks!

**Comment by stmeissner** [comment]
Thanks for your input to the discussion. I'm happy with your proposals.
