### ISSUE TITLE
Unwanted hyphen at the end of Anchor Links on Beta tagged headers

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#1181]
Anchor links for Beta-tagged entries have a hyphen (-) added to the end of their `href`.

![image](https://user-images.githubusercontent.com/77231096/147738096-f32f8806-4f36-4b9c-a8e4-66600619179f.png)

Transfered issue from the [docs repo](https://github.com/commercetools/commercetools-docs/issues/1674)

**Comment by timonrey** [comment]
Slack discussion for this issue:
https://commercetools.slack.com/archives/GG00MD84Q/p1640802801001600

**Comment by timonrey** [comment]
@adinakleine @industrian Can you please describe the practical problem for you?

**Comment by industrian** [comment]
> @adinakleine @industrian Can you please describe the practical problem for you? It would be quite complicated to fix and we would like to not do it if its just for aesthetical reasons.

Adding @stmeissner 

This problem essentially breaks links. But doesn't count as a broken link as the page itself loads.

Example:

1. Go to https://docs.commercetools.com/api/projects/cartDiscounts 
2. Click CreatedBy (in the screenshot). 
![image](https://user-images.githubusercontent.com/77231096/148200326-094777f1-e22d-4e59-9aa2-b9ae5a63814e.png)
3. This link expects to go to an anchor called "createdby", but as this anchor doesn't exist, it just takes you to the top of the Common API Data Types page.

I'm not sure how these pages are generated, but the issue appears to be that a space is being added to the title. This space is then causing a hyphen to be added to the anchor links.

![image](https://user-images.githubusercontent.com/77231096/148200992-0423250b-c557-4600-9344-116a0974de53.png)

**Comment by nkuehn** [comment]
@industrian  the contente that has the link is handwritten, that means the author has to put the exact achor string of the target location.  If the target location has a dash at the end the anchor in the hadwritten markdown has to have a dash at the end.  It's pretty mechanic work, yes. 

My conclusion from the ticket is that this is more of an author ergonomics issue than a bug.   It's not intuitive that some target anchors have a dash at the end.  And it's annoying to have to touch all manual links if something goes out of beta. 

I'd keep it as a feature request to try to somehow wrap the standard library used for "slugify" of headings and text to avoid the extra dash.  It's happening in many places in the codebase and therefore needs thorough testing.   I would prefer to do it after we have anchor link testing back ( #1185 )

**Comment by industrian** [comment]
This issue was "fixed" by adding a non-breaking space (`&nbsp`) between the end of the header and the `<Beta />` tag. 

As this is a workable solution, this issue can be considered closed.

**Comment by nkuehn** [comment]
@industrian  we can prioritize it down but it is still a bug in the implementation that we need to fix.   The underlying issue can also affect other situations in header content.  

I'd like to reopen this.  OK?   

FYI @timonrey

**Comment by FFawzy** [comment]
consider doing this together with mdx v2

**Comment by gabriele-ct** [comment]
Implemented in https://github.com/commercetools/commercetools-docs-kit/pull/1502 (part of MDX v2 upgrade)
