### ISSUE TITLE
Provide Link checking for anchor / hash to docs

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1185]
With the switch to linkinator during the migration from jekyll to gatsby we lost the ability to check hashes / anchor locations.  Errors have occurred in production now. Not many but some.  

We need to either contribute that ability to linkinator or find another way to at least periodically check the anchor integrity.

**Comment by nkuehn** [comment]
FYI this has become crtiical.  Docs team just reported they are running circles around broken anchor links and manually test the complete links now.  so the autometed check is not saving actual time,

**Comment by timonrey** [comment]
Link to the issue in the linkinator repository:
https://github.com/JustinBeckwith/linkinator/issues/79

**Comment by timonrey** [comment]
Idea: We could consider using another link checker which is more ideal for our use cases. This would include some research on existing link checkers

**Comment by nkuehn** [comment]
Here's some popular and well maintained other link checkers and whether they have anchor / fragment support:
 * [Lychee](https://github.com/lycheeverse/lychee) (Rust, has a [github action](https://github.com/lycheeverse/lychee-action), [no fragment check support](https://github.com/lycheeverse/lychee/issues/185))
 * [broken-link-checker](https://github.com/stevenvachon/broken-link-checker) (JS, we used this before linkinator and were not happy with speed and stability,  checking hashes is on the roadmap but not implemented)
 *  Python "[linkchecker](https://github.com/linkchecker/linkchecker)" (python, well maintained,  it _did_ have anchor checking but they [removed it because the plugin was unreliable](https://github.com/linkchecker/linkchecker/pull/575))
 * [HTML Proofer](https://github.com/gjtorikian/html-proofer) (Ruby, well maintained and stable, we used this in the old jekyll site,  has proven anchor check support,  relatively slow because it validates the complete HTML against the HTML spec, [has a github action](https://github.com/marketplace/actions/htmlproofer), only built for checking local files and the remote locations they link to)
 * Dart "[linkcheck](https://github.com/filiph/linkcheck)" (fast native binary, does have support for checking missing anchors,   no readymade github action but the docker container is just 8MB and github actions have full support for "runs-in" container steps. 

Plus a bunch more that are less maintained in the respective ecosystem but they are not listed if they have no anchor support. 

**Summary:  I suggest trying to port our linkinator settings to the CLI flags of  the Dart "linkcheck" CLI.  Regex skiplist in a file is possible, need to pass --external  and --show-redirects.    What is not supported by "linkcheck" is rewriting the hosts on our staging domain.  This might be the blocker.

**Comment by nkuehn** [comment]
`linkcheck` worked OK in a first try with this skip list file:
```
/custom-applications
/.+/(page-data|static)/(.*)
/[^/]+/[^/]+.(js|json)$"
https://cocoapods.org/
```
and calling 
`linkcheck --external --skip-file linkcheck-skip-list https://docs.commercetools.com`

As expected we have  accumulated quite a lot of broken anchor links over time.  Preview domains did not break right now, so the canonical tag seems to be not checked naively.  but they may break on certain types of changes, we'll see.

**Comment by nkuehn** [comment]
Resolved in the content repo(s), we should apply the same approach here now to have the kit development setup continue to serve as a testing ground for production use.

**Comment by nkuehn** [comment]
@timonrey here's the action step to put at the end of the preview deploy job: (adjust if the preview condidtion is different here)

```
      - name: Check local links including anchors
        if: ${{ env.DEPLOY_ENV == 'Preview' }}
        working-directory: public
        run: npx --quiet start-server-and-test 'npx --quiet http-server --silent -p 9000' 9000 'docker run --network=host  tennox/linkcheck :9000'
```
(not using a skiplist here, it's actually useful to test literally all hrefs in the kit smoke test, even the generated ones. 

The separate link checking step via linkinator can stay, it's checking the external links.
