### ISSUE TITLE
Add time estimation for tutorials

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#1186]
The idea is to have a timestamp below the H1 of a tutorials page that shows the reader how long it takes to read the page.
Invision link:
https://commercetools.invisionapp.com/console/share/ED30V03OA2

It can be implemented as an optional frontmatter where the writers can define a specific time. When the frontmatter is defined, the timestamp will be shown in the page under the H1.

**Comment by nkuehn** [comment]
looks clear.  Would live in the `page-header` grid piece and be driven from an optional MDX frontmatter 
It would not be tutorials-specific, could be used on any page.  

To be decided:  Frontmatter in numeric form as minutes or as the full string?    (I prefer numeric minutes for consistent output).
