### ISSUE TITLE
Allow common currency codes in writing style acronyms

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1193]
I think we can allow the big global currency codes (USD, EUR, JPY) to be used without explanation.  CHF maybe too? 

![image](https://user-images.githubusercontent.com/4006139/149976831-3d373536-4177-4950-97f9-44342f96fc46.png)

**Comment by timonrey** [comment]
The currency codes are already implemented 👍🏼 
https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/writing-style/styles/commercetools/Acronyms.yml
