### ISSUE TITLE
Top Menu

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#123]
- implemented in the kit (part of the theme)
 - pulls its content / links from a central URL   e.g.  https://docs.commercetools.com/menu.json
 - that URL is provided by  a new "home" website in the commercetools-docs repo. A netlify redirect places it into the root.

**Comment by emmenko** [comment]
For now we will hardcode the links in the theme. The dynamic part can be looked into as a follow up.
