### ISSUE TITLE
Separate check of internal and external links

### ISSUE THREAD

**Issue by adinakleine** [commercetools/commercetools-docs-kit#1230]
Please separate the check of external links from the internal link check for the commercetools-docs repo. 
The internal link check should stay required, while the external link check shouldn't be a blocker for merging.

**Comment by nkuehn** [comment]
We started to address it while trying to find a link checker that also checks the internal links. 
There's a PR open in the docs repo with a new link checker setup but it will be on hold a bit. 

If this is urgent we could consider separating it and doing it on the existing link checker.
