### ISSUE TITLE
Add SideBySide to SDK and Getting Started sites

### ISSUE THREAD

**Issue by industrian** [commercetools/commercetools-docs-kit#1239]
Only the API and Import API sites currently have `SideBySide` functionality available to them.

I would like it added to the SDK and Getting Started sites for better presentation of example requests and responses.

**Comment by nkuehn** [comment]
Nothing to do in the kit for that @industrian - the `<SideBySide>` component is available in any docs kit website, just start using it.  

Kit Documentation says it but only in one sentence at the end: https://commercetools-docs-kit.vercel.app/documentation/writing/pages 

Here's the test page with an actual example:  
 * source: https://github.com/commercetools/commercetools-docs-kit/blob/main/websites/docs-smoke-test/src/content/views/wide.mdx  
 * https://commercetools-docs-kit.vercel.app/docs-smoke-test/views/wide

**Comment by industrian** [comment]
Apologies to reopen this, but from my tests `SideBySide` only appears to display correctly on the API and Import API sites.

Please see the below screenshots for what I mean:

Correctly displays `SideBySide`:

**API**
![image](https://user-images.githubusercontent.com/77231096/154444133-5013fa92-60de-4673-8a4f-18cede0a1590.png)

**Import API**
![image](https://user-images.githubusercontent.com/77231096/154445303-44aaf37c-5559-4091-b1b9-cc5ac7605aa2.png)

Does not display `SideBySide`:

**SDK**
![image](https://user-images.githubusercontent.com/77231096/154442898-67bfebd2-a868-4e06-b9b8-8a9663d263f4.png)

**Getting Started**
![image](https://user-images.githubusercontent.com/77231096/154452351-3dbf6564-f707-489c-8638-9588d85de489.png)

**Merchant Center**
![image](https://user-images.githubusercontent.com/77231096/154445817-02ab548e-ad5f-42e0-88b5-1196c722ef4c.png)

**Comment by nkuehn** [comment]
@industrian  Then it's most likely that the sites have never been configured to allow the wide layout at all in their config.  You would set the respective flag in the `gatsby-config.js` file like it is set in the other site or take the information from the documentation:

https://commercetools-docs-kit.vercel.app/documentation/configuration/setup#available-options-for-the-theme-plugin

**Comment by industrian** [comment]
@nkuehn Thanks for the help and pointing that out. I added `allowWideContentLayout: true` to gatsby-config.js and it works as expected now:

![image](https://user-images.githubusercontent.com/77231096/154459770-45407181-6f9d-48d1-a396-35b49f3c42a7.png)
