### ISSUE TITLE
Text takes entire width of page in wide layout as opposed to usual

### ISSUE THREAD

**Issue by naveenchkrvrthy** [commercetools/commercetools-docs-kit#1242]
**Current Content:** There was [an instance](https://docs.commercetools.com/api/projects/types#resourcetypeid) where the text takes the entire width of the page (in wide screens), while the rest of the content in the page was restricted to only half of the page, as shown below.

![Screenshot 2022-02-25 at 09 42 51](https://user-images.githubusercontent.com/70849970/155683643-1da32913-aaee-4378-9be9-d3d64492ae28.png) 

vs.

![Screenshot 2022-02-25 at 09 43 06](https://user-images.githubusercontent.com/70849970/155683650-a8ef25cf-739b-4c17-8e53-f50ce31f918d.png)

Something to note, the first screenshot is a text in a RAML file, while the second one is handwritten. But, as I see other RAML generated content (like [TextInputHint](https://docs.commercetools.com/api/projects/types#textinputhint)) are also restricted to only half of the page.

**Comment by nkuehn** [comment]
The first example looks like an Enumeration.  and the other like a "normal" type.  Can you confirm that?   Could be that we forgot to properly constrain the enumeration component.

**Comment by naveenchkrvrthy** [comment]
Yes, the first one is Enumeration.
