### ISSUE TITLE
Use Markdown-inspired text definitions to create and modify diagrams dynamically

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-docs-kit#1251]
We Tech Writers think that our docs would highly benefit from visualizations like entity relationship and sequence diagrams as done in the introduction for [Product Selections](https://docs.commercetools.com/api/projects/product-selections).
Instead of embedding the diagrams as images we could use a text format from which our docs kit renders the graphical representations.
We don't need to reinvent the wheel, one example library for it is [mermaid.js](https://mermaid-js.github.io/mermaid/#/)

### Pros

- Such text representations are easier to maintain in the sense of reviewing changes to them in a pull request.
- All diagrams have the same design since it is fixed in the kit.

### Cons
- we might not have the freedom of arranging content within the diagram

**Comment by nkuehn** [comment]
Thank you for creating a proper issue to track the idea!  
The branch with the existing experiment is this here:  
https://github.com/commercetools/commercetools-docs-kit/tree/nk-try-mermaid-diagrams
