### ISSUE TITLE
Exploration: Expose "ramldoc" RAML types on GraphQL

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#126]
Based on the RMF based file generator by @jenschude, let's expose the "RAML 1.0 Datatype" files on the GatsbyJS GraphQL API. 

It can be implemented as an additional functionality in the transformer-raml  branch that we started already. 

 * still "listening" on File Node creations, still filtering for .raml via mime type. 
 * If the first line indicates it's a Data Type fragment, go into this new piece of code
 * Load the file content using a YAML parser , e.g. `js-yaml` or `yaml`
 * apply the minimum necessary transformations to safely get it into GraphQL
    * arrays to objects to get a stable GraphQL schema (see / take from legacy plugin)
    * remove the  brackets from`(annotationsInBrackets)` 
 * omit some of the fancier transformations, e.g. constants etc. 
 * Provide as a `RamlDataType`  node on GraphQL,  the parent node being the file read from. 

what do you think?

**Comment by davifantasia** [comment]
Obsolete
