### ISSUE TITLE
Color corruption in Gatsby image processing

### ISSUE THREAD

**Issue by industrian** [commercetools/commercetools-docs-kit#1284]
## Background

I am [updating some screenshots in the Getting Started guide](https://github.com/commercetools/commercetools-docs/pull/1975) and in his review @marcusschmidt-ct noted how the colors seemed off in one screenshot.

The below image shows (left) local preview and (right) the unprocessed image in VCS

![image](https://user-images.githubusercontent.com/77231096/165645439-21393ee8-f74a-40a3-957d-f67c6725dbe7.png)

I had used an image editor (Paint Shop Pro) to blur the email, first name and last name values. 

### Using another image editing software for blurring

I switched to using GIMP for blurring these details. This caused Vercel Preview and local preview to have two different results:

![Screenshot_82](https://user-images.githubusercontent.com/77231096/165646189-092721c9-daae-4ba7-bb9c-d991034151d0.png)

Also when you open the image (by clicking on it) the colors are corrupted in both instances:

![Screenshot_83](https://user-images.githubusercontent.com/77231096/165646347-69afc6bd-4a4d-4f63-b117-018f9979e484.png)

### Using the original unaltered screenshot

I then tried using the original screenshot without any editing and got the following results (locally):

![Screenshot_84](https://user-images.githubusercontent.com/77231096/165645783-4d58bdfc-0ed1-46e5-83df-fc019c5eed8a.png)

(Off topic: If anyone is curious, I used Chrome developer tools to change the displayed email to example@commercetools.com)

### Original

![Screenshot_80](https://user-images.githubusercontent.com/77231096/165645543-bc014f6a-db56-4d46-a5e8-14ef55eab3cb.png)

### Edited with Paint Shop Pro

![account_setup_old](https://user-images.githubusercontent.com/77231096/165647363-857158fd-7a35-4d11-98a7-f6c00f7df78d.png)

### Edited with GIMP

![account_setup](https://user-images.githubusercontent.com/77231096/165645562-a3b529a5-13ee-4ce0-bb77-87bb16e4f30e.png)
.

**Comment by nkuehn** [comment]
@industrian I'm trying to summarize the situation and some conclusions can be taken
 - since there is one situation where it is also wrong on the vercel preview (opening the full size image) it's not clearly a windows problem (but could still be related because the original file was processed on windows)

but I think we need a little more information, e.g. 
 - was the unaltered screenshot correct on vercel preview, too or just locally? (you just posted the local previews here)
 - does it make a difference whether the screenshot itself was taken on a windows machine or not?
 - how did you take  the original screenshot?  Windows built-in screenshotting or a special extra tool? 
 - did you use certain export and color space settings in GIMP or paintShopPro?  Stuff like this can happen if an image was accidentally converted to CMYK colorspaces and back or if a different RGP profile was applied and the export to PNG was assuming it's for print (which makes it change the colors)

**Comment by industrian** [comment]
> * was the unaltered screenshot correct on vercel preview, too or just locally? (you just posted the local previews here)

I only tested the unaltered screenshot locally.

> * how did you take  the original screenshot?  Windows built-in screenshotting or a special extra tool?

The screenshot was taken using an application called Lightshot. There's no quality/color settings when saving screenshots as PNG files.

The environment where the screenshot was taken was on 4K monitor with 200% scaling (applied in Windows Settings).

> * did you use certain export and color space settings in GIMP or paintShopPro?  Stuff like this can happen if an image was accidentally converted to CMYK colorspaces and back or if a different RGP profile was applied and the export to PNG was assuming it's for print (which makes it change the colors)

My version of PSP is incredibly old - I simply saved the file and I don't know if/how it modifies quality or color settings. For the GIMP file the settings for the export are below:

![image](https://user-images.githubusercontent.com/77231096/165867775-a0e4a024-6078-467b-8321-6ce02c38f036.png)

**Comment by FFawzy** [comment]
@industrian is this still an issue?

**Comment by industrian** [comment]
> @industrian is this still an issue in the future?

I have not re-encountered the issue since raising this issue, but that's primarily because I've not dealt with screenshots during that time.

**Comment by nkuehn** [comment]
Will you continue to work on a windows machine or did you get a mac in the meanwhile?  It will be tricky to reproduce and debug and we would only prioritize it if an actual power user has the problem in daily work.

**Comment by industrian** [comment]
> Will you continue to work on a windows machine or did you get a mac in the meanwhile? It will be tricky to reproduce and debug and we would only prioritize it if an actual power user has the problem in daily work.

I received a MacBook Pro a few days ago and will use it for taking screenshots going forward.
