### ISSUE TITLE
Deploy to Vercel fails because of invalid alias 

### ISSUE THREAD

**Issue by marcusschmidt-ct** [commercetools/commercetools-docs-kit#1319]
We have a [pull request](https://github.com/commercetools/commercetools-docs/pull/2070) with a rather long name and some hyphens in between.

**Current Behavior**

The branch slug is truncated after some characters, ending in a hyphen. Either that or the truncated name causes the build to fail.

This is taken from the Deploy to Vercel (Preview) section of the build:
```
> Assigning alias docs-prc-2277-standalone-prices-related-scopes-add-be-added-to-.commercetools.vercel.app to deployment commercetools-docs-93393t4qq-commercetools.vercel.app
Creating alias
Error! Invalid alias. Please confirm that the alias you provided is a valid hostname. Note: For `vercel.app`, only sub and sub-sub domains are supported.
```

**Expected Behavior**

Build does not fail. 

**Investigation** 
I created [another branch](https://github.com/commercetools/commercetools-docs/pull/2072) with exactly the same changes, but with a shorter name that works fine.

**Comment by nkuehn** [comment]
Documenting @timonrey 's research: 
 - the root cause is that a hyphen / minus at the end is really not allowed as a hostname in the DNS system. 
 - he'll file an issue in the upstream library that does the URL-ification of strings in our action.  Previously the maintainer was responsive, so we hope it won't take too long.

**Comment by timonrey** [comment]
I've created the ticket now:
https://github.com/rlespinasse/github-slug-action/issues/109

**Comment by timonrey** [comment]
Github-slug-action resolved this issue:
https://github.com/rlespinasse/github-slug-action/pull/111
