### ISSUE TITLE
Add pattern, minLength and maxLength to LocalizedString

### ISSUE THREAD

**Issue by industrian** [commercetools/commercetools-docs-kit#1328]
At the moment, only the string type appears to support these attributes. 

It would be nice to have this for LocalizedString for use in slugs.

![image](https://user-images.githubusercontent.com/77231096/174106705-9559123a-f3ec-4ed1-af64-42fe0fbcee4e.png)

![image](https://user-images.githubusercontent.com/77231096/174106843-432da85e-60bc-4045-af1c-e9419d22bfda.png)

**Comment by FFawzy** [comment]
@jenschude can you please explain the situation to @industrian ? `LocalizedString` is an object type

**Comment by jenschude** [comment]
I don't think this would work as intended as it's invalid RAML.

Only possibility would be to add some user-defined facets to the LocalizedString like here:

https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#user-defined-facets

**Comment by stmeissner** [comment]
My two cents to this: 
It only makes sense to model the restrictions in RAML when there is some validation in place enforced by the API, I would say.
If it's more like a hint on how to construct a valid slug we can say this in the `description` of the respective property (what is possible already). I don't really see an issue here.
