### ISSUE TITLE
Provide example for use of URN-style addressing of API endpoints

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-docs-kit#1339]
Similar to the [example we have for API types](https://github.com/commercetools/commercetools-docs-kit/blob/main/api-specs/test/types/descriptions-with-urn-links.raml#L4):  `[ObjectTestTypeDraft](ctp:test:type:ObjectTestTypeDraft)` we would like to have an example for URN-style links to **API endpoints** that should also be supported by the [API docs theme](https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-theme-api-docs/src/utils/ctp-urn.js).

**Comment by naveenchkrvrthy** [comment]
I remember from one of [Nikolaus's comment]( https://github.com/commercetools/commercetools-docs/pull/1171#discussion_r655167626).
