### ISSUE TITLE
Issue with style check for JSX elements with a `.` in the name

### ISSUE THREAD

**Issue by emmenko** [commercetools/commercetools-docs-kit#1341]
Seems to be related to these recent changes: #1321 

<img width="490" alt="image" src="https://user-images.githubusercontent.com/1110551/178750627-5bbd217b-62dd-4aa5-8721-36b8b71e15ed.png">

I think the regex needs to be adjusted.

**Comment by timonrey** [comment]
Yes, thank you. I will add it to the board 👍🏼

**Comment by emmenko** [comment]
Found another regression:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/1110551/193021573-5388e8d7-8f40-4f8c-bacc-02bb62d19615.png">

**Comment by nkuehn** [comment]
Sorry, got lost between bigger projects.  Unfortunatly we have to find the MDX expressions ourselves   The place to go is 
here: https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/writing-style/.vale.ini#L15  

The current regex is only covering self-closing tags because only these were a practical issue until now.   We'll have to make it more paranoid and add opening and closing tags, too. 

> Found another regression:

Github Style links (without explicit markdown link syntax) are not supported,  ideally generally not used e.g. for refactoring, finding links etc.   If you want just the text, ideally make it a string literal  `https://foo/bar`

**Comment by emmenko** [comment]
> Github Style links (without explicit markdown link syntax) are not supported, ideally generally not used e.g. for refactoring, finding links etc. If you want just the text, ideally make it a string literal `https://foo/bar`

Not sure I get the point. This is not a normal link, it's using a code block to show the URL format.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/1110551/193828211-ba0ce8f6-a5b8-4aa3-b619-c0391127af92.png">

https://github.com/commercetools/merchant-center-application-kit/blob/20c0be80ea2bb959c9f298cb7f6784841acef948/website/src/content/concepts/merchant-center-api.mdx?plain=1#L134-L136

How do you suggest to proceed with this?

**Comment by gabriele-ct** [comment]
@emmenko and @nkuehn 
are you sure the first error (regarding `<Foo.Bar>` tag) is still relevant?
I've tried pulling latest main and I don't get that error:


![Image](https://user-images.githubusercontent.com/106664971/193827894-64c76d5d-5ed6-409f-a69a-7ed185b40dcd.png)

In fact Vale should not validate fenced blocks: https://vale.sh/docs/topics/scoping/#markdown but it might be something wrong with my local setup.

I get the error when the code is not in a codeblock or fenced:


![Image](https://user-images.githubusercontent.com/106664971/193828462-5f704cdc-9082-4ca8-83fc-7297683802bd.png)

But this should be fine: a tag should exist in a fenced or codeblock all the times right?

**Comment by nkuehn** [comment]
> in fact Vale should not validate fenced blocks:  
@gabriele-ct  yes, that's what I first thought too but it seems to try to be even more "magic" by parsing the content of the fenced block according to the language annotated.  So technically spoken this is a "wrapped" scenario - it thinks this is not a proper element. 

> This is not a normal link, it's using a code block to show the URL format.
@emmenko yes, sorry for not looking carefully enough. 

> Seems to be related to these recent changes: https://github.com/commercetools/commercetools-docs-kit/pull/1321
I'm not 100% convinced - I rather suspect a vale update that came with the writing style update. 

> I get the error when the code is not in a codeblock or fenced:
I guess we need to support that case anyways, so if as a side effect Nicolas case is working again too even if we can't reproduce it that's fine.

**Comment by gabriele-ct** [comment]
Let's try to define some proper requirements here as I'm not sure what we expect.
1. Tag names with dots should pass validation both when fenced or when not fenced.
e.g. both these case should be valid:
<img width="278" alt="Screenshot 2022-10-05 at 11 14 16" src="https://user-images.githubusercontent.com/106664971/194025411-9a5957b7-3481-4d40-ad69-5326db039d04.png">
2. When `mc` case insensitive is part of a url, should be valid

Am I missing something? @nkuehn @emmenko

**Comment by emmenko** [comment]
So far we encountered these two issues in AppKit.

Thanks for looking into it!

**Comment by gabriele-ct** [comment]
I created with the regexp changes.
Here's some example:
<img width="571" alt="Screenshot 2022-10-05 at 12 56 25" src="https://user-images.githubusercontent.com/106664971/194047792-5f7ca567-360a-430e-96ba-fdb5631f7347.png">

And for url validation:

<img width="647" alt="Screenshot 2022-10-05 at 13 01 13" src="https://user-images.githubusercontent.com/106664971/194047843-a4e91e1e-85b7-48eb-b48a-908d6c73d7b5.png">

**Comment by nkuehn** [comment]
@gabriele-ct  thanks for the regex work. 

One consideration:  This matches whole JSX blocks including the content inside them, but this is likely not what we need in our docs situation.   A typical pattern is that we have JSX tags that include markdown content, e.g. Subtitle, Info, Warning etc. .   The content would now not be checked any more if the Rule becomes a vale `BlockIgnore`.   

Example:

```mdx
<Info>

This is CommerceTools written the wrong way. It should still be **checked**.  The blank lines above and below indicate MDX v1 to interpret this as markdown content which is then rendered and passed as `children`. This is a <Beta /> feature.

</Info>
<Info>This is rendered as a string as it is in MDX v1. It is used in the docs, too and the text should be checked.</Info>
```

Starting MDX v2, the blank lines can be omitted:

```mdx
<Info>
This is CommerceTools written the wrong way. It should still be **checked**.  MDX v2 will interpret the children string as mardkown without special indication. 
</Info>
<Info>Not sure how MDX v2 will handle this but it has to be checked by vale</Info>
```

To see how MDX parses that respectively you can try ASTexplorer (this example here: https://astexplorer.net/#/gist/6f8dceedbe4cd239a1ca505708c03054/60e6841564398b09f3a17e7f56574dd9f1f96daf )

For me that means that the Expressions have to match the actual Tags only, but not the contents. 

Implementation Problem:  It could be that we have to do this as a vale `TokenIgnore` and not a `BlockIgnore` for that purpose.  When I created the current setup I took the "Minimally invasive" approach and wanted to address only the specific case of our API documentation blocks which was the specific known problem at the time. 

In any case, we should create a test page in the docs-smoke-test site or some other test setup that has all those scenarios, to not start to run circles around conflicting use cases.

**Comment by gabriele-ct** [comment]
After a quick meeting with @nkuehn we agreed that this ticket is probably just the tip of the iceberg of a bigger issue regarding the lack of clear requirements in validation rules definition.
As consequence we also agreed that a broader process of review/definition of validation rules should happen adding some test validations helping to ensure we don't introduce conflicting  rules.

As for this ticket I'll just apply the `mc` url validation and disregard the tag part.
For the time being we should add the `<!-- vale off -->` and `<!-- vale on -->` comments surrounding the blocks we want to be considered valid.

**Comment by gabriele-ct** [comment]
For future reference, this rule, added to the `vale.ini` file, seems to solve the actual tag name validation:
`TokenIgnores = (?si)<[A-Z0-9.=\'\" \/]*>`

**Comment by emmenko** [comment]
We're still having errors with the latest version `v3.3.1`.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/1110551/197159626-4e3e5fd6-66c4-4fdb-b7d1-88de7f2bd2d6.png">

**Comment by gabriele-ct** [comment]
> We're still having errors with the latest version `v3.3.1`.
> 
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/1110551/197159626-4e3e5fd6-66c4-4fdb-b7d1-88de7f2bd2d6.png">

@emmenko please see: https://github.com/commercetools/commercetools-docs-kit/issues/1341#issuecomment-1271311164

**Comment by emmenko** [comment]
Ah thanks, I somehow missed that part.

**Comment by emmenko** [comment]
It doesn't seem to work 🤔

<img width="605" alt="image" src="https://user-images.githubusercontent.com/1110551/197173525-9fc34938-1721-4f9c-a1d0-3505e76adfd8.png">

**Comment by gabriele-ct** [comment]
@emmenko what's the repo you're working on? I've been trying on docs-kit and seemed fine

**Comment by emmenko** [comment]
app-kit

**Comment by gabriele-ct** [comment]
That's strange.
I just cloned the repo and setup the vale plugin.
This is what I get:
<img width="929" alt="Screenshot 2022-10-21 at 14 02 43" src="https://user-images.githubusercontent.com/106664971/197191468-2a08b15a-ef98-4d0e-961c-e6c31aa549d4.png">

**Comment by emmenko** [comment]
Try running the command `yarn lint:text`.

**Comment by gabriele-ct** [comment]
Still , I don't get that error:
<img width="1179" alt="Screenshot 2022-10-21 at 14 34 39" src="https://user-images.githubusercontent.com/106664971/197209445-d45d3b3c-f441-45a6-ad38-5ad2523f91b4.png">
