### ISSUE TITLE
Modifications to examples are not being cached properly

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#1349]
We've noticed that updates to content inside of examples are not being cached properly.

@nkuehn Input would be appreciated :)

**Comment by nkuehn** [comment]
this looks like we are "sideloading" data into the API type and Resource Gatbsy Data nodes without invalidating the cache. 

The Type nodes parent is the file node of the RAML_DOC File.  But the content of the examples property is loaded from the example files separately ( here :  https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-transformer-raml/src/utils/resource/examples-to-array.js#L6 ).   So if the RAML_DOC does not change but the example file does change gatsbyjs does not trigger invalidation and recalculation of the Type data node.  

Interestingly, the digest (content hash) of the Type node is actually changing (we do digest over the complete data including the examples content:  https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-transformer-raml/src/create-type-node.js#L38 ) - so it seems that the cache is purely driven by the parent node tree.  

Many approaches could be taken here:
 - change the RAML_DOC generator to inline the example files into the RAML (this might be architecturally the cleanest approach, even if it leads to data duplication
 - find the file nodes matching the example JSON filea and create explicit parent-child relationships to it when creating the Type and Resource (this would be the "low-level-gatsby-ish" way)
 - don't inline the examples into the Type node at all, leave them to be own file nodes and create properties on the Type / Resource nodes that point to them and can be expanded at GraphQL query time. 

I personally like the first most, if RAML_DOC becomes a more broadly used intermediate representation for publication of our API specs it would be most consequential to inline everything and not just nearly everything into these files.  (@jenschude  opinions concerning examples in RAML_DOC?)

**Comment by nkuehn** [comment]
@jenschude could you do us a favor and look into this?  It's become a real issue in the meanwhile.  Thank you!

**Comment by jenschude** [comment]
I just tagged https://github.com/commercetools/rmf-codegen/releases/tag/0.1.41 released at NPM as 13.25.0

This adds an `--inline-examples` flag to the codegen.

**Comment by nkuehn** [comment]
> I just tagged https://github.com/commercetools/rmf-codegen/releases/tag/0.1.41 released at NPM as 13.25.0
> 
> This adds an `--inline-examples` flag to the codegen.

thank you for going through the hassle of making this work robust! 

concerning the implementation in the kit: This could be an opportunity to reduce the complexity of the API further.  Let's check whether we still need to be able to address the example files separately at all.

**Comment by timonrey** [comment]
Status update:
There is a specific edge case where the examples are not being inlined into the RAML. That only happens twice in the smoke tests but it's hard to anticipate how it would behave on the actual docs content. If we really want to rely on the examples being inlined in every case, we would need to fix that first. The reduction of the API complexity also depends on that.
I will talk to @jenschude once he is back.
