### ISSUE TITLE
"Mess" less with the webpack config - possible cause of build issues in user repos (bun:ffi  and cbor-x related errors)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1352]
We're doing quite some modifications to the webpack config, including completely overriding it at the end of the process, which is critical because gatsby is effectivey a huge webpack config. 

Currently we have issues upgrading some repositories to new kit and gatsby versions because of certain issues with lmdb code loading "bun:ffi" and "cbor-x" native modules.   At least "cbor-x" is handled as an exception in gatsby's webpack code to tell it that it's external.   

I was able to downgrade the transitive lmdb dependency manually through yarn resolutions but it's not a solution.  It's not easy to debug because the problem does not seem to occur in the docs-kit repository (and not even in the commercetools-docs internal repo but only in other repos using the kit). 

It's to a certain degree a guess that we may accidentally override some of gatsby's own webpack configuration.

https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-theme-docs/gatsby-node.js#L482 

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts#L83

**Comment by nkuehn** [comment]
This is the yarn resolution to downgrade lmdb as a temporary hack: 
```json
  "resolutions": {
    "lmdb": "2.3.9"
  },
```

**Comment by emmenko** [comment]
FYI: in appkit I'm using the [packageExtensions](https://yarnpkg.com/configuration/yarnrc#packageExtensions) functionality (Yarn v3).

```yaml
packageExtensions:
  "lmdb@^2.5.3":
    dependencies:
      "cbor-x": "^1.3.1"
```

https://github.com/commercetools/merchant-center-application-kit/blob/bcb5e167bbc8dc660ba7fb11c94f7cf3918736f0/.yarnrc.yml#L3-L10

**Comment by nkuehn** [comment]
That looks good @emmenko  and does not lock us to an old dependency.  I'll try if it solves the `bun:ffi` error, too.

**Comment by nkuehn** [comment]
Update: the issue seems to be still present, it just popped up in the internal content repo, too.   We'll apply the same workaround there for now

**Comment by FFawzy** [comment]
manual Webpack config turned out to be necessary and the other topic will be handled [here](https://github.com/commercetools/commercetools-docs-kit/issues/1419)
