### ISSUE TITLE
Mobile view of Tables can't handle links (or any markdown) in table headers

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1353]
By chance I found out that the table rendering has issues in mobile viewports when the tables are stacked above each other row by row.   If a table header contains a link (or maybe even any markdown microformatting) that header is just rendering `[object Object ]`

```md
| [column head 1 as link](#anchor) | column head 2 | column head 3  |
| ------- | -------- | -------- |
| row 1       | foo       | cool       |
| row 2       | bar       |  less cool |
| row 3       | baz      |            |
```

| [column head 1 as link](#anchor)                | column head 2                                           | column head 3  |
| ------- | -------- | -------- |
| row 1                         | foo       | cool                |
| row 2                    | bar       |  less cool |
| row 3                  | baz      |            |

**Comment by FFawzy** [comment]
either the site build fails 
or
don't use the link
or
fix it and render it

the goal: do not let it fail silently
