### ISSUE TITLE
Regex properties currently only work for string types

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-docs-kit#1357]
I would like to render a property whose key is only defined with a regular expression like demonstrated in the [API smoke test](https://commercetools-docs-kit.vercel.app/api-docs-smoke-test/types/general#regexpropertytesttype).

The respective RAML spec looks like this:

```
properties:
  /^[a-z]{2}(-[A-Z]{2})?$/:
    type: string
```
The difference to my use case is that the type of my property is not `string`, but some object:

```
properties:
  /^[a-z]{2}(-[A-Z]{2})?$/:
    type: SearchKeyword[]
```
That causes following error on the page:

> Error in function NameType in ../../node_modules/@commercetools-docs/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js:58
>
> typeToRender.type.toLowerCase is not a function

Could you please add support for data types other than string also?

**Comment by industrian** [comment]
I believe this issue is also on the following PR: https://github.com/commercetools/commercetools-docs/pull/2250
