### ISSUE TITLE
Allow to control order of release notes for the same day

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-docs-kit#1364]
Sometimes we have more than one release notes at the same day. It happens in the release note feed that the release notes are not ordered by the times they have been released. We want to have the most recently published release note to appear on top of the feed, but this is currently not guaranteed and we don't see a way to control the ordering by time. (By day it works fine.)

I'm afraid that RSS feed readers will not get notified upon new release notes when they are not appearing last in the feed.

Could you please investigate?

**Comment by FFawzy** [comment]
Idea:- Defining a new frontmatter field (eg, orderHint) to tackle the order of release on the same day only
