### ISSUE TITLE
Regression: Release notes filter inputs overflow invisibly

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1382]
By chance I found a regression that makes the release notes filter unusable in certain viewports:

https://commercetools-docs-kit.vercel.app/docs-smoke-test/releases

<img width="493" alt="image" src="https://user-images.githubusercontent.com/4006139/195881353-45591102-d72d-4483-81c2-beadc2639074.png">

I have not been able to seen when it came into place so we'll have to fix it without knowning the original cause.

**Comment by emmenko** [comment]
I noticed that too, thanks for opening an issue.

I can look into it after #1372

**Comment by nkuehn** [comment]
Does not have to be you, we have sprint planning on monday and can pull it in.
