### ISSUE TITLE
Page with Mermaid crashes " Unsupported color format: "40%)"

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1384]
The current https://commercetools-docs-kit.vercel.app/documentation/writing/images    docs kit documentation site crashes client side when a mermaid diagram is loaded.  

Let's verify it's not in production on the docs already.

**Comment by FFawzy** [comment]
most probably [this](https://github.com/commercetools/commercetools-docs-kit/blob/00b32fb0fc82ffc32f35cab10ceffca6e543fb1f/packages/ui-kit/src/components/mermaid-client-side.tsx#L32) line is causing the issue

**Comment by nkuehn** [comment]
maybe maybe a regression from merging the new MC UI kit tokens, they use HSL expressions for colors. 

Here it is applied:
https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/ui-kit/src/components/mermaid-client-side.tsx#L32

Here it is defined: https://github.com/commercetools/ui-kit/blob/main/design-system/src/design-tokens.ts#L15 

The `cssVarToValue` function that  @emmenko  created to grab the fallback value ( https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/ui-kit/src/utils/css-variables.ts ) solves a similar problem but not this.  

Mermaid is an SVG generator so I guess it needs exact absolute RGB colors.  We can either resolve the colors and hardwire them, just referencing the vars or we can look for a way to resolve the HSL statement to a color code (it's client side only code, so maybe some browser API or hack? )

**Comment by nkuehn** [comment]
As long as it stays in the client-side component module we can let the browser wrestle all the pesky details of color expression parsing:

```js
const normalizeCSSColorExpression = (exp) => {
  const element = document.createElement("span");
  element.style.color = exp;
  return element.style.color;
}
```
returns `rgb(66, 120, 138)`  for our `hsl(195, 35.2941176471%, 40%)` value.  If the mermaid or SVG code does still not like that it is doable to extract a hex code from the rgb string reliably.
