### ISSUE TITLE
Use Gatsby's built-in support for modifying the document head

### ISSUE THREAD

**Issue by emmenko** [commercetools/commercetools-docs-kit#1389]
```
warning gatsby-plugin-react-helmet: Gatsby now has built-in support for modifying the document head.
```

Learn more at https://gatsby.dev/gatsby-head

**Comment by gabriele-ct** [comment]
Ensure this https://github.com/commercetools/commercetools-docs-kit/issues/1456 issue is solved by this upgrade, otherwise, create an investigation ticket
