### ISSUE TITLE
Regression in a specific branch. Dropdown caret in multilanguage code examples not visible

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1397]
The caret sign for dropping down the list of languages in multilanguage code examples has become black (from a light tone) and is now not practically visible any more, making it look like there are only Java examples for everything

<img width="371" alt="image" src="https://user-images.githubusercontent.com/4006139/196800255-eef07ff6-e7e2-4b0f-b448-624c1573ab71.png">

I wonder why VRTs did not catch this.

**Comment by emmenko** [comment]
Where do you see this?

In the docs kit it looks fine:

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/1110551/196807060-f0fa458e-2cb0-41fa-82cc-633aad5744cf.png">


https://commercetools-docs-kit.vercel.app/documentation/writing/code#multiple-languages

**Comment by nkuehn** [comment]
Thanks for checking.  I found it in a branch preview that is related to reformatting the java code examples.   But it's not in the live site.  We have to find out whether the changes in that branch are the issue or whether it's out of sync with main or something.  

https://docs-java-prettier.commercetools.vercel.app/getting-started/make-first-api-call

**Comment by FFawzy** [comment]
cannot reproduce and it is fine on production 
https://docs.commercetools.com/getting-started/make-first-api-call
