### ISSUE TITLE
Fix the missing configuration for learning plugins in the docs-kit repo

### ISSUE THREAD

**Issue by gabriele-ct** [commercetools/commercetools-docs-kit#1401]
build output on gh actions in docs kit

- Check gh secrets

**Comment by gabriele-ct** [comment]
@FFawzy and @timonrey do you happen to remember what as the failing build?
I can't remember where we saw the problem and having checked the secrets on docs-kit repo seem to be ok.



![Image](https://user-images.githubusercontent.com/106664971/200618863-31befac7-5f7d-4e6b-96cd-95c749ebbdc4.png)
![Image](https://user-images.githubusercontent.com/106664971/200618864-d3fb1abc-3f0d-4a79-aa2a-659248a22f14.png)
![Image](https://user-images.githubusercontent.com/106664971/200618865-7200f699-6b2b-4392-b6d0-cf41e2c0dee5.png)

**Comment by FFawzy** [comment]
@gabriele-ct 
the problem was that these secrets are not available locally for other users of the docs-kit, and we ended up hardwiring the secrets in the plugin.

we did that already in the docs repo now we need to do it again here in docs-kit

**Comment by gabriele-ct** [comment]
Thanks for clarifying that @FFawzy 
Expected ticket outcome is:
- doc-kits should be buildable without needing any .env file.

This means all github secrets should disappear (as we agreed they're not real secret) and the `gatsby-config.js` file should use hardcoded values, as we do in `docs` repo
