### ISSUE TITLE
@commercetools-docs/writing-style issue in mdx files when using inner components

### ISSUE THREAD

**Issue by CarlosCortizasCT** [commercetools/commercetools-docs-kit#1404]
When trying to update the [@commercetools-docs/writing-style](https://commercetools-docs-kit.vercel.app/documentation/configuration/packages#commercetools-writing-style-linter) package to version `3.3.1` we found a problem where some of the content in `.mdx` files raises unwanted errors.

The context is a `.mdx` file where we use React code snippets that use components which export internal subcomponents.
This is an example:
![image](https://user-images.githubusercontent.com/97907068/197192445-02a2821c-efcc-4d25-a1a1-7c223826849a.png)

Here the `Spacings` component exposes some inner components and, in this case, we are using the `Spacings.Stack` one.

When we lint this file with the latest version of `@commercetools-docs/writing-style` package, the process fails with this kind of error:
![image](https://user-images.githubusercontent.com/97907068/197192736-9adf2ee5-0a6b-48f9-8625-e7575d13ae7e.png)

It seems these use cases should not being treated as errors so I would like to know if there is some configuration we can apply to fix the situation or whether this is something that would need to be addressed releasing a new package version.

Thanks.

**Comment by emmenko** [comment]
Duplicate of #1341

We should keep it pinned and not update that package yet.

**Comment by CarlosCortizasCT** [comment]
Closing as this is a duplicate.
