### ISSUE TITLE
Make the whole banner area overridable

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#1413]
We decided that we don't want to show the user research banner in the frontend microsites. However, if we override the banner components with an empty component, the layout still shows a border on the left.
So we need to be able to override the whole banner area in the top-right corner if we don't want to show any banners or other content.

**Comment by nkuehn** [comment]
Not a kit issue, needs to be done in the content repository by shadowing the component with a blank one.
