### ISSUE TITLE
Render request headers 

### ISSUE THREAD

**Issue by mar-gil** [commercetools/commercetools-docs-kit#1427]
In the endpoint description, we would need to render the request headers contained in Frontend APIs RAML files.

```yaml

get:
  is:
    - right-header
    - frontastic-locale
  headers:
    Frontastic-Path:
      displayName: Frontastic Path
      type: string
      description: Path
      required: true
      pattern: ^/.*$
  description: Returns the structure and data of the published page displayed from commercetools Frontend.
  responses:
    200:
      description: Page folder information, page structure, and data source data.
      body:
        application/json:
          type: PageResource
    404:
      description: Page folder not found.
      body:
        application/json:
          type: Error
          example: !include ../examples/PageFolderError.raml
          
```

**Comment by FFawzy** [comment]
are the headers the same in every endpoint?
one way to look at it is that if they are the same across all the endpoints maybe we want to explain it once in a separate page?
or is it necessary in every page ?
WDYT?

**Comment by mar-gil** [comment]
> are the headers the same in every endpoint? one way to look at it is that if they are the same across all the endpoints maybe we want to explain it once in a separate page? or is it necessary in every page ? WDYT?
> 
> [this](https://docs.commercetools.com/api/general-concepts#correlation-id) is an example of a custom header in the CoCo responses as well but we defined it once in a page

@FFawzy sorry for the late reply. I must have missed the notification. 
Nope, the headers are not always the same. Furthermore, some are standard headers while some are "frontend-custom" headers. Therefore, I think that having a shared separate page would not be ideal.

**Comment by gabriele-ct** [comment]
@timonrey First step is to make and analysis of the ticket and the expected outcome is a tech proposal on how to implement the feature (check if rmfgen is supporting this feature)

**Comment by timonrey** [comment]
I tried out the raml file that is provided in the description with the custom header to see if rmf-codegen supports this data structure, but it looks like the headers are not being generated.

@jenschude maybe you can double-check, but we will probably need an update from the rmf-codegen to support this use-case. Any thoughts from your side are welcome as always ;)

**Comment by mar-gil** [comment]
> I tried out the raml file provided in the description with the custom header to see if rmf-codegen supports this data structure, but it looks like the headers are not being generated.
> 
> @jenschude maybe you can double-check, but we will probably need an update from the rmf-codegen to support this use-case. Any thoughts from your side are welcome as always ;)

@timonrey (cc @jenschude) what I did was moving the first headers "in the method" like this: 

```raml
get:
  is:
    - right-header
    - frontastic-locale
  headers:
    Frontastic-Path:
      displayName: Frontastic Path
      type: string
      description: Path
      required: true
      pattern: ^/.*$
  description: |
```

I forgot to update the issue description, now it's updated. They are rendered in the cURL examples now, but we would also need to render them in the endpoint description. For the moment, they're handwritten. 
![image](https://user-images.githubusercontent.com/63046911/213629781-e656eb91-1b79-471e-ac2c-bcc5a6f1b053.png)

**Comment by jenschude** [comment]
Update to at least version 13.23. of the codegen. Then the headers are in the resource files and the curl examples

**Comment by stmeissner** [comment]
Why is this issue blocked?

**Comment by Anshuman71** [comment]
@timonrey can we help clarify anything to unblock this issue?

**Comment by timonrey** [comment]
If I remember correctly, there was still a problem with the data structure rmf-codegen can work with. But maybe that's not the case anymore. I will unblock it and revisit the issue.

**Comment by timonrey** [comment]
Update: The rmf codegen is generating the required fields correctly so we can move forward with the implementation as soon as agreed on the design. @zbalek

**Comment by Anshuman71** [comment]
Hi @timonrey, we need to do some work on Frontend API docs before this feature goes live on the published docs. Do you have a timeline for the release of this change? So we can prepare.

**Comment by timonrey** [comment]
@Anshuman71  We can release it whenever you feel ready. If it's not too much work you could also adjust the frontend API in the release preview PR in the docs repo.

**Comment by Anshuman71** [comment]
Hi @timonrey, thanks. Can you link the preview PR here? I'll start the work on it.

**Comment by timonrey** [comment]
https://github.com/commercetools/commercetools-docs-kit/pull/1978
