### ISSUE TITLE
Render request body of web forms

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-docs-kit#1430]
We have the need to document POST request bodies with content type: `application/x-www-form-urlencoded`

Given the following RAML specification for a  POST request in which the `properties` are listed individually (_format 1_):
```yaml
post:
  displayName: Search Products by post
  description: |
    The query parameters are included in the body encoded in `application/x-www-form-urlencoded`.  
  body:
    application/x-www-form-urlencoded:
      properties:
        fuzzy?:
          type: boolean
          description: |
            Whether to apply [fuzzy search](#fuzzy-search) on the text to analyze.
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/product-projections-search.example.json
          type: ProductProjectionPagedSearchResponse
```

The Docs Kit could also support the below format with specifying the `type` that contains the properties (_format 2_):
```yaml
  body:
    application/x-www-form-urlencoded:
      type: SearchQueryParameters
```
This is currently supported for  `application/json` bodies, but it does not render it by mentioning the type as Link what would be consistent with payloads of other POST requests:

<img width="743" alt="render-type-with-link" src="https://user-images.githubusercontent.com/900598/202449506-4cc3d917-b782-4ab9-baa8-937cd286570c.png">

Instead, it lists all the properties of the specified type:

<img width="778" alt="render-type" src="https://user-images.githubusercontent.com/900598/202449140-d37be7c3-26b6-45c8-bbbf-145173f68b74.png">

The latter rendering I suggest to apply for the case of _format 1_.
I also suggest to mention in the label for the **Request Body** something like _URL-encrypted key-value-pairs_.

**Comment by FFawzy** [comment]
decision: 
adding the content/mime type after the request body and support not having a mime type and no request body type
