### ISSUE TITLE
[EPIC] Upgrade to `Gatsby 5`

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#1438]
See release notes with more explanation: https://www.gatsbyjs.com/docs/reference/release-notes/v5.0/

Migration Guide: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/

Key topics:

* Requires Node 18 (not available on Vercel, but that does not matter for a kit website because we're building on GH actions and Vercel is just there for fancy static hosting)
* Requires React 18
  * Note: UI Kit does not support React 18 yet.
* `trailingSlash` is [defaulting to always now](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#trailingslash-is-set-to-always), but it likely would not break because we have manually overridden that
* we can remove the manual browserslist config again, it's now [defaulting to requiring ESM supporting browsers](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#non-esm-browsers-are-not-polyfilled-by-default).
* need to rewrite some graphQL queries (sort parameters)
* remove the feature flags that triggered advanced features
* Images DOM might have changed, need to review the CSS
* performance: if we use the new slice API for header / footer / nav / search we may be able to improve build times (maybe 10%?)

**Comment by nkuehn** [comment]
Another topic we might add  here:   gatsby 5.3 will start supporting ESM format for gatsby-config.(m)js and gatsby-node.(m)js.   If we migrate config and node to ESM we can get rid of all the hardwired old versions of the remark / unified libraries that we rely on so heavily.

**Comment by FFawzy** [comment]
closed as done
