### ISSUE TITLE
Incorrect page title in static pregenerate HTML (only react hydration sets the correct title)

### ISSUE THREAD

**Issue by Anshuman71** [commercetools/commercetools-docs-kit#1456]
The commercetools Frontend Documentation page shows: "commercetools Composable Commerce documentation" as the title before React Hydration (JavaScript execution) and replaced with the correct title after hydration.

The static pre-generated site seems to have the "commercetools Composable Commerce documentation" as the title, only replaced by the correct one after React Hydration. It affects all open graph `<meta>` tags.

The image below is the Slack preview of the URL: https://docs.commercetools.com/docs/frontend.

<img width="561" alt="08-12-2022-at-15-54-23@2x" src="https://user-images.githubusercontent.com/28081510/206422805-2df0366a-911e-45a0-b27d-7950eca709bd.png">

**Recreating the issue**

Use the https://docs.commercetools.com/docs/frontend link in a Slack message and check the link preview.

or

Disable JavaScript in your browser and open the  [URL](https://docs.commercetools.com/docs/frontend link) in the browser

![08-12-2022-at-16-07-12@2x](https://user-images.githubusercontent.com/28081510/206425672-0b9bbe0d-f66c-4e23-9be2-f0c154e6f93a.png)

**Comment by nkuehn** [comment]
@Anshuman71  thank you!  I reworded the title a bit,  a smaller delay would not fix it - the static pregenerated content has to be already containing the correct title.  
Googles crawler runs javascript but most simpler snippet builders don't.  So it has to be in the static page.

**Comment by gabriele-ct** [comment]
Relates to https://github.com/commercetools/commercetools-docs-kit/issues/1389
Probably it's worth try to use the new native Gatsby function and see if this fixes the issue.
Currently we're relying on `gatsby-plugin-react-helmet` library.
