### ISSUE TITLE
Apply the same padding and spacing to SVG images as to pixel images processed by gatsby

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1460]
SVG images can be embedded in markdown but do not go through the processing pipeline and do not receive the automatic picture element wrapper with spacing etc. 

To not have to hardwire the spacing and padding into all individual diagrams the learning team would like SVGs (and/Or any other images that are not inside the gatsby image wrapper) to have at least the 8px padding left/righ and 16px top/bottom margin.

**Comment by FFawzy** [comment]
if a body paragraph has an <img> as a direct child element it should get the spacing
