### ISSUE TITLE
continue working on MDX v2 migration

### ISSUE THREAD

**Issue by FFawzy** [commercetools/commercetools-docs-kit#1472]
mainly focusing on the API microsite

Goal:- 

- MDX v2 is working on docs-kit
- Wiki Page with relevant changes that they need to know

**Comment by gabriele-ct** [comment]
@nkuehn as expected, it doesn't work out of the box but I've got the feeling we're not too far and I'm missing something you might find out quickly. I've been spending some time trying to figure out what are the difference between the original implementation and the mdx2.
Essentially the compiled version of the mdx file has a very different structure but that should not affect the resulting babel compiled ast tree (at least to the extent that we're concerned).
If you have some time tomorrow, I'd like to show you what I've found before deciding to ditch the introspection plugin.
