### ISSUE TITLE
Clarify software license for open source packages

### ISSUE THREAD

**Issue by emmenko** [commercetools/commercetools-docs-kit#15]
@nkuehn what is your idea for licensing the packages here?

**Comment by nkuehn** [comment]
The code parts are relatively easy (if you don't do MIT it's unlikely to be adopted a lot).  But I have to research or talk to Camilo how to regulate the visual design assets, logos etc which are under strict CT copyright AFAIK.

**Comment by nkuehn** [comment]
FYI @emmenko @davifantasia 

I spoke to camilo about the topic.  There are no legal terms for design copyright decided yet here but for documentation we can start with putting up the images and design artwork unlicensed and the code under MIT.
