### ISSUE TITLE
Move learning-tech packages to the docs-kit repo

### ISSUE THREAD

**Issue by gabriele-ct** [commercetools/commercetools-docs-kit#1512]
The requirements are:
 - move `@commercetools-docs/gatsby-theme-sso-ui-kit` package from learning-tech to docs-kit repo
 - move `@commercetools-docs/gatsby-theme-learning` package from learning-tech to docs-kit repo

Ensure the packages are correctly referenced by docs-smoke-test website rendering both login/loguot component and quiz

**Comment by FFawzy** [comment]
@gabriele-ct 
will this ticket include the cleanup in `learning-tech` too? or is there another issue for that

**Comment by gabriele-ct** [comment]
@FFawzy I want to reduce the scope of the tickets, so I prefer to create a ticket for `learning-tech` cleanup, and e2e testing separately. We can create them in the next daily

**Comment by FFawzy** [comment]
yea sure .. no problems I was just asking thats all
