### ISSUE TITLE
Migrate e2e/unit from learning-tech to docs-kit repo

### ISSUE THREAD

**Issue by gabriele-ct** [commercetools/commercetools-docs-kit#1515]
Having migrated the learning-tech FE packages to the docs-kit repository, we would like to migrate the current e2e and unit test from the learning-tech repo into the docs-kit.
- Ensure the unit tests are still runnable and valid
- Implement required changes to run the existing e2e scenarios against the `docs-smoke-test` website

**Comment by FFawzy** [comment]
closed by pr #1574
