### ISSUE TITLE
[SL] UX decisions/strategy for Self-Learning Homepage

### ISSUE THREAD

**Issue by lukpan** [commercetools/commercetools-docs-kit#1525]
This is a more medium-term task (Q2/Q3), and would require a conversation to really begin to draw out the detail. Our Self-Learning homepage requires some significant decisions as to its usability. Some areas for discussion:

- Naming of the site
- Microsites for each learning path versus having all learning paths on one site
- Experience of logging into moodle quizzes
- Experience of creation of CommercetoolsID account
- Left-hand navigation menu design and development (how best to structure/present this? Should there be ticks on the menu items when a learner has covered that part of the module?)
- General page design and layout - how can we improve the experience of learning on this site?
- Systemization of design assets for flowcharts/infographics/videos etc so that there is a consistent look and feel across the self-learning site.

Issue opened by @lukpan

**Comment by FFawzy** [comment]
closing as duplicate
