### ISSUE TITLE
Investigate the compatibility of Gatsby 5 with mdx v1

### ISSUE THREAD

**Issue by gabriele-ct** [commercetools/commercetools-docs-kit#1538]
Check if Gatsby 5 is compatible with gatsby-plugin-mdx@3.x (mdx 1)

**Comment by gabriele-ct** [comment]
In order to verify the above I have:
- created a generated Gatsby 5 project which includes mdx support using the gatsby-cli
- Downgraded `gatsby-plugin-mdx` to 3.20.0 (the same used in the docs-kit)
- Downgraded `@mdx-js/*` to 1.6.22 (the same used in the docs-kit)
- Added `md5-file": "^5.0.0` as it was required
- Created a simple react component
- Created a simple mdx page including that component

**Comment by gabriele-ct** [comment]
Findings:

`gatsby-plugin-mdx@3.20.0` is using in `gatsby-node.js` an unstable api `unstable_shouldOnCreateNode` that exists only in gatsby 4, Gatsby 5 uses the stable version `shouldOnCreateNode`. This causes the following error during local dev and build

![Image](https://user-images.githubusercontent.com/106664971/221179340-8fe884fc-3bb7-4a50-a3ba-ac37b54e7d29.png)

Apart from the error, both local development and build seem to work fine but I suspect this has to do with the super simple nature of the `mdx` file created.

The unstable API is used until version `4.0.0-next.0` (https://github.com/gatsbyjs/gatsby/blob/gatsby-plugin-mdx%404.0.0-next.0/packages/gatsby-plugin-mdx/gatsby-node.js) so it looks like there's no mdx 1 compatible versions of the plugin supporting Gatsby 5

**Comment by gabriele-ct** [comment]
On the less negative side, it seems that, apart from the method naming, there are no other issues (at least using my simple example).
One possible solution would be to create a fork of the last version 3 of `gatsby-plugin-mdx` and just rename `unstable_shouldOnCreateNode` to `shouldOnCreateNode` as recommended in the error description. For the time being could be a viable solution keeping in mind that gatsby-plugin-mdx v3 is not going to get any further updates form gatsby team and hopefully we'll be able to switch to mdx v2 in the near future.

**Comment by nkuehn** [comment]
@gabriele-ct  thank you, that's an overall very positive outcome.  

An alternative way to get a compatible version of the MDX plugin is to use  `yarn patch`  ( https://yarnpkg.com/cli/patch &  https://yarnpkg.com/cli/patch-commit or one of the various tutorials that are a bit more elaborate).  Yarn allows to store information about how to patch which package it installs.   It would have to be done in every repository that uses our package though, so it's a good temporary approach but for a long term maintenance setup we could copy / paste the old plugin into our repo  (I would not fork the complete gatsby repo, having to keep it up to date and build automation that publishes only that one package etc)

**Comment by FFawzy** [comment]
closed as done
