### ISSUE TITLE
Allow enums to be grouped semantically for rendering in markdown

### ISSUE THREAD

**Issue by melindafekete** [commercetools/commercetools-docs-kit#1539]
I would like support in the kit for grouping enums that are semantically linked. Ideally, I would like to provide a description for each group. Currently, this is not possible, and a long list of enums is difficult to navigate. Our problem is currently specific to Associate Roles, but right now the only workaround would be to handwrite the content and maintain two sets of enums and descriptions.

What it looks like now:

![Screenshot 2023-02-22 at 12 32 57](https://user-images.githubusercontent.com/14042876/221228102-c30aa641-af5a-4498-94b4-180882d88b9d.png)

What I would like to be able to see on the page:

![Screenshot 2023-02-22 at 12 32 16](https://user-images.githubusercontent.com/14042876/221228027-33ea971f-9dd2-4bbc-aa34-cdb7cd2408e3.png)

Discussed the details with Jens and Timon, and the possibility of extending `enumDescriptions` or introducing a new annotation.

**Comment by FFawzy** [comment]
this needs to go through design.

We try to avoid generating headings because it will not appear in the side nav
a better proposal would be without using a heading 

It is technically possible.

**Comment by melindafekete** [comment]
Update: please see our proposal [here](https://github.com/commercetools/commercetools-docs/pull/3047)

**Comment by nkuehn** [comment]
Thank you @melindafekete  & @stmeissner  - I left a quick review with two questions. https://github.com/commercetools/commercetools-docs/pull/3047#pullrequestreview-1362894092
