### ISSUE TITLE
Moving an image unchanged  causes cached builds to fail

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1542]
Moving an image file inside the images folder of the content to a different location (can only be a rename) without changing its contents causes cached builds to fail.  
Likely has to do with the fact that images are referred to by content hash in the gatsby cache only?

**Comment by FFawzy** [comment]
we can document that if you move images into different location you will need to run an uncached build.

**Comment by nkuehn** [comment]
This may have been resolved through gatsby 5.3  (  see https://github.com/gatsbyjs/gatsby/pull/37087  //  https://www.gatsbyjs.com/docs/reference/release-notes/v5.3/ ). 

Please test in the docs repo and confirm.
