### ISSUE TITLE
Issue with link matching the sitePrefix

### ISSUE THREAD

**Issue by gabriele-ct** [commercetools/commercetools-docs-kit#1593]
This has been reported by editors and originated by this failed build:
https://github.com/commercetools/commercetools-docs/actions/runs/4531921540/jobs/7982793380?pr=2948

It looks like when a automatic link to a type is generated, if the page where it links to has a name that starts with the `sitePrefix` defined in gastby-config, then the link gets truncated by removing the `sitePrefix` part.

In the example above, the sitePrefix is `/connect` and the pages are called `connectors.mdx` and `connectors-staged.mdx`. In the link they become `/ors` and `/ors-staged`.

This is due to this code: https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-theme-docs/src/components/link.js#L97-L102

**Comment by industrian** [comment]
Hi @FFawzy and @gabriele-ct , has there been any updates regarding this issue?

**Comment by gabriele-ct** [comment]
hi @industrian , the issue is in our backlog but it's not prioritised. 
Since I haven't heard anything from your side I assumed you found a workaround for the connect website. If that's not the case and the issue is blocking you in any way, please let me know. Depending on the urgency we can work on it next sprint, or even in the current sprint

**Comment by industrian** [comment]
Hi @gabriele-ct , thanks for the update.

Our workaround was to remove the "o" from the filenames (the pages are now cnnectors.mdx and cnnectors-draft.mdx), which is functional but looks a bit iffy and I'm not sure of its potential impact on SEO when Connect docs become publicly available. The longer we leave it like this the longer we will potentially need to support it with redirects as well.

What would be the timeline if you were to work on it on the next or current sprint?

**Comment by industrian** [comment]
Hi @gabriele-ct , thanks for the explanation.

If it can be achieved this sprint then please do so, otherwise please add it to the following sprint. Thank you.
