### ISSUE TITLE
Fix the spelling of open-source in the docs

### ISSUE THREAD

**Issue by melindafekete** [commercetools/commercetools-docs-kit#1597]
When used as an adjective preceding a noun, open-source should be hyphenated.

Due to an incorrect writing style check, there are a lot of incorrect instances in the docs. Related PR to fix the style check: https://github.com/commercetools/commercetools-docs-kit/pull/1596

Let's hyphenate all instances where the word is used as an adjective proceeding a noun.

**Comment by melindafekete** [comment]
Sorry, meant to be an issue in commercetools-docs.

**Comment by naveenchkrvrthy** [comment]
[Issue](https://github.com/commercetools/commercetools-docs/issues/3087) now created in commercetools-docs.
