### ISSUE TITLE
Info boxes are not displayed correctly in the release note preview

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#1598]
Info boxes that are used in release notes are only displayed correctly on the release note detail page, not the preview in the release note list page. The content inside of the info boxes is rendered, but without the info box.

My first guess is that it has something to do with the translation of markdown to react that we do for the release notes on the preview page.
Place of implementation:
https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-theme-docs/src/templates/release-notes-list.js#L42

**Comment by gabriele-ct** [comment]
TODO: add comment explaining the reason this is happening as discussed in sprint planning

**Comment by timonrey** [comment]
As already discussed in the weekly, we do not support mdx components from the kit before the  tag to ensure that the release notes can be displayed in the release note list as well as in the RSS feed correctly.
