### ISSUE TITLE
SWR cache revalidation

### ISSUE THREAD

**Issue by gabriele-ct** [commercetools/commercetools-docs-kit#1642]
if taken literal none of this happens in the case I tested.
- `revalidateOnFocus` would have required me to switch between tabs or windows.  I did not actually do that when I tested.  I’ll try again and be mindful what exactly I do because I think focusing (clicking) something in the dev console counts as a tab / window switch
 - `refreshInterval` is off default and would have behaved differently
- `revalidateOnReconnect` can be ruled out here, network was stable and the timing of the calls was clearly associated to when I clicked the nav entries
 - `revalidateIfStale`  “The revalidateIfStale controls if SWR should revalidate when it mounts and there is stale data.” .  The question here is what is “when it mounts”.   Maybe a navigation between pages makes SWR unmount and remount?
 - in the options documentation (link) there is also revalidateOnMount - it sounds similar to me but rather on component level. If the specific component using the hook with that option is remounted the data would be considered stale.
 
A first thing I think we should do (and intend to do anyways to provide the localstorage) is to inject  the SWRconfig  at a high level in the app tree so that it is not remounted on page changes.  ( https://swr.vercel.app/docs/advanced/cache.en-US#create-cache-provider   )  That would give us explicit clarity to the scope and lifetime of a given SWR cache, even without providing a custom one like localstorage.    Ideally, we can stick to the defaults if it works.
“revalidateIfStale” may be a bit too much - e.g. it would revalidate on every microsite switch but better safe than sorry for now I would say.

**Comment by gabriele-ct** [comment]
@nkuehn I've been digging a bit into this task and I've learning that by default gatsby unmounts and re-mounts the whole layout component at each [route change ](https://www.gatsbyjs.com/docs/how-to/routing/layout-components/#how-to-prevent-layout-components-from-unmounting)
That's why we get `revalidateIfStale` triggered each time we navigate the minisite.
There are some approaches to avoid this behaviour. Gatsby mentions [this plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-layout/) that apparently should prevent the un-mount/re-mount 

I'd like to know what are your thoughts about the possible solutions and if I should invest time in trying out the above mentioned plugin

**Comment by nkuehn** [comment]
@gabriele-ct  I would not mess with gatsby's runtime model, that just causes technical dept.  Layouts are not the right place for such a use case anyways because it has nothing to do with the appearance of a certain page vs. other pages.  

I suggest to inject the `<SWRConfig ..>` through  gatsby's `wrapRootElement` in gatsby-browser.js  which is the intended extension points for stuff like context providers (in a way SWR provides a state to the rest of the app that can be read through hooks)

 - https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#wrapRootElement 
 - https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-theme-learning/gatsby-browser.js  - you could put it inside `<LearningStateProvider>` an move `{element}` inside it or wrap it all around.

**Comment by gabriele-ct** [comment]
Differences between `revalidateIfStale` and `revalidateOnMount`: https://github.com/vercel/swr/discussions/1400

Essentially, `revalidateIfStale` acts only if a cache exists but it would NOT trigger a refetch if the cache is not there. Meaning that the cache must be created at some point, in our case the place that makes more sense is when the component is mounted, AKA `revalidateOnMount`

As expressed above, the problem is that the `revalidateOnMount` is performing a request EACH time the component is mounted, regardless of cache status. This is good for the first time, but then we would like to stop making requests to the API if the cache exists, in other words we would like to disable `revalidateOnMount` after the first successful request.
This is a common issue: 
https://github.com/vercel/swr/issues/943 (and other linked issues).

As far as I can tell, there are only workarounds for out use case:
- [the first](https://github.com/vercel/swr/issues/943#issuecomment-1514571807) is clever and essentially is disabling subsequent revalidation calls to the same API endpoint by setting the `dedupingInterval` property very high. In this case the only way to refetch the data is manually `mutate` the swr cache key
- [the second](https://github.com/vercel/swr/issues/455#issuecomment-643504686) is just a pattern that we should check if meets our needs, TBH I don't fully understand if this is going to help us in any way.

On a side note I'm trying to disable temporarily `revalidateOnFocus` since when refreshing the browser page using the reload button in chrome, the page gets the focus just before reloading triggering a api call (that gets eventually canceled) but generates "noise" in the console

**Comment by nkuehn** [comment]
Thank you for the research @gabriele-ct  - at least good to see we're not alone with the requirement to reduce load on the backend.  I doubt I find the combination of time and concentration today to properly understand and try out.  

But maybe as a guidance to pick the right approach: We only look for a "pareto optimal"-like solution, not a perfect one.  If we can avoid 80% of the unncessary calls it's perfectly fine if there is the one or the other revalidation that is just there to stay on the safe side.  

Just from scanning the three threads you linked, setting a higher deduplication interval but leaving as little else as possible untouched sounds like a possible solution for that topic. We need to explicitly mutate the course status anyways on events that we know implicitly changes them (e.g. submitting a quiz)

It can be set per data hook separately and does not even have to be extremely long, just reasonably to not suffer from people clicking around the site in fast sequence to find something they remember to have seen.
