### ISSUE TITLE
[UI/UX] Adding Checkout & Connect to Docs

### ISSUE THREAD

**Issue by zbalek** [commercetools/commercetools-docs-kit#1657]
PROBLEM STATEMENT
Background/content: We're adding two new products to our portfolio and need to reflect this in our docs.
User group | This causes problem for: Users looking for docs related to these products
How or why it affects the user | Because: They may struggle to find it if we don't add it to the menu and landing page.
Impact of problem on the organization | This is important because: We want our users to be able to use our docs seamlessly.

USER STORY
AS a
I WANT
SO THAT

ADDITIONAL INFORMATION

THINGS TO CONSIDER

**Comment by FFawzy** [comment]
maybe add
[UI/UX] as prefix to your tickets so we know that this ticket is for you .. or assign it to yourself because for example we have a similar one for tech in the same repo

**Comment by zbalek** [comment]
Megamenu: Following the discussion with Fady and Timon, [we're adding a two columns to the current megamenu.](https://www.figma.com/file/GqhHFUcEaMxBXnMM9TXdaZ/%F0%9F%9F%A2-Feedback-Board?type=design&node-id=640%3A4449&t=PPci367aVAumKpvQ-1) This approach still works visually but shouldn't require too much dev work.

Landing page is still in progress.

**Comment by zbalek** [comment]
Landing page and menu in Figma: https://www.figma.com/file/GqhHFUcEaMxBXnMM9TXdaZ/%F0%9F%9F%A2-Feedback-Board?type=design&node-id=816%3A4550&t=oODoebz1v7nlGw86-1

**Comment by gabriele-ct** [comment]
Handover happened to docs team. We can consider this closed
