### ISSUE TITLE
Move SSO plugin and learning plugin into the core theme

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#1660]
We want to get the user data through the learning context and not through auth0. But the learning context is provided by the learning plugin and the sso-ui-kit also has components that need the user information. The best solution would probably be to merge the learning plugin and the sso plugin into the core theme, so that we can rely on having the user information provided by the context to every component that needs it.

That would mean moving all components into the core theme, so a lot of refactoring. But it would be an investment into the feature, because then we have more possibilities for features that can be used by all microsites.

Once this is done, we can refactor the remaining components in the SSO plugin so that they get the user information over the context.

related to #1481

**Comment by FFawzy** [comment]
definition of done:
- gatsby-theme-learning is not there anymore
- gatsby-sso-kit is not there anymore
- everything still works
- the docs and docs-kit are updated
