### ISSUE TITLE
CI: Inconsistent external link checker

### ISSUE THREAD

**Issue by Anshuman71** [commercetools/commercetools-docs-kit#1665]
There are two issues:

1. The external link checker passed for [3124](https://github.com/commercetools/commercetools-docs/actions/runs/4922465124/jobs/8793545936?pr=3124#logs). But failed for [2972](https://github.com/commercetools/commercetools-docs/actions/runs/4915447132/jobs/8778096841?pr=2972). It's odd because, 2197 failed even though it had four broken links (correct behavior), but 3124 succeeded even though most links return 400, including those in 2197
2. The fullstory links fail most of the time but pass on retries.

**Comment by gabriele-ct** [comment]
This is the expected behaviour (not failing on external link check). There might still be some sporadic errors if external sites are down and any time
