### ISSUE TITLE
Feature: Edit user name and company (open profile modal on avatar click?)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1692]
As a User, I'd like to review or modify my Account information (e.g. the company association or name) proactively or when asked to do so so that commercetools knows the company association better.  

One common option could be to open the modal when clicking the avatar. 

As commercetools I want to be able to encourage or ask users to keep their information up to date and review the commercetools maintained company / account ID association.  But for that they need to be able to actively set the data.

**Comment by FFawzy** [comment]
@zbalek .. we had this on Figma somewhere as a post mvp enhancement ;) .. looks like now is the time 😆 

partially related to commercetools/learning-tech#429

**Comment by gabriele-ct** [comment]
I found out it is relatively simple to make the modal dismissable, so I've changed a little the requirements by making the modal closable and I also update the title since it was reading "Tell us a bit about yourself" (it still reads like this when opened upon new user creation)

**Comment by FFawzy** [comment]
> I believe we agreed to not allow users to proceed without providing us with all of the information. (which is it would not be possible to dismiss the modal)
> 
> @FFawzy has this approach changed in the meantime?

@zbalek it is still the case.

this feature is for editing the data after submitting it the first time.

so the now the avatar is clickable, you see the data that you have submitted before and we allow the user to edit it. and in this case the Modal is closable

**Comment by zbalek** [comment]
Ah I see - thanks for clarifying @FFawzy!
