### ISSUE TITLE
parallel initial requests that causes multiple token creation

### ISSUE THREAD

**Issue by gabriele-ct** [commercetools/commercetools-docs-kit#1697]
when you login to self learning and once a valid session is detected we send multiple requests to check every `course/course-id` and to get the enrolled courses via `/courses` endpoints .. resulting in 5-6 requests being fired in parallel and therefore the learn api will initialise with a new token for everyone of them because we don't have a session cookie yet

Goal: mitigating this behavior and only creating & using one token 

check auth0 sdk if we can tap into a "pre-logged in" hook and trigger a session creation.

explore also the possibility of wrap the auth0 hook into a custom one that handles the session creation

**Comment by FFawzy** [comment]
some findings 

- you cannot create two tokens for the same user with the same service account.
- if you request a new token for the same user with the same service account, it will replace the old one. which will make it obsolete if it is used by any cookies

**Comment by gabriele-ct** [comment]
We agreed to implement the following idea:
```
explore also the possibility of wrap the auth0 hook into a custom one that handles the session creation
```

**Comment by gabriele-ct** [comment]
Depends on learning-tech#448
