### ISSUE TITLE
[Investigation] Verify if it's possible removing bundling hack introduced when upgrading to gatsby 5

### ISSUE THREAD

**Issue by gabriele-ct** [commercetools/commercetools-docs-kit#1730]
Looking at gatsby release notes of the last few months and found that 5.10 included this change:   https://github.com/gatsbyjs/gatsby/pull/37961
it sounds a lot like this is addressing the problem with the massive per-page bundles that I “hacked” by including the templates into gatsby-ssr.js.
Could be worth revisiting that hack as a tech maintenance issue when we have a sprint that has a little space.  It would be good to get rid of ugly hacks over time, at some time they fire back.

**Comment by nkuehn** [comment]
For convenience this here are the lines of code we could remove to see if the behavior changed: https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-theme-docs/gatsby-ssr.js#L22-L26  

The memory debug mode should also still be there.
