### ISSUE TITLE
Add Good Store integrations to the Integrations section

### ISSUE THREAD

**Issue by sgoel518** [commercetools/commercetools-docs-kit#1741]
We would like add links to The Good Store integrations pages to this page: https://docs.commercetools.com/frontend-development/integrations-overview.

Links to be added to the Overview page: 
1) https://docs.commercetools.com/frontend-development/adyen-good-store
2) https://docs.commercetools.com/frontend-development/algolia
3) https://docs.commercetools.com/frontend-development/google-tag-manager
4) https://docs.commercetools.com/frontend-development/sendgrid

**Comment by FFawzy** [comment]
Hey @sgoel518 , please use [commercetools/commercetools-docs](https://github.com/commercetools/commercetools-docs) repo for content change requests.

Thanks
