### ISSUE TITLE
Feature request: embedding stackblitz to docs

### ISSUE THREAD

**Issue by FFawzy** [commercetools/commercetools-docs-kit#1743]
The devtooling team asked us (docs-tech) to look into embedding a [sandbox environment](https://stackblitz.com/edit/stackblitz-starters-qq8rke) built using [stackblitz](https://stackblitz.com/) into the typescript sdk docs.

 Here are the [Productboard](https://commercetools.productboard.com/roadmap/2172202-devtooling-roadmap/features/20703969/detail) and [Jira](https://commercetools.atlassian.net/browse/DEVX-187) tickets for Sandbox.

**Comment by FFawzy** [comment]
PM is @anjaliVashisth 

and platform security team is already looking into it 
[Ticket](https://commercetools.atlassian.net/browse/PLASE-1116)

**Comment by nkuehn** [comment]
Interesting.  Please don't forget to think about the UX/UI concept early enough.   

I had investigated the webcontainer based Stackblitz runtime, too already (see my comment on the internal security ticket).  It's interesting becasue the sandbox runs inside the customer browser.

**Comment by FFawzy** [comment]
Hey @zbalek I added this to your backlog too to start exploring it at some point.
we can talk together at any time if you need more details on this.
