### ISSUE TITLE
[Design adjustments] Replace Ribbon icon with Clipboard icon

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#1746]
Replace the ribbon icon with the clickboard icon from the ui-kit

<img width="600" alt="Bildschirmfoto 2023-07-10 um 10 11 49" src="https://github.com/commercetools/commercetools-docs-kit/assets/31767369/2cbead59-db26-4caf-90df-f57dff992873">

**Comment by FFawzy** [comment]
@zbalek .. please specify the exact color of the icon
Thank you

**Comment by zbalek** [comment]
@timonrey Based on our discussion during the sprint planning I tried to find a lighter color for the icon. But the lighter the color, the lower the contrast = i.e. an accessibility issue.

The lightest color that is suitable from the color contrast perspective on a white background is: #949494
<img width="738" alt="image" src="https://github.com/commercetools/commercetools-docs-kit/assets/125564062/fd8e9b8f-7fdc-4bcc-a3c2-91b197bc9e49">
