### ISSUE TITLE
Add component for Lord-Icons with animations

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1766]
Decision was taken to move on with using the Lord-Icons including their animation features, starting with the new top menu but also moving on to other places.  

Lordicons are based in Adobe Illustrator Animations but provided in various formats. Static image files, SVG, animated image files, video based animation files and, most relevant, "lottie" JSON which is a description of the animation that can be played using a player library.    

The SVGs and image files behave like standard web technology, the "lottie" player based animation have the advantage that the resolution is better and the animation can be configured in speed, trigger, color etc client side.  But the lottie animation player is client-side only.  It renders nothing into the SSR view.   So for full Gatsby support we could (should?) provide both the SVG file as well as the lottie-JSON data to a wrapper component.  The wrapper itself would render the SVG and load a client-side component that renders the animation based icon instead.  The technical pattern is known, we've done this in various places already. 

- https://lordicon.com/docs/web  (developer docs for web)
- https://lordicon.com/collections  (our collection that is to be included by default, you need to be logged in. Ask zoe to give you access)
- https://github.com/tomwilusz/lord-icon-element  (their special custom element which uses "lottie-web".  The "examples" folder has a lot of code for different use cases)
- https://airbnb.io/lottie/#/web  (docs of the lottie-web library if we decide to skip the lordicon-specific wrapper)
- https://lottiefiles.com/  (the marketplace where people share and sell animations)

Implementation notes:
- the "lord-icon" custom element has a built-in capability of a loading placeholder, e.g. the SVG version.  Not sure if that helps in our sceanario because the custom element itself is client-side only which defeats the intent of having a placeholder that is SSR built already. 
- I personally would prefer to have the files in the build, i.e. not loading the JSON and SVG through URLs from the lordicon CDN but through including them into our build so that we don't load data from another 3rd party source.   (or, include the ones that are fixed in the kit like the menu but fall back to CDN loading if an icon name is passed that is not in the bundle)
-  we could decide to load the lottie library itself from the npm CDN like we do with mermaid and videojs, but it's a tradeoff here it's ca. 165 kb in the light form and 200-something kb in the full form.  On the other hand, if we directly include it we can make use of loading only the minimal code we need like they do in the "lottie-light" example of the custom element
 - if the files are committed here we must add a respective notice in the README that they are not under the license of this repo.  Ideally also add a README into the folder with the icon files, too. 
 - I think it would be good to have this component in the docs-ui-kit package.

**Comment by FFawzy** [comment]
some restrictions:

- sticking to the needed icons ONLY. (collection link is in the ticket description)
