### ISSUE TITLE
[megamenu] create a functional non-styled top menu

### ISSUE THREAD

**Issue by FFawzy** [commercetools/commercetools-docs-kit#1772]
Requirements: 
- expansion functionality to be working
- the menu should reflect the structure of the definition file (depends on #1771 )
-

**Comment by gabriele-ct** [comment]
Removing this from spring 27 as it's been replaced by expandible chapters ticket

**Comment by gabriele-ct** [comment]
This part of the top menu implementation can be considered done. I'm moving this to in review so reviewers can start having a look to the code. The PR will not be merged until the styling has been completed (other ticket)

**Comment by FFawzy** [comment]
the ticket can be considered done and now Gabriele is working on the styling on the same branch
