### ISSUE TITLE
CodeBlock markdown component not rendered correctly

### ISSUE THREAD

**Issue by gabriele-ct** [commercetools/commercetools-docs-kit#1797]
when using `markdownFragmentToReact` function overriding `pre` rendering with `CodeBlock` component. The rendering fails due to the fact that the content is expected to be passed as prop but the wrapper component doesn't seem to forward all the props down to the actual `CodeBlock` implementation.

The objective is to be able to use `markdownFragmentToReact` function to render multiline code blocks properly

**Comment by nkuehn** [comment]
Solution is to use the `CodeBlockMarkdownWrapper`, not the pure `CodeBlock`

what's blocking it is that the UI Kit is only published in compiled minified form and that the markdown wrapper is not exported. 

Please patch release UI kit and export  https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/ui-kit/src/components/multi-code-block.tsx#L223C14-L223C38  CodeBlockMarkdownWrapper  and also the Multi** variant of it.  

The wrapper can then be passed as the renderer for "pre" in markdown fragment renderer

**Comment by nkuehn** [comment]
P.S:  as a default, it's intended that the markdown fragment renderer is not rendering full blocks, for example if embedded int the description field of an API field.    It shuold be a situational override to allow rendering "bigger" components

**Comment by FFawzy** [comment]
the wrappers can be added as options here https://github.com/commercetools/commercetools-docs/blob/82ddc291924bd4e954a0acbfc7a2c3ca37a04ad6/websites/docs/src/components/chat-messages.jsx#L45

**Comment by timonrey** [comment]
Solved by this PR:
https://github.com/commercetools/commercetools-docs/pull/3852
