### ISSUE TITLE
Code block title element gets distorted on smaller screens

### ISSUE THREAD

**Issue by Anshuman71** [commercetools/commercetools-docs-kit#1809]
On smaller devices, when the title of the code block is long, the title and language type occupy more space than needed and create a bad user experience. See the image below.

![image](https://github.com/commercetools/commercetools-docs-kit/assets/28081510/c0ad7fba-5c6e-4149-8920-2d50400a491a)

**Comment by gabriele-ct** [comment]
Possible solution: do not wrap the language part, make the title wrap
