### ISSUE TITLE
Mermaid automatic numbering

### ISSUE THREAD

**Issue by basebander** [commercetools/commercetools-docs-kit#1825]
## Problem

For certain complex diagrams, we aren't able to match the auto-assigned numbers on mermaid diagrams to the written documentation steps.

For example, on our documentation page, we show:

1. step
2. step
    a. possibility
           i.   status 1
           ii.  status 2
           iii. status 3
           iii. status 4
    b. possibility
         
For the above example, mermaid walks through each line and applies a number, 1-8.

## Config

Mermaid automatically add numbers to steps for `sequenceDiagram` due to the config setting `showSequenceNumbers: true`.

## Solution

Disable autonumbering site-wide `showSequenceNumbers: false` and instead allow the authors of each diagram to manually add the `autonumber` variable to the diagram code when numbering is required.

[Mermaid sequenceDiagram docs](https://mermaid.js.org/syntax/sequenceDiagram.html)

```
sequenceDiagram
    autonumber
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
```

**Comment by FFawzy** [comment]
we will disable the defaults in the docs-kit and therefore all the mermaid diagrams that needs numbering will need to explicitly use the flag
