### ISSUE TITLE
Megamenu direct links should be anchors

### ISSUE THREAD

**Issue by gabriele-ct** [commercetools/commercetools-docs-kit#1850]
Current implementation of mega menu redesign is rendering direct link as simple divs with an onClick handler which handles the redirections.

This works fine but it would be better to actually render `<Link>` components so that the links can be opened in a separate tab

**Comment by nkuehn** [comment]
Definitely!  Not only for being able to open in a new tab but also to track external links in analytics and all the other things the Link handling does.  I hope it does not require a huge refactor of the link logic if that has too much styling hardwired.
