### ISSUE TITLE
Ai chat modal keep capturing certain key events even when defocused

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1871]
The modal  used in the Chat UI, the User account dialog, the feedback dialog etc  is not capturing input events,  it's passing them through to the page behind the overlay if they are not explicitly handled e.g. by a form input.  

In the case of scrolling this only confusing and weird because it changes depending on if e.g. the chat UI is a scrolling container aleready or not.  

In the forms that have inputs it's an actual bug.  For example, when using the Feedback dialog in the Chat UI,  pressing the enter key will submit an new empty message in the chat ui in the background of the modal.   If the user has e.g. started writing a response that is not the user intent if they are in the feedback dialog.

**Comment by gabriele-ct** [comment]
I can replicate the following issue

> In the forms that have inputs it's an actual bug. For example, when using the Feedback dialog in the Chat UI, pressing the enter key will submit an new empty message in the chat ui in the background of the modal. If the user has e.g. started writing a response that is not the user intent if they are in the feedback dialog.

This is caused by the custom input event listener defined in the chat UI (to make possible submitting message when typing enter). This listener should be disabled when opening any modal and re-enabled when closed. Or, even better enabled only when the chat input has focus.

Regarding the rest of the issues, if they still exist, I'm not able to replicate. A step-by step guide or a video would help

**Comment by nkuehn** [comment]
The issue with the form is most important, if it by chance changes the scroll behavior too that is good and if not let's track it separately as low priority. 

Here's a video with me using the touch scroll to move the page that is behind the two layers of modals.  It's not a practical issue on the demo page which is near empty, but if the assistant is opened over a longer page users would accidentally scroll the page behind the modal overlay to a different position. 

https://github.com/commercetools/commercetools-docs-kit/assets/4006139/740af1c3-6a32-44fa-ae40-2766258d4a76
