### ISSUE TITLE
Code block title doesn’t appear when using MultiCodeBlock

### ISSUE THREAD

**Issue by Anshuman71** [commercetools/commercetools-docs-kit#1877]
When using the `MultiCodeBlock` syntax, the code block titles don't appear. For example, for the following code:

![21-11-2023-at-14-08-01@2x](https://github.com/commercetools/commercetools-docs-kit/assets/28081510/1658b789-7262-4de1-beff-252068591f32)

the output is:

![21-11-2023-at-14-08-25@2x](https://github.com/commercetools/commercetools-docs-kit/assets/28081510/0bb4708f-eec8-4962-b5a7-df9ec5f0f14a)

**Comment by FFawzy** [comment]
the MultiCodeBlock is intentionally built for the same example but in different programming languages that share the same title (there is a title prop in the MultiCodeBlock component)

if you need to have two different examples with two different titles they need to be two different blocks

**Comment by FFawzy** [comment]
We will improve the docs for this component [here](https://docs-kit.commercetools.vercel.app/documentation/writing/code#multi-language-code-blocks-in-markdown) to further explain this
