### ISSUE TITLE
🔍  Add the Metadata of a microsite into the html

### ISSUE THREAD

**Issue by FFawzy** [commercetools/commercetools-docs-kit#1905]
we need to add the following datapoints from the microsite config to the html content
products
contentType

the way we write it, to be investigated which is the better/easier way for the crawler to catch.

**Comment by gabriele-ct** [comment]
@FFawzy would this be an acceptable format?


![Image](https://github.com/commercetools/commercetools-docs-kit/assets/106664971/3ec0ae96-31a5-486c-85f9-7ff958d98fb8)

**Comment by FFawzy** [comment]
looks good to me .. but ultimately check whether it is easily catchable using that lib .. was it called cherioo ? 
i think that would be your deciding factor
