### ISSUE TITLE
Creating the onboarding plan for an ET Dev

### ISSUE THREAD

**Issue by gabriele-ct** [commercetools/commercetools-docs-kit#1979]
https://commercetools.atlassian.net/wiki/spaces/ET/pages/707136051/Senior+Frontend+Developer+Onboarding+Plan

**Comment by gabriele-ct** [comment]
@FFawzy would you mind checking when you have time and add some notes about what you think is still missing?
Thank you

**Comment by FFawzy** [comment]
template ready to use [here](https://commercetools.atlassian.net/wiki/spaces/ET/pages/707136051/Senior+Frontend+Developer+Onboarding+Plan)
