### ISSUE TITLE
Creation of three new microsites

### ISSUE THREAD

**Issue by lukpan** [commercetools/commercetools-docs-kit#2065]
The administrator learning path is going to be broken up into three new learning paths. The existing administrator content will be distributed across the three new learning paths, and new additional content added to it as well.

The names of the new learning paths are:
- Model your product catalog
- Price and discount your products
- Model your business structure

Can we therefore name the microsites:
- `learning-model-your-product-catalog`
- `learning-price-and-discount-your-products`
- `learning-model-your-business-structure`

Could we have three new microsites created for these learning paths please. They can remain hidden until we go live, but it would be good to have them living on the main branch so that we can push content to them more incrementally.

It would be great if this could happen within the next week or so, if possible...
Thank you team ET!

**Comment by timonrey** [comment]
Link to the new microsite creation process documentation:
https://commercetools.atlassian.net/wiki/spaces/ET/pages/1134133271/Creating+a+new+microsite+in+the+docs

Link to the PR with the first two microsites:
https://github.com/commercetools/commercetools-docs/pull/5588
