### ISSUE TITLE
Investigate how to dedupe emotion styles

### ISSUE THREAD

**Issue by emmenko** [commercetools/commercetools-docs-kit#252]
I noticed that in the production build some styles are "duplicated" all over the page, for example for links.

<img width="1623" alt="Screenshot 2020-01-29 at 15 19 22" src="https://user-images.githubusercontent.com/1110551/73364364-bd898000-42aa-11ea-96ee-6c7058a49315.png">

This seems to be a "known behavior" in Emotion: https://github.com/emotion-js/emotion/issues/1061

We should investigate how to reduce the duplication. They mention having a "common" emotion ancestor, but I'm not sure exactly what that means.

**Comment by andgra** [comment]
The easiest way is to wrap your whole app in custom CacheProvider (https://emotion.sh/docs/cache-provider). For me, it fixed the problem.
But the downside is you must set up ssr manually (https://emotion.sh/docs/ssr)
