### ISSUE TITLE
Investigate analyzing bundle size

### ISSUE THREAD

**Issue by emmenko** [commercetools/commercetools-docs-kit#26]
https://www.gatsbyjs.org/packages/gatsby-plugin-webpack-bundle-analyser-v2/?=bundle
https://github.com/siddharthkp/bundlesize

**Comment by nkuehn** [comment]
the analyzer can be called through an env var and we've groomed through most of the bigger bundles in the last month, removing what we can.  
The biggest chunk remanining are the ui kit icons which do not seem to be tree-shaken (any more) despite being imported per icon through destructuring.
