### ISSUE TITLE
Types not rendered as links in Import API docs site

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#263]
### Description

Types that are defined on a page somewhere on the website should be linked. This affect various property types and response representations on the Import API site.

Expectation
Types links are queried from graphql nodes generated gatsby-transformer-mdx-introspection tool, so the links are expected to be available in graphql.

### Current behaviour

In the current case the links are not present in graphql. So types are rendered as a string.

### Proposed solution

The next step is to look into the gatsby-transformer-mdx-introspection to implement the fix.

**Comment by nkuehn** [comment]
@davifantasia  I have the impression this issue belongs into the kit repository.  

Please keep in mind that we have this big 3rd party PR open on the introspection code:  https://github.com/commercetools/commercetools-docs-kit/pull/183

I hope we get it merged (or published separately) to be able to work on it when doing this here.

**Comment by davifantasia** [comment]
With this merged [PR](https://github.com/commercetools/commercetools-docs-kit/pull/183), there is a new challenge - all types are no longer rendered as links, previously, only some types were not rendered as links in production.

### Findings so far
- types are rendered as links in development
- types are not rendered as links in production
- allComponentInMdx nodes is empty in production
- allComponentInMdx are generated but after all pages have been generated
- current proposed solution is to look into async implementation of the [MDX introspection](https://github.com/commercetools/commercetools-docs-kit/tree/master/packages/gatsby-transformer-mdx-introspection) tool. See Gatsby's documentation about [async plugins](https://www.gatsbyjs.org/docs/node-apis/#async-plugins)

### Other notes
Why it works in development: A pages static query is executed client side, that is when a page is rendered. So allComponentInMdx nodes have been generated at this point.

Why it does not work in production: All Gatsby APIs are executed when site is generated, including createPage API, so for an async api that does not return a promise, Gatsby does not know there is still an ongoing async operation within that API.
