### ISSUE TITLE
provide a package that dynamically downloads and provides rmf-codegen CLI for RAML

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#292]
### Need:

 * the RAML plugin is relying on a very conventional RAML file and annotations structure that allows us to not have to work with a full JS RAML parser to generate the site (speed, availability of suitable RAML parsers)
 *  to generate the format from arbitrary valid RAML you have to use the "rmf-codegen" java tool ( https://github.com/vrapio/rmf-codegen ).  Installing java to be available on the command line is an acceptable requirement (for now), but building and providing the CLI jar of rmf-codegen is too complex for all users.   So the fat JAR should be downloaded dynamically by an npm wrapper package that does nothing but to download it at install time and provide it as a predictable path to the local project 
 * this has been analogously implemented for the vale writing style linter: https://github.com/commercetools/commercetools-docs-kit/blob/master/packages/writing-style/package.json#L15-L21 . A notable difference is that the JAR is not directly a binary so we'll have to try how calling it from a yarn script works best  (maybe via some sort of cross platform script caller)

The rmf-codegen CLI JAR is available on Bintray https://bintray.com/vrapio/vrapio/rmf-codegen/1.0.0-20200206130325#files/io%2Fvrap%2Frmf%2Fcodegen%2Fcli-application%2F1.0.0-20200206130325  , the version needs to be updated manually.  

There's an issue asking for a URL providing the latest stable version of the RMF-Codegen: https://github.com/vrapio/rmf-codegen/issues/137

**Comment by jenschude** [comment]
The FAT jar get's published since version `1.0.0-20200220153930` to `https://dl.bintray.com/vrapio/vrapio/io/vrap/rmf/codegen/cli-application/`

**Comment by davifantasia** [comment]
Just for my use:

https://dl.bintray.com/vrapio/vrapio/io/vrap/rmf/codegen/cli-application/1.0.0-20200221085820/

**Comment by jenschude** [comment]
From Slack:

Achraf Beniasaad

12:16
by the way i just released an installable cli for vrap, you can find it at https://github.com/vrapio/rmf-codegen#install-vrap-cli (edited) 
12:17
basically to install it its enough to execute

```
export VRAP_VERSION=1.0.0-20200225111016
curl -o- -s https://raw.githubusercontent.com/vrapio/rmf-codegen/master/scripts/install.sh | bash
```

12:17
once done you can check that the command is installed by executing `rmf-codegen -v`

**Comment by davifantasia** [comment]
> From Slack:
> 
> Achraf Beniasaad
> 
> 12:16
> by the way i just released an installable cli for vrap, you can find it at https://github.com/vrapio/rmf-codegen#install-vrap-cli (edited)
> 12:17
> basically to install it its enough to execute
> 
> ```
> export VRAP_VERSION=1.0.0-20200225111016
> curl -o- -s https://raw.githubusercontent.com/vrapio/rmf-codegen/master/scripts/install.sh | bash
> ```
> 
> 12:17
> once done you can check that the command is installed by executing `rmf-codegen -v`

Is it possible to have it as an NPM module? This would be the best solution for us - we're currently working on an NPM module that preloads the jar file before running it.

**Comment by nkuehn** [comment]
@wale it#s our job to provide an NPM module that automatically downloads the latest vrapio on installation.  it does not really make sense to publish NPM modules from a Java project.
