### ISSUE TITLE
duplicate filesystem watcher plugins on images and configuration data folders

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#310]
In the docs-theme's  `gatsby-config.js` two filesystem directories are loaded into graphQL twice, one with a different name and one just duplicate. 

It looks like something that sneaked in with a merge sometime. 

````
      {
        resolve: 'gatsby-source-filesystem',
        options: {
          name: 'srcImages',
          path: path.resolve(`./src/images`),
        },
      },
      // Data files (.yaml)
      {
        resolve: 'gatsby-source-filesystem',
        options: {
          name: 'configurationData',
          path: path.resolve(`./src/data`),
        },
      },
````

**Comment by emmenko** [comment]
Right, the `src/images` is duplicated.

However, not the `src/data`. One is for the local path and one is for the website path. `path.resolve` and `path.join` are different!

**Comment by nkuehn** [comment]
right, thanks!
