### ISSUE TITLE
No Highlighting for Some Languages in CodeBlock

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#313]
Languages are:
- csharp
- curl
- yaml

Current rendering example:
![Screenshot 2020-03-19 at 13 23 23](https://user-images.githubusercontent.com/8238495/77067220-e85b9f00-69e4-11ea-869e-566a6be06d9f.png)

**Comment by emmenko** [comment]
The list of supported langauges is this: https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js

Some languages need to be mapped, like we already do here:
https://github.com/commercetools/commercetools-docs-kit/blob/718ea08ac05a8db7c973fef8a3330c5cf15aea97/packages/ui-kit/src/components/code-block.js#L197-L203

**Comment by davifantasia** [comment]
Closed by https://github.com/commercetools/commercetools-docs-kit/pull/325
