### ISSUE TITLE
Release Notes List (no filter, no RSS links yet)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#314]
* Design: https://commercetools.invisionapp.com/share/ZFWC4K04S7V#/screens
 * MDX and data format:  see PR #312 (decided)

 separate issues:
 * Read more and details page
 * links to details page
 * filtering.

**Comment by davifantasia** [comment]
After discussing with @nkuehn  today, we decided this issue will be split into 3 tasks/stages/PRs for a more efficient review process:

1. Implement underlying infrastructure which will include
- `gatsby-node.js` and `gatsby-config.js` customizations,
- disallow any mdx file with name `release-notes.mdx` within `content` directory.
- and a basic page that includes list of all release notes.

2. Implement design (see link in the first comment) for the overview of all release notes.

3. Implement "read more" functionality.

4. Implement filter in the design.

**Comment by nkuehn** [comment]
Open Issues:
 
 * Heading anchors are broken and not part of the design, need to be removed for now (is back in design). 
 * remove the TODO entries to have a state that could be used already (e.g. import API? )
