### ISSUE TITLE
Descriptions of properties of a type should formatted using design guidelines

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#321]
## Problem
Descriptions of properties of a type currently use basic html formatting, see the following examples:

HTML code element on this page - https://commercetools-docs.now.sh/import-api/import-operation#importoperation
![Screenshot 2020-03-25 at 12 55 02](https://user-images.githubusercontent.com/8238495/77533843-e63b8980-6e97-11ea-9226-0b45eb4183b1.png)

Anchor link on this page - https://commercetools-docs.now.sh/import-api/product-draft-import#pricedraftimport
![Screenshot 2020-03-25 at 12 52 07](https://user-images.githubusercontent.com/8238495/77533628-81802f00-6e97-11ea-908e-e4b04235a087.png)

## Design
https://commercetools.invisionapp.com/d/main?origin=v7#/console/17784193/390033493/preview?scrollOffset=425

EDIT:

The task to parse only the allowed markdown syntaxes and render custom components should be a separate PR.
- disallowed markdowns will be rendered as text

**Comment by nkuehn** [comment]
I think this is is the option in the `remark-reactjs` lib you need to fill with a selection of our components (from the docs-ui-kit package):

https://github.com/remarkjs/remark-react#optionsremarkreactcomponents

We only need to provide the components that are actually allowed (see confluence)

**Comment by davifantasia** [comment]
Fixed in https://github.com/commercetools/commercetools-docs-kit/pull/375
