### ISSUE TITLE
Define convention for content includes (MD(x) transclusion)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#338]
The legacy documentation implementation holds a significant number of markdown and plaintext (can be handled as markdown) fragments in an `_includes/content/**` folder structure that is then included into the pages via  `{% include content/** %}` liquid statements. 

It's a sort of "*topic based writing for the poor*" and without the conceptual pre-determination into definitions, instructions etc. 

In MDX the matching concept is MDX transclusion, which by spec works via an import statement to load the fragment as a react component ( https://mdxjs.com/getting-started#documents ) 
````mdx
...
import Contributing from '/some-folder-convention/contributing.mdx'

... other content possible ...

<Contributing />
...
````

To do:
 * decide on a file system convention where such re-usable  fragments should live  - e.g. `src/topics` or `src/content-fragments` or `src/includes`  etc.. 
    * !!!: the implementation does not force a location, it's a generic 
 * autogenerate the folder on startup if it does not exist

**Comment by nkuehn** [comment]
@adinakleine  in the migration code I've now created a separate package (=folder) outside the websites named `topics`  that contains the re-usable parts independently of whether they are used in only one site or not. 

if you're okay with that wording the matching convention inside a site would be `src/topics`

It leans a bit to topic based writing so I thought that name might be familiar to tech writers.

**Comment by adinakleine** [comment]
> @adinakleine in the migration code I've now created a separate package (=folder) outside the websites named `topics` that contains the re-usable parts independently of whether they are used in only one site or not.
> 
> if you're okay with that wording the matching convention inside a site would be `src/topics`
> 
> It leans a bit to topic based writing so I thought that name might be familiar to tech writers.

src/topics is absolutely fine for me. It's understandable and simple. 👍
