### ISSUE TITLE
Possible issue with rendering custom script elements for production builds

### ISSUE THREAD

**Issue by emmenko** [commercetools/commercetools-docs-kit#342]
I just realized that we might have an issue with the production build, regarding the rendering of the extra script elements (e.g. cookie consent).

<img width="2557" alt="Screenshot 2020-04-03 at 22 47 56" src="https://user-images.githubusercontent.com/1110551/78403794-4ac7b880-75fd-11ea-9773-8a5c34aaf361.png">

Somehow the scripts are rendered for the docs-kit production build on master, but not for the app-kit build.

I need to investigate a bit if those env variables are correctly set:

https://github.com/commercetools/commercetools-docs-kit/blob/d064f474152a508dfc93409210593f28be79d414/packages/gatsby-theme-docs/gatsby-ssr.js#L16-L18

**Comment by emmenko** [comment]
Also on the import api production build they seem to be missing.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/1110551/78404002-d04b6880-75fd-11ea-9b74-66ee38a3766c.png">

It looks like this has been an issue for quite some time now.

**Comment by nkuehn** [comment]
The cookie consent banner is not intended to run on domains that are not *.commercetools.com  - it tries to set cookies for the  *.commercetools.com  scope and that causes trouble (that's why we try to hide it on other domains). 

The top left image should actually not happen (now.sh domain), at least the banner should pop up over and over again on every page load. 

I hate that thing...

**Comment by emmenko** [comment]
I added some debug logs: https://github.com/commercetools/commercetools-docs-kit/commit/b9f55041a966010529177b2aaba286f10e1655cb

<img width="845" alt="image" src="https://user-images.githubusercontent.com/1110551/78546218-5681cd80-77fd-11ea-9e2b-8c9d75d6881d.png">

So it's kind of expected that the banner shows up on the now.sh for docs-kit. The question is why it doesn't for e.g. app-kit.
I'll use the canary release to test out the logs in appkit when it deployed. Let's see what we get there.

**Comment by emmenko** [comment]
Now it seems to work, what the hell...well whatever...

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/1110551/78551285-baa88f80-7805-11ea-9ea9-c98a85cc23bf.png">

**Comment by nkuehn** [comment]
I don't want to know how much dev time this crap wasted already in our company.  In the old docs stack I chose to simply accept that I can't really it and brute-force delete the whole thing from the DOM after load if the domain isn't  docs.commercetools.com .
