### ISSUE TITLE
Release Notes: Details Pages (designed)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#360]
* [x] Design and generate the Details pages.  
 * [x] Find a solution to use an explicit excerpt separator instead of chopping off after a given number of characters.  The remark plugin supports this on GraphQL but the MDX plugin doesn't.  Maybe we can do something in the layer that creates our custom grapql Schema. 
 * [x] change the GraphQL query of the overview page to not load more than the excerpt
 * [x] Change the overview list page to show the "Read More"  link if there is such a separator in place
 * [x] NEW: Make the title of the post in the overview a link to the details page, also for entries that do not have a read more.   Styling decided with Sven (design):  Like in the top navigation, i.e. black but on hover colored in that color.   

Design - https://commercetools.invisionapp.com/d/main?origin=v7#/console/19438556/412794930/preview?scrollOffset=299

**Comment by nkuehn** [comment]
@davifantasia  I've updated the description of this issue to address the problem that MDX does not have excerpt separators and added the UX requirement that the title in the overview is a link.

**Comment by davifantasia** [comment]
This is done now.
