### ISSUE TITLE
RSS link not working as expected

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#372]
### Current behaviour / Reproduction
1. Visit https://commercetools-docs-kit.now.sh/docs-smoke-test/releases
2. Click "RSS" link on the right side of the page
3. Result:
![Screenshot 2020-04-20 at 11 56 37](https://user-images.githubusercontent.com/8238495/79739726-db411100-82fe-11ea-860f-acc48487678d.png)

### Expected behaviour
Step 3 should lead the the xml document like in the image below:
![Screenshot 2020-04-20 at 12 05 04](https://user-images.githubusercontent.com/8238495/79739958-33781300-82ff-11ea-8d71-c5108842b978.png)

**Comment by emmenko** [comment]
Can you point out the differences, or what is supposed to be broken?

**Comment by davifantasia** [comment]
> Can you point out the differences, or what is supposed to be broken?

The links I included shows the difference. I have amended the description to include current and expected titles.

**Comment by davifantasia** [comment]
O I see the problem now, using the links shows no difference, I'll amend the description.

**Comment by emmenko** [comment]
Ah I think the RSS link should be an "external" link, not a Gatsby link.

**Comment by emmenko** [comment]
I opened a PR
