### ISSUE TITLE
Api Types: Deprecated properties being rendered

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#374]
API spec types can have a "deprecated" annotation that must lead to them not appearing in the rendered docs any more. 

There is a test type for the case `AnnotationsTestType`.  It has one property that must not be rendered but currently is.

**Comment by davifantasia** [comment]
*  [AnnotationsTestType RAML doc link](https://github.com/commercetools/commercetools-docs-kit/blob/f004c073c0bc2afa460cb131b43ea383f26e7a8f/websites/api-docs-smoke-test/src/api-specs/test/types/AnnotationsTestType.raml#L13-L19)
* [Rendered Link](https://commercetools-docs-kit.now.sh/api-docs-smoke-test/types/annotations-test-type)

**Comment by davifantasia** [comment]
@nkuehn I have a question:

* Since `AnnotationsTestType` also includes a `beta` property, should we create a different issue for that or include it here?

**Comment by nkuehn** [comment]
I suggest to handle beta differently because we have the speak about design in that case and there's another PR open concerning the beta badge.
