### ISSUE TITLE
Docs Theme Performance: How can we better track build & develop performance on non-dev devices? 

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#377]
(updated text)

When bootstrapping the empty sites for the complete structure for migration I realized that building an completely empty site with only the docs-theme  as a plugin is now taking 80+ seconds to build on my laptop, which was not always the case, I remember times around 20 seconds including actual content.  

It's the case for both building and development, but more pronounced when building. 

This issue is not about the specific problem but rather **how we can work to better track regressions of that sort** -  the developer's machines are usually 2-4x faster than users's so for them everything is fine unless explicitly trying a less powerful environment.  

Since the migrated setup will have at least six sites which will only grow it would be good to take a look at the topic before it gets even harder to track.  Doing a full build is relevant for users, too because before finishing a given task you usually have to do a full build of all sites to make sure you have no broken links.

**Comment by emmenko** [comment]
Hmm are you sure? I just tried:

- **Building production bundles**: ~38s
- **Starting dev server**: ~13s

Building production bundles is usually something you don't need to do, unless you're debugging issues.

Happy to have a chat if you want to talk about it.

**Comment by nkuehn** [comment]
We have enough users now to get feedback about slowness in the dev server.   It's also become a non-issue because cached gatsby finally became a stable product
