### ISSUE TITLE
Error on specific pages when scrolling

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#389]
The migration preview: https://commercetools-docs-jszg143tk.now.sh/api/message-types  fails hard when scrolling the body content. 

"unable to load view"

**Comment by nkuehn** [comment]
Here's a matching Sentry entry: https://sentry.io/organizations/commercetools/issues/1624534474/?project=1819068

**Comment by emmenko** [comment]
Looks like the `item.url` is undefined.

**Comment by emmenko** [comment]
The items come from `tableOfContents`.

**Comment by emmenko** [comment]
Do you know why there is a link without a URL?

**Comment by nkuehn** [comment]
I can't find a link without a URL in the markdown source of the messages list, do you have a hint which link it could be? 

In general:  It can always happen that an author messes something up in the source that is formally correct markdown but not expected by the implementation,  we'll have quite some more cases to catch and display an error in development over time  (like we do in the RAML driven API types now).

**Comment by emmenko** [comment]
I found the issue. I'll open a PR to prevent the component to throw but it's an issue with the content.
