### ISSUE TITLE
Document and autogenerate `src/topics` folder

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#391]
docs team decided to use the convention `src/topics` for content that is re-used via MDX transclusion in many places inside a website. 

Content that is re-used across websites lives in a top level "topics" package (already done in migration). 

That `src/topics` folder needs to be autogenerated on start and documented in the README.

**Comment by emmenko** [comment]
Is this required for every website?

**Comment by nkuehn** [comment]
We are autogenerating all conventional folders up to now  (code-examples, images, content, data)  independently of whether they are needed or used, so for consistency we should autogenerate this convention too.  

e.g. the images folder is just a convention too, you could use any other location.  I personally prefer to have the folder convention autogenerated than to have to regularly give authors negative nitpick feedback because they put certain things into non-conventional place.    Like others, this is a need from the docs team side and not from the contributors side.
