### ISSUE TITLE
Configurable Top Menu and Footer content (for migration)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#396]
As already discussed at the beginning of the kit implementation,  we are now nearing go live and it turns out we need to be able to configure the top nav and footer links - or at least toggle between "current" and "next" in the site options. 

Reasons:
 * I realized that it's very hard to get QA from externals if they get lost in navigating to the old site
 * Enabling link testing an generally full automated QA is running circles between excluding too much and then having issues there.  

We did discuss live download from a central location, that's an option but i would already be very happy with being able to pull the data from a file or a file in another package.

**Comment by emmenko** [comment]
Should I look into this?

**Comment by nkuehn** [comment]
@davifantasia result from a quick call with Nicola:  We'll try to use gatsby's code shadowing to simply override the files locally using gatsby component shadowing. 

It means duplicating them for the 6 sites but that's good enough for the migration phase.

**Comment by nkuehn** [comment]
@emmenko  FYI my research status: 
 - it's only possible to shadow files that are loaded via webpack (i.e. import / require in code) but if a plugin like YAML loads file directly gatsby does not intercept that  -> not working here
 - I created a wrapper theme package in the `commercetools-docs` repo which is practical anyways because it allows to centrally preconfigure themes and centrally set the version.  I configured the filesystem source again there, which works but it does not override the data but adds new menu entries etc.  That's nice but was not the goal. 

So we'll have to do something in the actual theme, the simplest form would be to pass  an option that allows to disable the theme's 'internalConfigurationData'  loading.

**Comment by emmenko** [comment]
Have you tried simply creating a `top-menu.yaml` in `src/data`?

The yaml transformer should be able to pick it up and assign it to the `TopMenu` schema.

**Comment by nkuehn** [comment]
Yes, that's what I did.  But as said in the above comment, the YAML plugin **adds** the menu entries to the existing menu entries, it does not replace them. 

That's because the YAML source plugin is hardwired to require an array as the top level stucture of the yaml files whose entries are then automatically becoming nodes in a GraphQL type of the file name.  If if finds two same named files it seems to just add the entries.  

So to really override you have to stop the theme from providing its own files.

**Comment by nkuehn** [comment]
PS: if you mean "just" putting it into the website folder?  That leads to nothing, the loader is explicitly configured to look into  `__dirname`, that was the whole point of it originally

**Comment by emmenko** [comment]
No the source plugin is configure to load `data` folders both in the theme and in the website.
Yes, it adds the new entries to the existing one. I thought this was enough, or do you want to replace some of the menu items?

One option could be to allow a `custom-top-menu.yaml` in the website `src/data`, and instruct the theme to render that, if available. We could probably do that in `gatsby-node.js` when constructing their related nodes.

**Comment by nkuehn** [comment]
OK, back to zero and do not take 500 $.  The use case:

 * the links in the current menu are all "dead" in the  new build and only work when proxied through netlify on docs.commecetools.com
 * that is bad
 * once migrated, links need to point to the actual new locations and not to a redirect rule
 * I want to prepare and test the new link locations already now in the preview build
 * that means the menu needs to be _exchanged_  for _different_ data.

**Comment by emmenko** [comment]
I have an idea, let me try something
