### ISSUE TITLE
404 layout broken

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#403]
The layout of the gatsbyJS 404 page is broken,  in some responsive breakpoints it at least says "page not found" but in the main view it's completely broken. 

Please note:
 * this refers to production builds
 * the gatsbyjs 404 does not appear when directly entering a wrong URL.  But when navigating via back / forward the gatsbyJS client side 404 appears. 
 * ideally we also configure `now.json` to a proper 404.   Let's get it first set up correct in this repo and then do it in the private content repos. 

![image](https://user-images.githubusercontent.com/4006139/80252951-a58e8600-8678-11ea-85df-bf739ce55358.png)

**Comment by emmenko** [comment]
Thanks for the reminder, I’ve been meaning to look into it but forgot.

Is there a design for the 404 page?

**Comment by nkuehn** [comment]
No, there's no design for it yet.  To start with, a content page layout does the job.  Here's a rough piece that should work for all sites to start with.  If the nav and search are both visible people should find their way around. 

```mdx
---
title: Page not found
---

<Error>

It seems you requested a page that does not exist. 

</Error>

```
