### ISSUE TITLE
Theme: Configurable key color per website

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#409]
Currently all the websites get the key color of the custom applications site because the second phase of designs was built on custom applications as the example content. 

But (@Shecki please confirm) the design concept is that there are multiple key colors and that in a "normal" platform documentation site the key color is the same green as the links (see the original design of the HTTP API site). 

To be decided:  
  a) Wrap it into a more general "style variation" setting that just allows to tell whether it's  e.g.  merchant center vs. api platform vs. open source offerings vs. custom applications  (or whatever separation we want.  
  b) explicitly allow to pass a color key (e.g. a named design token).

**Comment by Shecki** [comment]
@nkuehn yes, each Product/Solution will get there own color.
so its easier to recognize and as a guidance
These colors will also be used in the "banners for each "Intro-Page""

And yes green is our "key color". But should not have the same color as the Links

Links: #008071
Key color: #00B39E

**Comment by emmenko** [comment]
PS: I want to do some cleanup and renaming first of the current design tokens (see also #226).

@Shecki you need to tell us exactly which parts of the docs should have their own specific colors.

**Comment by Shecki** [comment]
- Intro Headline "H1"
![image](https://user-images.githubusercontent.com/28807759/80497382-a8d08d00-896a-11ea-836a-ecc66c44e7ac.png)
![image](https://user-images.githubusercontent.com/28807759/80497543-e7664780-896a-11ea-85cd-f6b3598db1c6.png)


And the "home Button" - Back to the "Intro-Pages" 
![image](https://user-images.githubusercontent.com/28807759/80497599-fc42db00-896a-11ea-8750-a001394cbf0a.png)
![image](https://user-images.githubusercontent.com/28807759/80497628-0533ac80-896b-11ea-9491-38c6ac61fead.png)

@emmenko @nkuehn

**Comment by Shecki** [comment]
And Graphics that will be provided by the designer
