### ISSUE TITLE
Image should only display the title but not the alt as a caption. 

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#41]
Pseudo-spec:

- if none is provided,  neither alt nor a caption is generated (fallback to the file name OK but not ideal)
- if only alt is provided, it's used as alt but not as caption
- if only title is provided, it's used as caption and also as alt (better to have some accessibility than nothing)
 -  if both are provided alt is the alt and title the caption. 

In any case, the html "title" attribute does not have to be set  if  <figure> &  <figcaption> are properly used.

**Comment by emmenko** [comment]
So if you only provide the `alt` text like:

```
![the image alt text goes here](../../images/full-resolution-photo.jpg)
```

The props that we get contain both `alt` and `title`, in which case `title` is the same as the `alt` value:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/1110551/68626745-54307700-04dc-11ea-9bf9-9609d92c818d.png">

If the `alt` text is left empty in markdown like:

```
![](../../images/full-resolution-photo.jpg)
```

Then the filename is used for both `alt` and `title`.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/1110551/68626815-80e48e80-04dc-11ea-87da-a17957da617b.png">

So it seems that we always get a `title` as there is some sort of fallback mechanism.
WDYT?

**Comment by nkuehn** [comment]
FYI @emmenko  I changed the title and text of this to match what we found out today.
