### ISSUE TITLE
Writing Style Improvements

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#437]
**this issue serves as a place to collect improvement ideas for the writing style linter rules. Please add ideas as comments**

Implementation will be done periodically.

**Comment by nkuehn** [comment]
**seen**:  NodeJS, Nodejs, node.js

**should be**:  Node.js  

**reference**:  https://nodejs.org/en/

**Comment by nkuehn** [comment]
seen: 
 * "USA"   is forbidden
* "NPM"  is forbidden (the node package manager, but nobody spells it out in real life)

should be allowed. 

Rule:  Acronyms.

**Comment by nkuehn** [comment]
seen:  .NET  (correct, but the linter thinks we forgot a space after the end of a sentence)

should be allowed

**Comment by nkuehn** [comment]
For awareness (not seen yet: We can warn or block race and slavery related metaphors technical language as it was brought up by various open source projects.  For example
- whitelist(ed) -> allowed, good, ...
- blackliste(ed)  -> disallowed, forbidden, ...
- master
- slave
- native (feature)
- ...
 
It's covered in Google's writing style that we base on but not checked in this automated checker.  https://developers.google.com/style/inclusive-documentation#features-and-users

**Comment by nkuehn** [comment]
@stmeissner  found this in a release note:
  * found:  "Extenstions ...."  
   * should be "API Extensions ...."

**Comment by nkuehn** [comment]
maybe already covered in our weasel words but occurred in a recent docs PR:  "upgraders", like absolute, utterly, overly

**Comment by nkuehn** [comment]
Here's a repository with a lot of various style guide rules for inspiration to pick things from:  https://github.com/testthedocs/vale-styles

**Comment by nkuehn** [comment]
**deactivate "Vale.spelling" rule** - I am adding suggestions to the configuration of the VSCode workspace, but the spelling is dominating the output and is not of good quality.  The VScode spellright plugin does a better job by using the operating system spell checker.

**Comment by stmeissner** [comment]
Currently we have no guideline for abbreviations of high numbers. like 1 million.
In a PR I found `1M` as acronym, but this is not covered by the [Google Style Guide](https://developers.google.com/style/numbers).
One option is to forbid such abbreviations at all since they are rather used as unit of measurements for which we have clearer rules, e.g. 1 MB for one megabyte.

**Comment by adinakleine** [comment]
> Currently we have no guideline for abbreviations of high numbers. like 1 million.
> In a PR I found `1M` as acronym, but this is not covered by the [Google Style Guide](https://developers.google.com/style/numbers).
> One option is to forbid such abbreviations at all since they are rather used as unit of measurements for which we have clearer rules, e.g. 1 MB for one megabyte.

I like the idea of eliminating unnecessary abbreviations like this. 👍

**Comment by nkuehn** [comment]
> In a PR I found `1M` as acronym, but this is not covered by the [Google Style Guide]
Please see https://developers.google.com/style/units-of-measure , it's "implicitly covered" as the google style explicitly allows "5k" (small "k" for thousands) as an exemption, but not "3m" for millions.   The question is technically not about units as measure but they seem to cover it on that page (i guess because it's usually coming up alongside with "KB" vs. "kilobyte" vs. "Kb" etc.)

**Comment by adinakleine** [comment]
> For awareness (not seen yet): We can warn or block race and slavery related metaphors technical language as it was brought up by various open source projects. For example
> 
> * whitelist(ed) -> allowed, good, ...
> * blackliste(ed)  -> disallowed, forbidden, ...
> * master
> * slave
> * native (feature)
> * ...
> 
> It's covered in Google's writing style that we base on but not checked in this automated checker. https://developers.google.com/style/inclusive-documentation#features-and-users

FYI: There is already an [issue](https://github.com/commercetools/fe-chapter-notes/issues/163) for discussion in the fe-chapter-notes repository.

**Comment by nkuehn** [comment]
commercetools  set terms:
 * "ImpEx" -> "IMPEX"  (for example seen on https://docs.commercetools.com/import-and-export )

**Comment by adinakleine** [comment]
commercetools set terms:

- [UI-Kit](https://docs.commercetools.com/custom-applications/components/ui-kit#top)
- [UI Kit](https://uikit.commercetools.com/?path=/story/introduction--getting-started)
- [UiKiT](https://uikit.commercetools.com/?path=/story/introduction--getting-started)
- [UIKit](https://docs.commercetools.com/custom-applications/support-policy#release-process)

**Comment by nkuehn** [comment]
"CORS" - spelling it out does not explain it better.

**Comment by nkuehn** [comment]
The Vale VSCode plugin now supports configuring it to show "suggestion" level rules in the editor without running them on GitHub too (and annoying everybody). 

I tried it, its nice for some things but the current state of the rules show enormous numbers of suggestions of whom most that are not a fit for us are from the "write-good" ruleset.    I think it would be good to pick a few purely stylistic rules and show them to authors as suggestions, but the current state makes the editor UI very annoying.

**Comment by stmeissner** [comment]
In the [Docs Smoke Test](https://commercetools-docs-kit.now.sh/docs-smoke-test/) we have the term "chapter" in the left hand navigation, but the style checker currently reports a warning about this:
`Use 'document, page, or section' instead of 'chapter' (case insensitive).`

**Comment by nkuehn** [comment]
"VAT" acronym for value added tax can be allowed in a commerce environment.

**Comment by adinakleine** [comment]
> "VAT" acronym for value added tax can be allowed in a commerce environment.

Added to acronyms.yml in PR #840

**Comment by adinakleine** [comment]
> seen:
> 
> * "USA"   is forbidden
> * "NPM"  is forbidden (the node package manager, but nobody spells it out in real life)
> 
> should be allowed.
> 
> Rule: Acronyms.

Added to acronyms.yml in PR #840

**Comment by nkuehn** [comment]
Notes from working through the rules with @timonrey   : 
- `ZEIT`in acronyms can be removed, the brand is "Vercel" now
- ".NET":  we would have to override the Google Rule for Spacing and add an exception block  that includes ".NET" 
- the excemption for old jekyll content can be removed:  https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/writing-style/.vale.ini#L16 
-  we need to re-run the update styles script for Google and 
- blacklist / whitelist etc not covered yet --> allowlist, denylist
- Nodejs must move from Product to WordList_CaseSensitive  (only our own brand and product terms are hard errors)
- "Extension" vs. API Extension:  wontfix, "Extension" can happen in other context and is still a valid word. But we could introduce a new rule file `WordList_Suggestions`  that is set to level suggestion and gives a hint "consider using X instead of X"
- add "utterly" and "overly"  to weasel words
- Impex:  change to new convention, `ImpEx` is correct. 
- set `Vale.Spelling` to `NO` in the config so we can explore enabling suggestion level in VSCode. 
- Create a new standalone issue for the millions `1M` discussion and copy the three comments above over. 
-
