### ISSUE TITLE
New Release Note Type: "Announcement"

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#439]
While starting to migrate existing platform release notes we realised that a number of release notes don't fit into the types we defined in the design process  (enhancement, new feature, resolved issue).  

The types in question are 
 * announcements, that in the future a change will happen - e.g. one that requires customers's attention
 * information that a feature is being removed from the documentation as the start of its end of life. 

They are called "announcements" in the existing wording and we would like to keep that because comparable synonyms are either confusing in the context of Release Notes ("Note" / "Notification") or seldomly used or specific ("bulletin").  

Specifiics:
 * Color of the badge:  To be defined @Shecki 
 * key in the data scheme: "announcement"
 * UI Text: "Announcement"

Since he types are strictly validated it's a bit pressing

**Comment by Shecki** [comment]
@nkuehn 
what do you mean with badge?
![image](https://user-images.githubusercontent.com/28807759/82056905-e3ecf300-96c2-11ea-9eff-60b0c10ff3e2.png) <- this one?

**Comment by nkuehn** [comment]
I mean this one in the release notes ("Feature" in this case)

![image](https://user-images.githubusercontent.com/4006139/82057342-7db4a000-96c3-11ea-88d7-d61925696770.png)

**Comment by Shecki** [comment]
ah sorry!
Realse-notes

**Comment by Shecki** [comment]
Here you can see three suggestions from my side

![image](https://user-images.githubusercontent.com/28807759/82057792-2a8f1d00-96c4-11ea-9178-6c5bc22230e3.png)

**Comment by nkuehn** [comment]
How about the orange one?  The other two are very similar to the existing three ( https://commercetools.invisionapp.com/d/main#/console/19438556/408192223/preview ) 

I think we just need the two color definitions here.

**Comment by Shecki** [comment]
ok, orange it is.
will upload the screen to invasion and link the page here

**Comment by Shecki** [comment]
https://commercetools.invisionapp.com/share/NYW48W04MJP#/406140186_Label

here you can find the "orange lable"

**Comment by nkuehn** [comment]
I just realized these are all the standard Stamps from the UI Kit. Sorry to have bothered you @Shecki , this could have been simpler.

**Comment by Shecki** [comment]
ah sorry, thought that this is already clear

**Comment by nkuehn** [comment]
@Shecki  here's the preview:  https://commercetools-docs-kit-git-release-note-announcement-type.commercetools.now.sh/docs-smoke-test/releases#top 

I looked at the UI kit spec  https://uikit.commercetools.com/?path=/story/components-stamps--stamp and wonder whether the Announcement wouldn't better match the "information" tone. 

Current mapping:
 * feature -> positive
 * enhancement -> information
 * announcement -> primary
 * resolved issue -> (custom violet)

Maybe better mapping:
 * feature -> positive
 * enhancement -> **primary**
 * announcement -> **information**
 * resolved issue -> (custom violet)
 
it would match the meaning better and feature and enhancement, which are only a gradual difference, would have more similar colors too. 

What do you think?  (very not-urgent, all is fine and we can change it later too)
