### ISSUE TITLE
API docs: Include Request Examples for Endpoints

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#445]
RAML allows "example" and "examples" properties for query parameters, POST payloads etc ,too but we have not yet defined the usage pattern in example files.  

Some constraints need to be clarified, e.g. how to connect query, path and request body examples that could have differing names or some be a single example and others multiple.   

Also, the examples would have to be converted into e.g. a single cURL call example.

**Comment by nkuehn** [comment]
@davifantasia  I had the impression you did this already?  Please try to keep the issues up to date.

**Comment by davifantasia** [comment]
@nkuehn there are a couple of missing things

* Including examples in auto-generated RAML doc, from my discussion with @ashishhk last week, @jenschude will take a look when he gets back in a couple of weeks. Here is the issue - https://github.com/commercetools/rmf-codegen/issues/162
* Rendering the examples (I suppose this should be a separate issue)

**Comment by nkuehn** [comment]
> * Include examples in auto-generated RAML doc, from my discussion with @ashishhk last week, @jenschude will take a look when he gets back in a couple of weeks. Here is the issue - [commercetools/rmf-codegen#162](https://github.com/commercetools/rmf-codegen/issues/162)

Can you please provide Ashish the acceptance criteria he needs in his issue to enable this to move on? Thanks !

**Comment by jenschude** [comment]
I opened a PR which will add examples for bodies, responses and uriparameters in the same way they are rendered for types.

Just for UriParameters they are directly added as a value cause uri parameters should be only scalar values

See https://github.com/commercetools/rmf-codegen/pull/164 and https://github.com/jenschude/ramldoc/commit/24d7971e5401b30b787b1b055f2285ffe1ee4e4a how it should look like

**Comment by nkuehn** [comment]
Thanks a lot @jenschude !  

How about query parameters?  The RAML spec has them as individual scalars, too.   We've got examples now in the documentation smoke test: https://github.com/commercetools/commercetools-docs-kit/blob/master/websites/api-docs-smoke-test/source-raml/test/api.raml#L73  

(sorry, I was not 100% what sense to make of the link to your "ramldoc" repository)

**Comment by jenschude** [comment]
Yeah I already saw that i forgot the query parameters and added them too:

https://github.com/jenschude/ramldoc/commit/3e30ec4a8c5d9feeb8598b2374fe534a73b1c17d

And the ramldoc was just to point out how the rendered raml files would look like

**Comment by jenschude** [comment]
I just released a new version of the codegen with the changes to examples:

to install latest version:

```
export VRAP_VERSION=1.0.0-20200617122809 && curl -o- -s https://raw.githubusercontent.com/vrapio/rmf-codegen/master/scripts/install.sh | bash
```

**Comment by nkuehn** [comment]
Thank you @jenschude  - the new version is in the docs-kit now, but we keep this issue open to build an example frontend.

**Comment by nkuehn** [comment]
Since the default rendering of a request example is a curl command I suggest to start with that before diving into any SDK specific endpoint request examples. 

Also, we don't need support for multiple examples, do a hard check on "default"

To try out, use  https://httpbin.org/post (or /get /delete)

often forgotten simplifications in curl calls:
 - `-X POST` is not necessary  if `-d` // `--data`  is passed (-d implies POST)
 - `-u` implies `--basic`,  don't additionally pass `--basic` (from the curl docs: "This is the default and this option is usually pointless")
 - since 2013 curl has the `--oauth2-bearer`  flag which is more concise than manually composing the Authentication header, BUT it does not seem to consistently send the header in HTTP. maybe it's intended for other purposes

To be decided:
 - token placeholder
 - multiline with backslashes or not? 
   -  can be a problem in the classic windows command prompt - it has a `^` escape character but it's not 100% robust)
    - windows powershell supports backticks for multiline, so it's really inconsistent
 - pretty print the JSON payload into many lines or not?  (if we do many lines)
 - prefer the long `--data` parameter or the `-d` shortcut? (same for `-h`, etc.)
 - always include `-i`  to have curl print the response headers? This helps teaching that we have important headers but makes the output more complex, too. 

## Here's an initial proposal for the cURL "language" output: 

### GET

```sh
curl  https://api.{region}.{cloudProvider}.commercetools.com/{projectKey}/customers?where=foo&limit=bar  -i \
     --header 'Authorization: Bearer YOUR_TOKEN' \
```

### POST
```sh
curl  https://api.{region}.{cloudProvider}.commercetools.com/{projectKey}/customers?param=foo  -i \
     --header 'Authorization: Bearer YOUR_TOKEN' \
     --header 'Content-Type: application/json' \
     --data '{ "name": "cool event" }' 
```
### DELETE

```sh
curl -X DELETE https://api.{region}.{cloudProvider}.commercetools.com/{projectKey}/customers  -i \
     --header 'Authorization: Bearer YOUR_TOKEN' \
```

**Comment by nkuehn** [comment]
@jenschude  @davifantasia  here's some thoughts about generating request example code after our conversation yesteday:


### concerning "where to put it in RAML":
I saw that some parts of the import API have multiple actual response examples and use the key and description to give them a name.  It's not the case on requests and more cumbersome there but since it's possible on requests to (e.g. by using the same key to match query parameters, uri parameters and response body examples) I think my initial idea to use the keys for programming languages is not a good one.  It would shut the door to multiple examples later on. 

But I saw that annotations are allowed inside an example.  So we could consider putting them into annotations that have the key of the respective programming language, e.g. `(curl)`.   https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#as-a-map-that-contains-additional-facets 

### concerning generating in the frontend vs. in the code generator:

generally we agreed that the rmf-codegen is the better place.  There's just one extra aspect:  we'd like to be able to dynamically insert a specific region, cloud and project key so a user can set that once in her browser and can then actually copy the code.  But if we stick to a clear convention how the placeholders are "escaped" that's possible as a simple string replacement.

**Comment by nkuehn** [comment]
PS: I tried to create a simple to generate but still concise pattern in the current JS SDK but it's messy. If you don't use the request builder it's super verbose with all the middlewares and manual http headers and if you use the request builder it's hard to generate and could confuse users.  

In the training exercises we realized relatively concise versions but that's sort of fake because we provide a bunch of helper functions in advance:  https://github.com/commercetools/commercetools-js-sdk-training/blob/solutions/handson/product.js#L37
