### ISSUE TITLE
Remove "Thanks @username !" block from releases - it's 90% wrong

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#472]
The changesets configuration tries to map changes to contributors and nicely says Thanks!  I really like the idea but unfortunately it's wrong in 90% of the last cases. 

The work seems to be randomly assigned to the renovate bot (even if its a feature) or @emmenko  (across all topics, his work but also work by @davifantasia  or the renovate bot). 

I think we better remove that part from the template than have that completely awkward list of features that are supposedly contributed by a bot ;-)

**Comment by emmenko** [comment]
There was a bug, it's been fixed now.
