### ISSUE TITLE
Implement Final Color Presets

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#475]
We've now received the real color codes and banner graphics for the color presets (assets available in google drive). 

Invision Prototype: https://commercetools.invisionapp.com/d/main#/projects/prototypes/19262954

In addition to the four we have already implemented, three new options are now defined that are not yet assigned to topics but are intended to be already implemented as "option-1", "option-2" and "option-3".   We can later alias them with meaning once they get used.  Some of the colors are from the UI kit and some are new (all signed off with Camilo, he did the banners himself). 

Each consists of:
 * the key color ("color")
 * the lighter color that is the end of the gradient in the banner and fills the rest of the width if the screen is wider than the banner
 * a banner SVG
 * a card image SVG for cards that are generically referring to the topic on the home page. 

On the landing page, the banner is attached to the left and does not stretch or scale in other responsive sizes - you just see less and less of the pattern.  This makes sure that the title text of the landing page is always over dark enough background. 

The height is fixed - we may want to increase the title width to fit more typical titles into two lines. 

**Task here**:
 * add the new assets
 * add three new color presets
 * implement the correct height and background of the banners
 * propose how to provide the card image patterns to content authors in MDX. 

The Home page and Cards on the home page are not part of this issue, I'll create a separate one.

**Comment by emmenko** [comment]
I can work a bit on this today

**Comment by emmenko** [comment]
Q: it says the height is `200px`. What should happen if the header text is long?

**Comment by emmenko** [comment]
For example:

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/1110551/83763978-a2c08100-a679-11ea-9199-18769245a0df.png">

I guess authors should try to fit the header in 3 lines...

**Comment by emmenko** [comment]
One thing I noticed is that the provided SVGs are not "properly aligned". Notice how the patterns tend to "shift" to the right. I'm not sure this is on purpose, I would expect the patterns to "start" more or less at the same position.

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/1110551/83776863-fc7c7780-a688-11ea-8288-0611700f08f1.png">

cc @Shecki

**Comment by nkuehn** [comment]
The Title should fit into two lines normally.  If a third line is possible that's nice for edge cases or mobile devices. 

A fourth line can look bad or be completely cut off.  If it looks horrible that's a strong signal to the author to not write novels in the title. 

---

Concerning the start position of the pattern I wouldn't block this - it's intended that they are visibly different, e.g. when  the small version is used in cards that stand next to each other. 

Camilo and Sven have both looked over it, so I assume it's not a bland oversight.     Last call to @Shecki  nevertheless.

**Comment by Shecki** [comment]
@emmenko 
Yes, that the Pattern moves is on purpose.
even that a user will never see them one by on at the same time, the always should have a different look for the rectangle.

**Comment by Shecki** [comment]
it could be that the user sees the "small-Card-Banner" right next to each other,
and there he will see that the "rectangles" always on the same position.
this should generate a slight feeling of "motion"

**Comment by emmenko** [comment]
I just noticed that the SVG is rendered differently in Chrome (left) and FF (right) 🙃

<img width="2560" alt="Screenshot 2020-06-05 at 12 38 36" src="https://user-images.githubusercontent.com/1110551/83867376-9d227400-a729-11ea-994d-c6b9a9d864c3.png">

**Comment by emmenko** [comment]
Which is weird because if I access the SVG file directly it's rendered correctly on both browsers

<img width="2560" alt="Screenshot 2020-06-05 at 12 42 02" src="https://user-images.githubusercontent.com/1110551/83867641-0bffcd00-a72a-11ea-88cc-0bddeabd3208.png">

**Comment by emmenko** [comment]
It seems to be something related to the `background-url` CSS property.

I'll give it a try with an inline data svg.

**Comment by emmenko** [comment]
Same result.

By looking at the SVG itself, I noticed there are a lot of `mask` elements with `<use xlink:href`. Is this correct? @Shecki can you double check?

**Comment by nkuehn** [comment]
closed via #480
