### ISSUE TITLE
Broken Sorting of Release Notes

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#481]
I just realized a regression that must have come in in some past release.  

the Release notes are not sorted from newest to oldest any more.  In the smoke test page they follow no specific pattern, in the full migrated documentation they appear to be sorted from oldest to newest. 

Tasks here:
 * add release notes list page to the visual regression test
 * make sure that release notes are always sorted from newest to latest.

**Comment by emmenko** [comment]
Are you sure?

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/1110551/83866636-5d0ec180-a728-11ea-9202-411a2fbb93aa.png">
