### ISSUE TITLE
bug: access to Product Modelling Guide / Products

### ISSUE THREAD

**Issue by adinakleine** [commercetools/commercetools-docs-kit#484]
Product types and attributes part in the Product Modeling Tutorial is not displayed.

**Steps to reproduce the bug:**
1. Open https://commercetools-docs-git-sync-docs-content.commercetools.now.sh/tutorials/product-modeling/products
2. Scroll down
3. "unable to load the view" is displayed
![Bug](https://user-images.githubusercontent.com/58512719/83890988-d3251f80-a74c-11ea-8941-f3af78b54f2e.png)

**Comment by davifantasia** [comment]
@adinakleine the page seems to work fine now so I will close this issue. Please feel free to re-open it if the problem occurs again.

**Comment by adinakleine** [comment]
> @adinakleine the page seems to work fine now so I will close this issue. Please feel free to re-open it if the problem occurs again.

Many thanks!
