### ISSUE TITLE
Release Notes: Trim Topic Strings to avoid duplicate filters

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#530]
Since the Release Note Topics are data driven it can occur that they accidentally have whitespace around them or other unwanted characters. 

This currently results in this UI:

![image](https://user-images.githubusercontent.com/4006139/86094594-08edc780-bab1-11ea-96ae-813c741941a7.png)

As a firs measure please trim the values when loading them (either already when building the GraphQL nodes or when building and applying the filter data structures). 

It can't reliably be avoided, authors can but whitespace in YAML frontmatter accidentally.

**Comment by davifantasia** [comment]
@nkuehn how can I replicate this bug?
