### ISSUE TITLE
bug(theme): automated graphql scheme generation affected by other plugins in sites

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#54]
If a site uses the theme but also uses other plugins and these plugins are creating graphQL surface, the generated scheme file is updated in the theme plugin source code without the theme actually being affected.  
If that modified file is accidentally committed it contains scheme that has nothing to do with the theme. 

overall impression:  since the theme is not generating any graphQL surface itself by creating nodes I think it does not need to have any sort of persisted schema definition.

**Comment by emmenko** [comment]
Hmm I see...let's remove the plugin then for now
