### ISSUE TITLE
API Endpoint:  Request payload with example broken in wide layout

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#550]
Situation:
 * API endpoint 
 * request body not placed somewhere else on the site but rendered directly in the endpoint layout
 * request body type has an example
 * wide layout

Current:  request body type and its example are rendered side-by-side but don't have the space, so the type is compressed to a thin column
 
Intended: request body type and its example can take the full width.  I.e. the complete API endpoint needs to allow the width and constrain its children to 770px except when they are side-by-side.   It might require using a different stack implementation, let's see.

**Comment by emmenko** [comment]
Can you provide a screenshot so it's easier to pinpoint the issue? Thanks

**Comment by nkuehn** [comment]
![image](https://user-images.githubusercontent.com/4006139/87411943-b3dda580-c5c8-11ea-9030-35f8b38ae73f.png)
