### ISSUE TITLE
API docs: Render constant (single value enum) pattern in type properties

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#556]
E.g. in discriminator values of specific types we're just rendering the generic information of the discriminator field instead of the specific string to be sent. 

(use case: CategoryImportSink)

**Comment by davifantasia** [comment]
Just leaving this here for my use:

Use ImportRequest and CategoryImportRequest.

Previous discussion about rendering constants:

Use setChanges in table design - https://commercetools.invisionapp.com/d/main#/console/17784193/390031793/preview
