### ISSUE TITLE
Decision: Consider dropping URN as an anchor pattern

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#559]
We recently experienced a broken page using soft linking on api site in commercetools-docs repo after an update, this is because the urn pattern we use in our anchor links is not valid when querySelector is used. Error returned was:

`DOMException: Failed to execute 'querySelector' on 'Document': '#ctp:import:type:ImportResourceType' is not a valid selector.`

See these link for more information on the reason this happened:
* https://stackoverflow.com/a/37271406/2467003

**Comment by nkuehn** [comment]
@davifantasia I'm not sure what this issue "wants to be" - fix the implementation or reconsider the anchor pattern to avoid future similar changes. 

the colons are the issue but they are the definition of how a URN is built. So if this is about changing the pattern then the title would rather be "consider dropping URN as an anchor pattern"

**Comment by davifantasia** [comment]
> the colons are the issue but they are the definition of how a URN is built. So if this is about changing the pattern then the title would rather be "consider dropping URN as an anchor pattern"

Thanks @nkuehn , this is a much better title.

**Comment by nkuehn** [comment]
@davifantasia  from our conversation:  The remaining problem is in cypress only, here's the FAQ for the topic: https://docs.cypress.io/faq/questions/using-cypress-faq.html#How-do-I-use-special-characters-with-cy-get

**Comment by nkuehn** [comment]
That means: no, we're not changing the spec for now.
