### ISSUE TITLE
Design review: top menu open/close animation

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#564]
Open animation: smooth push down
Close animation: smooth push up

Recommended example https://www.zalando.de/

**Comment by davifantasia** [comment]
The left hand and the top menu should have the same speed, in easing and duration. Also consider making the speed of the left menu, and as a result the top menu, faster.

**Comment by TimonRey** [comment]
@Shecki from the implementation point of view, the closing animation would be too difficult to implement given how the page is built right now. So we agreed to go only with the opening animation for now.

**Comment by Shecki** [comment]
@TimonRey is there a preview where i can see the solution?
Maybe for the close function is an easier animation possible?
Like a fate or something?

**Comment by Shecki** [comment]
as we talked during our meeting, a hover "open-close" animation would be also fine to solve the current issue "click-open"
