### ISSUE TITLE
Design review: index menu item not highlighted consistently on scroll when content menu is used.

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#567]
When we have content menu (see https://new-commercetools-docs.vercel.app/api/projects/categories#representations), scrolling through content that follows removes highlighted menu on the index menu.

**Comment by emmenko** [comment]
As far as I can tell, this is not possible to fix with the current implementation.
The problem is that the (sub) sections are flat, meaning they are sibling elements. And the anchor links are also flat. There is no hierarchical notion of parent-child.
