### ISSUE TITLE
Design review: images with widths less than the content width

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#569]
Image should appear on grey background which spans through entire page with

**Comment by emmenko** [comment]
This is not possible unfortunately and it's a limitation of the gatsby image plugin. This has been discussed in the past already and agreed that we keep it like this.

cc @Shecki @nkuehn please correct me if I'm mistaken.

**Comment by nkuehn** [comment]
Yes, I told @Shecki  that it's very likely a limitation that we already ran into (I was just nearly sure about it when we spoke).  

I would nevertheless keep this issue, link to the dependency and put it on hold (except there is already one and this is a duplicate).

**Comment by emmenko** [comment]
Yes, it's a duplicate of #66
