### ISSUE TITLE
Design review: previous and next buttons in wide layout should be align in the middle

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#571]

**Comment by davifantasia** [comment]
On hold until wide layout is robust.

**Comment by davifantasia** [comment]
WideLayout more predictable with new restrictions so this can move forward.

**Comment by nkuehn** [comment]
When doing this, please change the config of the "docs-smoke-test" website to allow wide layouts at all.  Currently the `wide.mdx` test page does not work.
