### ISSUE TITLE
Managing raml descriptions

### ISSUE THREAD

**Issue by TohruKohrita** [commercetools/commercetools-docs-kit#607]
The raml document generator picks up `descriptions` in raml files. For example, the three sentences "An import sink is the entry ......met the conditions of the predicate." in the following screenshot.
<img width="1282" alt="Screenshot 2020-08-12 at 17 10 35" src="https://user-images.githubusercontent.com/63338357/90032524-beba5180-dcbe-11ea-8819-007e11033e5b.png">

Right now, except for editing raml files themselves, there is no way to turn this off nor overwrite provided descriptions. Since the descriptions in raml files have their own purpose and are used in SDK, we better avoid editing them for documentation purposes alone. 

Thus, it may be desirable. at least worth discussing, to have an "on/off switch" or an overwrite option.

**Comment by TohruKohrita** [comment]
Here is another instance where raml generated content needed editing. Raml yielded the following ImportResourceType subsection: 
<img width="1284" alt="Screenshot 2020-08-24 at 10 19 27" src="https://user-images.githubusercontent.com/63338357/91020870-4d9a6880-e5f3-11ea-9974-b2d2a57bd44d.png">

In addition that we wanted to edit the descriptions in this list, we needed to remove the final item "product-variant-patch" for the moment for a documentation reason. (The type "product-variant-patch" is supported by the Import API, so the raml file should not be edited.) For the moment, I typed with markdown to produce the following desired content:
<img width="1277" alt="Screenshot 2020-08-24 at 10 34 35" src="https://user-images.githubusercontent.com/63338357/91022383-699f0980-e5f5-11ea-8b22-8d3cccb555b9.png">

**Comment by nkuehn** [comment]
My personal stance on this:
 * try to convince clients to have most RAML definitions's  "system of record" (masterdata) in the docs repo and not in another one. 
 * in the case of import API where the definitions serve a purpose inside the development process,  I suggest to explore using a RAML overlay in the docs repository.  The sole purpose of that overlay would be to change or add descriptions (that's the purpose of overlays).  

Overlay spec: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#overlays  

To be evaluated:  Does the RMF implementation support overlays?  We could try running the RMF-codegen over a file that is an overlay and see what's happens.

**Comment by davifantasia** [comment]
Last week, we talked about taking advantage of RAML Overlays. Unfortunately, the RMF-Codegen parser does not currently support Overlays:

https://github.com/vrapio/rest-modeling-framework/issues/33

**Comment by davifantasia** [comment]
> Unfortunately, the RMF-Codegen parser does not currently support Overlays:

@nkuehn from our side, one option is to build this as a feature in our custom MDX components. What do you think?

**Comment by nkuehn** [comment]
@davifantasia  no, overriding data does not belong into the frontend components, that sort of thing belongs into the gatsby plugins generating the graphQL nodes in GatsbyJS.  But it is not straightfoward to realize  that the graphQL node representing an API type is updated both when the overrides file is changed and when the RAMLdoc file is changed - A GatsbyJS node can have only one parent.  

Also, if one descriptions file contains descriptions for many types we can only regenerate the complete API definitions.  

I suggest you and me both think about possible approaches and then speak about it together.

**Comment by nkuehn** [comment]
This is obsolete because the RAML masters sit in the docs repository now and are co-owned by documentation
