### ISSUE TITLE
More realistic query parameter examples to be included in request examples

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#612]
From my discussion with @jenschude , query parameter examples that we currently have [here](https://github.com/commercetools/commercetools-docs-kit/blob/1c684f4c00199587925d9f82838453627dff8f78/websites/api-docs-smoke-test/source-raml/test/api.raml#L74-L97) needs more work to be included in the generated cURL examples.

Each value of a query parameter example will eventually be included in the generated request example. So if a query example is not a needed, incomplete or unrealistic, do not include it.

**Comment by nkuehn** [comment]
obsolete or never actually requested again
