### ISSUE TITLE
Can't resolve 'typeface-roboto' error

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#618]
I'm getting this error intermittently on my dev machine after merging changes in master branch to https://github.com/commercetools/commercetools-docs-kit/tree/ao-render-endpoint-code-examples

![Screenshot 2020-08-19 at 12 53 03](https://user-images.githubusercontent.com/8238495/90626319-16a30c00-e21b-11ea-8b7c-3efb0c2c019a.png)

**Comment by davifantasia** [comment]
@emmenko I guess this bug has something to do with changes in https://github.com/commercetools/commercetools-docs-kit/pull/614

**Comment by emmenko** [comment]
Did you install the dependencies?
You might need to clean the gatsby cache also
