### ISSUE TITLE
Implementation proposal for custom descriptions of some aspects of an API

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#634]
Part of #607 

### Proposal

Take the idea of RAML Overlays and build a custom implementation that would parse YAML or markdown file contents to override descriptions defined in RAML documents.

### Workflow Challenges

How do we manage customization as well as API teams being included in the process?

**Comment by davifantasia** [comment]
One idea is to have a directory with similar file structure as the `api-spec`, we use this to map descriptions appropriately. So a file located at `src/api-spec/types/person.raml` can be mapped to `src/api-spec-descriptions/types/person.md`.

Instead of building a new tool, we can take advantage of the `gatsby-transformer-raml` tool to locate custom descriptions and replace originals where custom descriptions exist.

**Comment by nkuehn** [comment]
ideas developed by @davifantasia  and @nkuehn 

## idea 1: Markdown file convention
![image](https://user-images.githubusercontent.com/4006139/91851106-ecac0980-ec5e-11ea-96a9-ef02e24d2812.png)

## idea 2: YAML file convention

![image](https://user-images.githubusercontent.com/4006139/91851156-fdf51600-ec5e-11ea-84b4-2f824783f3f3.png)

**Comment by nkuehn** [comment]
This is obsolete because the RAML masters sit in the docs repository now and are co-owned by documentation
