### ISSUE TITLE
Component: Single Language code example from file

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#64]
> update: here's a branch with experiments in an actual MDX file: https://github.com/commercetools/commercetools-docs-kit/blob/extended-code-syntax-brainstorming/websites/docs-smoke-test/src/content/code-samples/multi-language-code.mdx

Alternatively to writing example code in markdown as fenced code blocks an author must be able to store the example code in a separate standalone file and pull it into any MDX page.  This provides the advantage that the code examples can be own fully valid software projects that are automatically tested. 

This issue covers the case of a single-language example like fenced code blocks. 

We decided to leverage MDX import statements and custom webpack loaders, which is how gatsbyJS is generally built internally, too.   Webpack can be configured cleanly by a plugin like the theme (see reference link below)

Any import statement loading from a path containing `/code-examples/` (plus maybe further restrictions like whitelisting packages if possible) is managed by a custom loader that returns a function component that is wrapping our standard Code component.  It's detecting the language by file name and injects the content. 

The following code is pseudo-MDX
```md
import CartCreateExampleJs from '@commercetools-docs/code-examples/javascript/cart/create.js'
import CartCreateExampleJava from '../../code-examples/java/cart/create.java'

<CartCreateExampleJs title="Creating a Cart in Javascript" />
<CartCreateExampleJava highlightLines="5-10" title="Creating a Cart in Java" />

```

## Not necessary

We don't need to support cases that cannot be derived from the file name extension (e.g.  individual terminal cli commands that are not part of a shell script)

## References:
 * https://www.gatsbyjs.org/docs/add-custom-webpack-config/
 * how it's currently written in markdown (Liquid templating using a parameterized template import):  https://github.com/commercetools/docs.commercetools.com/blob/master/sdk/jvm-sdk.md  (private repository)
 * https://prismjs.com/plugins/file-highlight/   (not nice because it does an HTTP call at runtime from the browser)

**Comment by nkuehn** [comment]
update from a conversation with @emmenko  about how to approach the topic:
 * we will go for an import and webpack-based approach. Users learn the import notation and have to lean it anyways for MDX transclusion.  
 * code examples from outside the repository will be provided via a special package in the respective content repository which pulls the examples from whereever they live (e.g. the repository of an SDK) and then provides the files as a javascript package. 

I'll update the issue description here

FYI @davifantasia

**Comment by davifantasia** [comment]
I just want to say I started working on this.

**Comment by davifantasia** [comment]
To be able to implement this:

```
import CartCreateExampleJs from '@commercetools-docs/code-examples/javascript/cart/create.js'
import CartCreateExampleJava from '../../code-examples/java/cart/create.java'

<CartCreateExampleJs title="Creating a Cart in Javascript" />
<CartCreateExampleJava highlightLines="5-10" title="Creating a Cart in Java" />
```

I looked into exporting [CodeBlock](https://github.com/commercetools/commercetools-docs-kit/blob/master/packages/ui-kit/src/components/code-block.js) component from a webpack loader. I mainly used this plugin as a base, because it pretty much has a similar process compared to what we want to achieve:

https://github.com/gregberge/svgr/blob/master/packages/webpack

My conclusion is that I have to understand how Babel transpiles both ES6 and React. At least for now, I don’t think it’s worth the effort.

**Comment by davifantasia** [comment]
Current solution proposal:

Expose a AutoCodeExample component which authors can then use like so:

```
<AutoCodeExample import="@package/path/to/sample-code.js" title="JavaScript Code Sample" />

<AutoCodeExample import="/path/to/sample-code.java" />
```

`AutoCodeExample` - name was chosen after discussing with @adinakleine , since this tool is author-centric.

**Comment by emmenko** [comment]
In the PR #299 you only load code examples from a local folder. What about external files?

**Comment by davifantasia** [comment]
> In the PR #299 you only load code examples from a local folder. What about external files?

That is still a draft PR. I appreciate early review but in this case I suggest you wait until I mark it as ready for review.

**Comment by davifantasia** [comment]
I was still having trouble implementing this task by taking advantage of building a webpack plugin, so after sitting down with Jens, I decided on a different approach. Please see the PR here - https://github.com/commercetools/commercetools-docs-kit/pull/300
