### ISSUE TITLE
Implement Filtering over ChildSectionNavigator  (phase 1)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#643]
we have now received the final UX design for the ChildSectionNavigator component.  It defines the spacing more precisely and specifies a filter search box at the top of the component. 

This ticket covers implementing the basic functionality,  advanced / nice to have functionality is to be implemented in a separate ticket. 

Design link - https://commercetools.invisionapp.com/console/commercetools-API-DOCS---Component-V2-ckem9zrer39id01z90qsjc8iy/cketv6lbk02te01xk6zll8jwo/play

 * implement spacings and minimum height as specified.
 * filtering the contents as-you-type 
 * active / inactive state of the search box

Not immediately doing here:
 * display sentence beginnings like "set" "delete", "add a" etc.  in lighter font
 * fixing the box height when filtering (to be evaluated by UX first after basic behavior is implemented)
 * highlighting the matching substrings in color

**Comment by davifantasia** [comment]
Design link - https://commercetools.invisionapp.com/console/commercetools-API-DOCS---Component-V2-ckem9zrer39id01z90qsjc8iy/cketv6lbk02te01xk6zll8jwo/play

**Comment by nkuehn** [comment]
done already
