### ISSUE TITLE
CodeExample component does not appear on rendered page

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-docs-kit#648]
Looks like there are problems with rendering content of CodeExample components, 
For example, that component is not rendered at all:

`<CodeExample path="api-authorization/oauth-getToken.sh" title="Example Request" />`

although the file `api-authorization/oauth-getToken.sh` does exist in the `src` folder of my website.

Could you please check what is wrong with that? Thanks

**Comment by nkuehn** [comment]
@davifantasia  (side aspect) I wonder why the `src/code-examples` folder convention is not documented in the docs theme.  
https://github.com/commercetools/commercetools-docs-kit/tree/master/packages/gatsby-theme-docs#folder-structure  - it's implemented in a separate plugin but the docs theme is always loading it so it's effectively part of the docs-theme folder convention

@stmeissner  you mention that the path exists in the `src` folder.   The code examples have to live the `src/code-examples` folder though.

**Comment by TohruKohrita** [comment]
> @stmeissner you mention that the path exists in the `src` folder. The code examples have to live the `src/code-examples` folder though.

The code examples are put in subfolders in `src/code-examples`. eg. `src/code-examples/api-authorization/oauth-getToken.sh`

**Comment by stmeissner** [comment]
The files are in the folder `src/code-examples`, and they are not rendered.
Sorry for confusion.

**Comment by davifantasia** [comment]
> @davifantasia (side aspect) I wonder why the `src/code-examples` folder convention is not documented in the docs theme.
> https://github.com/commercetools/commercetools-docs-kit/tree/master/packages/gatsby-theme-docs#folder-structure - it's implemented in a separate plugin but the docs theme is always loading it so it's effectively part of the docs-theme folder convention

`gatsby-theme-docs` does not include the `gatsby-theme-code-examples`, `gatsby-theme-code-examples` needs to be added as an add-on theme.
