### ISSUE TITLE
Layout of release note section on homepage

### ISSUE THREAD

**Issue by adinakleine** [commercetools/commercetools-docs-kit#649]
The titles of the release notes on the homepage have different starting points. It looks a bit messy (see red line in attached screenshot).
I would suggest to have a date field with a fixed width which fits for the longest date: 30. September 2020. This would ensure that all release note titles start at the same horizontal point.
For sure we have to consider how this would fit for mobile phones.
![Release notes on homepage](https://user-images.githubusercontent.com/58512719/93184270-50910080-f73c-11ea-8df8-2755998c49a8.png)

**Comment by nkuehn** [comment]
duplicate to #657
