### ISSUE TITLE
Component: Multi Language code example from external files

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#65]
> update: here's a branch with experiments in an actual MDX file: https://github.com/commercetools/commercetools-docs-kit/blob/extended-code-syntax-brainstorming/websites/docs-smoke-test/src/content/code-samples/multi-language-code.mdx

(This builds on top of #64 )

Since markdown does not allow to express multi-language code blocks examples that have a language switcher need to be pulled from external files.   The implementation may also support multi-language code blocks that hold the actual code in the markdown document, but that is not the design we optimize for. 

pseudo-MDX based on the pattern developed for single language code in #64 :
```
<MultiCode title="Creating a Cart">
   <CartCreateExampleJs />
   <CartCreateExampleJs highlightLines="5-10" />
</MultiCode>
```

This tickets stands for the first iteration, which must not yet support a data layout that has all the languages next to each other in a folder and allows to pull all languages via a wildcard import. 

The languages end up in the dropdown on the right of the title. 

It must be possible to pass a title

Child Elements are always single code examples that are rendered without their title bar and copy button.

**Comment by nkuehn** [comment]
(updating the description with today's findings now)

**Comment by nkuehn** [comment]
Design updates:

 * orginal design:  https://commercetools.invisionapp.com/d/main#/console/17784193/388242718/preview
 * changes in reality:  The copy button is always inside the code area ( makes it easier to implement here, too)
 * robust CSS  to style the native select:  https://github.com/filamentgroup/select-css  (seems pretty doable to override the closed style and leave the open style as native)
 * UI kit select (does not match our design due  to the colored border in closed state: https://uikit.commercetools.com/?path=/story/components-inputs--selectinput

**Comment by emmenko** [comment]
> UI kit select (does not match our design due to the colored border in closed state: 

It can be customized by using the createable select inputs (react-select is composable).

> robust CSS to style the native select:

Not sure it's needed
