### ISSUE TITLE
Links to static downloads "caught" by react and showing a 404. 

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#680]
For example in https://docs.commercetools.com/tutorials/extensions#validate-maximum-number-of-ten-items-in-the-cart  there are links to static downloads.   GatsbyJS uses the "static" folder next to "src" and the links actually work. 

But if the link is clicked inside the content generated by MDX it's caught by the `Link` component that tries to navigate to the location using react router (without loading a page). 

So we need a way to 
 - either make the link component understand that the links to the static stuff under "downloads" is not handled, i.e. handled as a regular link tag and not as a 
- or find a content pattern in MDX that instructs the link to open in a new tab or something else that leaves the react page context

**Comment by emmenko** [comment]
Didn't we have a convention to have static files in a `src/content/files` location?
https://github.com/commercetools/commercetools-docs-kit/tree/master/packages/gatsby-theme-docs#auto-generated-directories

And yes, I suppose the `<Link>` should be fixed. If we follow the convention of the `src/content/files` folder, then we can leverage that.

**Comment by nkuehn** [comment]
@emmenko  no, I cannot remeber that convention to have ever gone live.   I think we wanted it but found it does not really work and thus resorted to 

But this problem is independent of how the file gets to a given URL path, it's about detecting it from the URL found in markdown without knowing anything else (in the Link component). 

Propsal discussed in the daily:
 * detect `^/downloads/.*`   as always being handled through an `<a>`
 * detect `.html$`  as always not being handled by react.  (file extension = some other generator)
