### ISSUE TITLE
investigate "Cannot read property 'light' of undefined"  errors in sentry

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#682]
Among a few that rather look like outliers here's one issue that seems to occur with a certain regularity: 

https://sentry.io/organizations/commercetools/issues/1452889339/ 

"light" could relate to something that has two themes, maybe a code example block?

**Comment by emmenko** [comment]
Somehow I managed to see this issue during build time:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1110551/98098090-2a5f2580-1e8e-11eb-862a-fdefcfbf00ab.png">

This should help with the investigation
