### ISSUE TITLE
google analytics tracks pages including hash

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#694]
I don't think it's right to track pages separately per chapter hash that they were navigated to.  Let's check where that behavior comes from 

![image](https://user-images.githubusercontent.com/4006139/95180943-ead7e780-07c2-11eb-91ee-c7de2497302e.png)

**Comment by emmenko** [comment]
It's the behavior of the gatsby plugin: https://github.com/gatsbyjs/gatsby/blob/ce34c6ed10786f889ca65f61deadb78cab64e7c5/packages/gatsby-plugin-google-analytics/src/gatsby-browser.js#L15-L19

I suppose if we want to have control on what we track, we would need to implement the plugin on our own.

**Comment by nkuehn** [comment]
I could not find a suitable option among the huge list of google's `analytics.js` client documentation (all options to the gatsby plugin are passed through to the GA script, so that would have been the easiest way). 

I'll take a look at what I can do server-side in the google analytics configuration, maybe I can retain the information for good use without spamming the page tree analytics.

**Comment by nkuehn** [comment]
I started realizing the needed custom views and filters now - it's the more powerful and flexible approach than omitting the hash from the beginning and never sending it to GA at all.
