### ISSUE TITLE
<Constant> component for limits not rendered in Release notes preview - good or bad? 

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#698]
The fragment renderer does not seem to have received support for our  `<Constant>` feature.   It's not an omission but a conceptual question - the fragment renderer is intended to render only plain markdown,  mainly in situations like rendering the descriptions of API spec data that was provided in RAML and other 3rd party sources with microformatting. 

So it's not an MDX renderer at all and so it can't render our custom components. 

here's an example:
![image](https://user-images.githubusercontent.com/4006139/95322820-64dc9f00-089d-11eb-8c09-13f86a4bb5cc.png)

This issue has two aspects:
 * technical:  we were struggling with it, but after the MDX 2.0 release we could take another look at maybe using an actual MDX renderer
 * **conceptual:  A release note should not use the constant but the literal value of the limit at the time of the release.  When the value is later changed, the old release note should not change to the new value!   So from that perspective it's a non-use case and actually good that the limit is not rendered.**

**Comment by stmeissner** [comment]
I see the conceptual aspect, a release note captures the state as it was at the time of the release date and should thus not contain any variable values.

**Comment by nkuehn** [comment]
Closing, was forgotten to be closed with the PR merged
