### ISSUE TITLE
UX: consider to copy address when clicking on Section Anchor icon (instead of navigating)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#699]
Given that Chrome will remove the default display of the path in the address bar rolling out gradually starting with Chrome 86 (now) it can be expected the the whole concept of the address bar to see the full URL will further deteriorate. 

Here's how the new browser bar will show addresses (just the host, no matter where you are). 
![image](https://user-images.githubusercontent.com/4006139/95324257-bd14a080-089f-11eb-8555-4bbe3fdf32f3.png)

For example, the google cloud documentation is not actually navigating to the anchor when the anchor icon is clicked but is only copying it the to clipboard and that's it.   
Example:  https://cloud.google.com/compute/docs/instances/create-start-instance#publicimage

**Comment by timonrey** [comment]
Idea approved by @Shecki

**Comment by nkuehn** [comment]
Implementation proposal:  Exactly like it's done in the code block component.  Click on it and then there is a tooltip popping up confirming it was copied.  Not sure if making it re-usable is worth it but worth a look if e.g. the clipboard logic is tricky
