### ISSUE TITLE
Possible to declare all allowed mdx frontmatter as explicit schema ?

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#70]
(absolute nice-to-have just for robustness) 

Currently, if a site's content never uses a frontmatter key that is queried by our implementation, the site build fails because the queried field is not on the graphQL schema. 

The "beta"  frontmatter is such a case.  

I don't know whether it is possible at all to change the graphQL surface of other plugins (gatsbyjs is shielding plugins from each other pretty good), so this might well simply not work.

**Comment by emmenko** [comment]
TL;DR: it does not work out of the box using the gatsby schema extension hooks/points.

However, I found a workaround that we could use to circumvent that problem. I'll open a PR and we can talk about it there.
