### ISSUE TITLE
UI change: Move beta flag from main (left) to index (right) nav

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#700]
We have decided to implement moving the page-level beta flags from the left hand (main) nav to the right hand (index) nav's top area. 

While touching the top right corner anyways, the icon for "back to top" link is also changed to a more explicit upward pointing arrow. 

The data sourcing is not changing, the information is available on graphQL in the page metadata. 

Inspectable design prototype here ( closed account in commercetools):  https://commercetools.invisionapp.com/console/share/WP1MKLPW6A

Screenshot:
![image](https://user-images.githubusercontent.com/4006139/95422587-dc630a80-093f-11eb-9fb3-88257ea316fb.png)

**Comment by emmenko** [comment]
Thanks, the improvements look good to me 👌

Can you maybe explain the reason for moving the beta flag to the right?
