### ISSUE TITLE
Duplicate creation of release notes as content pages, too (performance!)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#704]
I was alerted by a log output claiming "516 SitePage" nodes in the dev mode console in the API docs site, which in fact has 

 * 227 release notes (counted files manually)
 * 59 pages (counted files manually)

To cross check, I pulled all the node counts on GraphQL and found **they are completely off (see below)**

 * `allFile`: **359** - release notes, content pages plus with 2 images, 56 code examples and a few data files that matches the GraphQL "allFile" count good. -> OK
 * `allMdx`:  **286** -  release notes + pages  vs 287 graphQL nodes -> OK for now (i guess I missed one when counting manually)
 * `allSitePage`:  **516**  - what is this?  It contains all content pages plus all release notes **twice**. Every release note is there once with its actual URL as `path` and once with its file path as `path` (see next bullet point for details)
 * `allContentPage`: **287** - contains the content pages AND the release notes also -> **we are building all release notes as a page in addition to being a release note? **
 * `allReleaseNotePage` **227** - that's the correct number. 

Overall, I have the impression that we have a bug in not properly filtering out release note MDX when creating the content page nodes.  To be verified!

```json
{
  "data": {
    "allFile": {
      "totalCount": 359
    },
    "allDirectory": {
      "totalCount": 40
    },
    "allMdx": {
      "totalCount": 287
    },
    "allSitePage": {
      "totalCount": 516
    },
    "allContentPage": {
      "totalCount": 287
    },
    "allReleaseNotePage": {
      "totalCount": 227
    },
    "allCodeExample": {
      "totalCount": 56
    },
    "allConstant": {
      "totalCount": 34
    },
    "allImageSharp": {
      "totalCount": 2
    },
    "allRamlApi": {
      "totalCount": 0
    },
    "allRamlResource": {
      "totalCount": 0
    },
    "allRamlType": {
      "totalCount": 0
    },
    "allSite": {
      "totalCount": 1
    },
    "allSiteBuildMetadata": {
      "totalCount": 1
    },
    "allSitePlugin": {
      "totalCount": 71
    },
    "allTopMenuYaml": {
      "totalCount": 2
    },
    "allTopSideMenuYaml": {
      "totalCount": 6
    },
    "allComponentInMdx": {
      "totalCount": 0
    },
    "allFooterYaml": {
      "totalCount": 2
    },
    "allLimitYaml": {
      "totalCount": 34
    },
    "allNavigationYaml": {
      "totalCount": 9
    }
  },
  "extensions": {}
}
```

**Comment by emmenko** [comment]
A `return` statement is missing after we create a node for a release note page:

https://github.com/commercetools/commercetools-docs-kit/blob/872b4bacff4fe323fe50d39f0e81890530bae713/packages/gatsby-theme-docs/gatsby-node.js#L209-L247

🤦‍♂️
