### ISSUE TITLE
New color for light themed header code block

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#712]
Based on the discussion from:

https://github.com/commercetools/commercetools-docs-kit/pull/692#pullrequestreview-503291705

The background colour of the header of the light-themed code block should be tweaked to the contrast works with both white and grey background. 

@Shecki  now decided that the header background for light code examples can be generally changed to `#CCCCCC` so we still need only two themes for a code block. 

The code block component is on light background and on grey background as seen in the following links:

* https://commercetools-docs-kit.vercel.app/docs-smoke-test/components/code-examples#multiple-languages
* https://commercetools-docs-kit.vercel.app/api-docs-smoke-test/endpoints/endpoints-for-resource

**Comment by nkuehn** [comment]
@davifantasia  thanks! I changed the text to the decision Sven just took. Ready for implementation now.
