### ISSUE TITLE
Automate release note file generation with a script.

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#723]
## Why

Creating a release note (looking for the right location, copying content from the template) can be cumbersome for authors and contributors. So this issue is to help fix the problem.

## Acceptance criteria

Users can create a release note by running a script inside the microsite folder, e.g.

```sh
yarn create-release-note
```

Ideally, a CLI would collect the date, type and title on the CLI interactively using a library like prompts ( https://www.npmjs.com/package/prompts  - there are many others but this is used by gatsby CLI so it's pulled anyways)

Interactive input:
 * "Type": (single select,  "enhancement" / "feature" / "fix" / "announcement")
 * "Release Date": (date, no time)
 * "Title": (String, single line, max 256 chars)
 * "Description in Feeds (title plus value proposition)": (String, single line, max 256 chars - can be prefilled with the title if that is easy to achieve)

File location:  `./src/releases/slugified-title.mdx`  (check what slugify lib we use anyways to avoid an additional dependency)

Script location:  Centrally provided as a bin by the docs theme package 

## Ouput template structure

(written in GitHub, indentation etc. may be wrong)

```js
fileContent = `
---
date: ${isoDate}
title: ${title}
description: | 
  ${description}
type: ${type}
topics:
# Please use the topics defined in the wiki and stay focused.
# https://wiki.commercetools.com/display/DOCS/Writing+release+notes#Writingreleasenotes-Typesandtopics
#  - Topic1
#  - Topic2
---

${description}

<!--more-->
```

**Comment by davifantasia** [comment]
@nkuehn please include information as discussed.

**Comment by nkuehn** [comment]
@davifantasia  I spoke to the team and completed the description text with all details.  Should be relatively straightforward when using a library like prompts and using a  JS string literal. 

Please add the "groomed" label if you think it's good to go.
