### ISSUE TITLE
API Type & Endpoint: "Sticky" behavior inside side-by-side layouts

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#736]
When in side by side layout, the API Types plus their examples should show a sticky behavior inside the side by side container box.  Same for API endpoints and maybe even generally for everything that uses the side-by-side pattern.

The behavior is intended to mimick the one in the Stripe API docs:  https://stripe.com/docs/api/setup_attempts/object  - But in addition, also the type definition on the left column should stick when the example is longer (if that is possible!) 

It's solving the problem that when the type is much longer than the example or the example is longer than the type one of the columns can be just whitespace and also, the reader cannot compare between type definition and example any more.

**Comment by nkuehn** [comment]
I put this back into the backlog because the generated API docs are now being rolled out more.

**Comment by timonrey** [comment]
Link to an example in our docs:
https://docs.commercetools.com/api/history/change-history#query-records
