### ISSUE TITLE
Evaluate new GatsbyJS performance optimization flags

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#781]
See Gatsby Release notes:  https://github.com/gatsbyjs/gatsby/blob/master/docs/reference/release-notes/v2.28/index.md

The flags can now be applied through `gatsby-config.json` instead of env variables, so it will be easier to roll them out. 

I suggest to test them on the API docs and the MC docs in the `commercetools-docs` repo and, if successful and stable, try setting them via the theme centrally

**Comment by emmenko** [comment]
Nice! 🎉

I would suggest to try them all:

```js
flags: {
  FAST_DEV: true,
  FAST_REFRESH: true,
  PRESERVE_WEBPACK_CACHE: true,
  PRESERVE_FILE_DOWNLOAD_CACHE: true,
}
```

**Comment by nkuehn** [comment]
`PARALLEL_SOURCING` is not as relevant since we don't have contentful sources any more but in theory it could also trigger an incremental improvement for disk I/O.

**Comment by emmenko** [comment]
I did an initial test in the MC website. The screenshot here shows what happens on a cold start (no cache).

<img width="2136" alt="Screenshot 2020-12-03 at 16 50 31" src="https://user-images.githubusercontent.com/1110551/101053462-19d2c580-3588-11eb-8f0c-2075e5a1899e.png">

**Left**
No flags enabled, using gatsby `< v2.28`.

**Middle**
Flags enabled in the theme, using gatsby `v2.28`. The flags are not being used when provided in the theme.

**Right**
Flags enabled in the website, using gatsby `v2.28`. Flags work, there are indeed some improvements.

**Comment by nkuehn** [comment]
on my sad i5 dual core the numbers are higher so the changes are maybe clearer to see

try `yarn develop`: 
![image](https://user-images.githubusercontent.com/4006139/101092139-76020d80-35b9-11eb-8885-edf255043afd.png)

then try gatsby 2.28.0 and all the flags and `yarn develop`:  fails with errors

then try gatsby 2.28.0 and all the flags and  `yarn clean:develop`:

![image](https://user-images.githubusercontent.com/4006139/101093278-cfb70780-35ba-11eb-9ade-af7fbae2bb40.png)

learning:
 * lazy image transformation does not seem to apply in our MDX & gatsby-remark-images scenario. A little lower times like with nicola but definitely not completely "lazy" only when the respective page is loaded.
 * the dev server starts up a little faster, but then I wait the saved time for the first page to load because building the dev bundle is just delayed after the dev server being there. 

OK to take it instead of leaving it but not a fundamental change.

**Comment by davifantasia** [comment]
Evaluated!
