### ISSUE TITLE
rmf-codegen wrapper: use native linux binaries for simpler CI use (vercel )

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#784]
Having the master RAML in the docs repository and automatically generating the canonical "ramldoc" is currently blocked by either having to get java on the Vercel build environment or providing the graalvm linux binary via the nodejs package.   

https://github.com/commercetools/rmf-codegen/releases  also provides a linux binary which should technically run on CI (but I have not really tested it yet!).   Windows does not work yet and the mac OS binary is not signed and notarized by apple so it's blocked by default. 

For the current purposes, at least using the linux binary when node is running in a linux system would be an improvement and about as complex as getting java onto the vercel environments.  

Analogous implementation:  our `writing-style` package that provides the vale binaries depending.

**Comment by davifantasia** [comment]
Scope expanded because the current linux binary also requires Java. To unblock https://github.com/commercetools/commercetools-docs/pull/775, we came up with a work around solution of sticking with the current setup on import-api microsite, so generated specs of change history API will be committed with api microsite until the solution for this issue is completed.

**Comment by nkuehn** [comment]
Trying to build a real binary here: https://github.com/commercetools/rmf-codegen/pull/211   - but it does not look easy to fix the remaining issues.

**Comment by AgaMillward** [comment]
@davifantasia to have a conversation with:
client team
ask @nkuehn for the future approach

**Comment by nkuehn** [comment]
We can close this issue for now until something fundamental changed in the tech stack needed to generate binaries for the rmf-codegen java programm.  It#s not very likely to happen in the near future.
