### ISSUE TITLE
Clipboard icon leads to "unable to load view" error

### ISSUE THREAD

**Issue by adinakleine** [commercetools/commercetools-docs-kit#790]
When hovering over the clipboard icon on any code snippet example, the page fails and shows an error "Unable to load view." 

https://docs.commercetools.com/api/authorization#examples

![Screen Shot 2020-12-08 at 11 45 56 AM](https://user-images.githubusercontent.com/69007224/101514816-b19b2f80-394b-11eb-85c4-ed579ec17f2f.png)

Please fix. :-P

**Comment by nkuehn** [comment]
Let's add an e2e test for this when we fix it.

**Comment by emmenko** [comment]
I'll take a look at this, as it is related to something I changed.

**Comment by emmenko** [comment]
This is actually working in the docs-kit repo. It looks like an issue only in the docs website. Maybe some dependencies issue.

I'll take a look over there.
