### ISSUE TITLE
Design: Striped table has same background as string literals

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#797]
String literals have a light grey background that is the same as the striped table background 

@Shecki  is this tolerable or do we need to adjust? :
![image](https://user-images.githubusercontent.com/4006139/101879949-6a52b000-3b92-11eb-9cf0-e54d1e82ad30.png)

**Comment by nkuehn** [comment]
* #2 would be messy to implement and if we would follow the pattern we would accumulate a lot of exceptions. 
 * #3 I think we had that in a previous iteration and reduced it to a simpler look again.  Could be a white outline though so it's only visible on non-white backgrounds. 

My fav is #3 because it's side effect free to other UX situations.

**Comment by Shecki** [comment]
ok, i try to find a color today or tomorrow

**Comment by Shecki** [comment]
@nkuehn 
outline color is #CCCCCC

**Comment by emmenko** [comment]
@Shecki please always refer to the color token (name) from our design system.

**Comment by Shecki** [comment]
sorry
color-neutral
