### ISSUE TITLE
excludeFromSearchindex frontmatter not effective for algolia on-site search

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#829]
Algolia seems to crawl and index all linked pages independently of whether our frontmatter to exclude them was set. 

It occurred with the change history page.  Let's check whether the frontmatter was set wrong or whether algolia ignores the page metadata

**Comment by davifantasia** [comment]
From my research `excludeFromSearchindex` works as intended - the `noindex` meta is included on pages with the flag. If Algolia finds a link to a page, Algolia appears to crawl the page even if `noindex` is set according to https://www.algolia.com/doc/tools/crawler/apis/configuration/ignore-no-index/.

Next step is to ensure we use the ignoreNoIndex flag in our Algolia configuration.

**Comment by davifantasia** [comment]
I was wrong about the previous link, there is still an open issue to provide that functionality here:

https://github.com/algolia/docsearch-scraper/issues/401

**Comment by davifantasia** [comment]
@nkuehn only option is to include change history in the `stop_urls` list of our docsearch configuration. What do you think?

**Comment by nkuehn** [comment]
@davifantasia  that does not make sense to me, we can't rely on waiting for someone at algolia merging pull requests to their repo and then for the reindex to happen if we need to launch a new feature to public.  

So I suggest to close this as not working for now, watching the issue at algolia and updating the README and our internal wiki documentation with a warning that algolia indexes the pages nevertheless.
