### ISSUE TITLE
excludeFromSearchIndex did not work

### ISSUE THREAD

**Issue by TohruKohrita** [commercetools/commercetools-docs-kit#830]
In the following instance, `excludeFromSearchIndex: true` did not exclude a page from the search index.

Although `excludeFromSearchIndex: true` was set, the change history page was searchable after [merging this PR](https://github.com/commercetools/commercetools-docs/pull/784). 

However, [after this follow-up PR](https://github.com/commercetools/commercetools-docs/pull/829), the Change History page successfully got hidden from the search. What we did in this second PR was to remove an unintended link to the Change History page from the landing page. (I do not want to guess, but this may have something to do with the failure of `excludeFromSearchIndex: true`.)

-----

One more thing, [here in /gatsby-theme-docs/README](https://github.com/commercetools/commercetools-docs-kit/blob/master/packages/gatsby-theme-docs/README.md#available-options-for-the-theme-plugin), I think you mean **Default: false**. This part:
<img width="1110" alt="Screenshot 2021-01-14 at 11 39 32" src="https://user-images.githubusercontent.com/63338357/104580168-2e14e280-565d-11eb-9ee2-5dcd19f7a73e.png">

**Comment by nkuehn** [comment]
Resolved wontfix /we learnt something:
 * Algolia docsearch does not respect the HTML header, we must make sure it's not linked 
 * but we still need the header for the other crawlers like google.
