### ISSUE TITLE
Add icon next to microsite title

### ISSUE THREAD

**Issue by TimonRey** [commercetools/commercetools-docs-kit#845]
- placement and spacing: todo @Shecki pls add the link to invision here
- icons assets: https://drive.google.com/drive/folders/1ZXtyvOtAiysIg9Ky_4Ew6NKKwnmm39cx?usp=sharing
- Icon has to be configured separately from the theme because the icons have to be unique for each site. That's why they should live in the microsite and not in the theme
- we suggest to not add a configuration but to add the icons to a conventional path
 - `src/site-icon.svg`
 - `src/site-icon-small.svg`

open questions:
- What's the initial state when no icon is configured yet? Default icon or no icon? @Shecki 
- Which icon should be used next to the title? Small (25x25) or the big one? @Shecki

**Comment by Shecki** [comment]
- invision link:
   https://commercetools.invisionapp.com/console/share/3A1N99HMK2

- icon next to title - "25px"

- default icon will be created in a separate task by me

**Comment by TimonRey** [comment]
@Shecki Another question: How should it look like if there is a beta flag as well?

<img width="567" alt="Bildschirmfoto 2021-02-10 um 00 14 39" src="https://user-images.githubusercontent.com/31767369/107441121-fa7e8880-6b34-11eb-866f-00f36829ce77.png">

**Comment by Shecki** [comment]
@TimonRey  please place the beta above.
left aligned to the icon
