### ISSUE TITLE
Make MDX transclusion possible for topic based writing

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#85]
Technical Writing works a lot with a concept named "Topic Based Writing" which is a fancy name for re-using content across many places.  MDX has native support for transclusion and being able to use it would make this a much more interesting tool for large-scale usage. 

MDX documentation: https://mdxjs.com/getting-started#documents

If done it would be very likely that the centralized content lives in a separate package.  

example usage
```mdx 
import TopicBasedWritingConcept from "../topics/concepts/topic-based-writing.mdx"

<TopicBasedWritingConcept />
```

It did not work out of the box.

**Comment by emmenko** [comment]
See #104
