### ISSUE TITLE
Release note generator needs correction

### ISSUE THREAD

**Issue by TohruKohrita** [commercetools/commercetools-docs-kit#862]
Currently, if you feed in 
<img width="670" alt="Screenshot 2021-02-11 at 13 59 26" src="https://user-images.githubusercontent.com/63338357/107640745-040e0a80-6c73-11eb-9f51-92cf2ad1af3f.png">

you get the output:
<img width="780" alt="Screenshot 2021-02-11 at 14 02 39" src="https://user-images.githubusercontent.com/63338357/107640788-138d5380-6c73-11eb-8758-ac2ff171b424.png">

Problems:
1. Even though a type was chosen, the `type` is not rendered. Since `type` is required, this MDX does not render a webpage. The browser sends back an error.
2. There should (probably even must) be 2 spaces before hyphens in the`topics` list. This is auto-corrected by the beautification program once you (insert the content and) save the file, so it will be auto-corrected but I think it's better to be right from the beginning.
3. After giving `type` manually and correcting the YAML list of `topics`, the webpage gets rendered. However, the `date` format is wrong, so we get "Invalid date":
<img width="315" alt="Screenshot 2021-02-11 at 14 23 36" src="https://user-images.githubusercontent.com/63338357/107642160-cad69a00-6c74-11eb-9bdf-af03e109e83b.png">
The correct format is `date: 2021-03-03`.

4. `description` gets a wrong value. Somehow, it is set to {value for title} + {value for description}. (Compare the first two screenshots above).
5. We got this wrong in wiki. Sorry! But the docs naming convention for release notes is to lower case the title and replace spaces with hyphens. So could you lower case the generated file names? Thank you!
6. (opinion) About the command line instruction (please see the first screenshot above), I think we better remove the time option because it won't be used. Simple YYYY-MM-DD suffices.
7. (opinion) Again about the command line instruction. This is a small thing and there is nothing wrong with "Title of the release note. Max. 256 character plain text." but max 256 is more important for "description" that come right after this. So I propose "Title of the release note. Write it in plain text."
8. (opinion) For the content of the generated MDX, it is perhaps better to replace the Latin with the following: Please write the content here. To use "Read More", insert `<!--more-->`.
9. Align the wording of the descriptions in the command line... suggestion (start with a verb):
- Insert the title of the release note. [...]
- Describe the key changes and their advantages briefly. [...]
- Fill in the topics for this release note. [...]

10. npm script in VSC after testing.
11. List of topics (selector)... for each microsite (Merchant Center, API, ... have different topics.). Maintenance of topics in the code (not wiki) would be okay.

Thank you!

**Comment by TohruKohrita** [comment]
Adina (@adinakleine) has further feedback on command line commands. 

@TimonRey

**Comment by adinakleine** [comment]
@TimonRey I will extend this issue. I will ping you when the issue is completed.

**Comment by nkuehn** [comment]
Thanks for filing all the details so exactly!   
If you want to top up on that, give the issue a specific title, too.

**Comment by TohruKohrita** [comment]
For the 11th point, if we provide enum selector (which needs to allow multiple choice), it is my personal opinion that we better provide "Leave blank" option mainly for two reasons:

- The contributor needs to be familiar with our definition of topics. It may be OK for a frequent contributor, but otherwise, it will take a lot of their time. On the other hand, it is generally easy for us to choose topics. 
- It is rare but we sometimes change topics. Eg. Import API will have export feature sooner or later.

What do you think? @adinakleine @stmeissner

**Comment by TimonRey** [comment]
Thanks for the feedback! Just one question for the 5th point. The script already generates the filenames in the format you suggested. Or do you also want to have this format for the title in the frontmatter?
