### ISSUE TITLE
API docs: visualize "pattern properties" (regexes that allow varying object property names)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#863]
For example, the commercetools LocalizedString object type allows arbitrary keys as long as they are a valid locale code. 

The docs kit RAML API components are handling the case without error and render the regular expression as the property name:

![image](https://user-images.githubusercontent.com/4006139/107693539-95e73900-6cae-11eb-8d85-b8f1339fb2cd.png)

So at least it works, but it's very opaque to the user because it's implicit that we don't mean this explicit string but any string that matches the given regular expression. 

RAML spec for it:  https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#additional-properties 

In incremental imrovement to the renderer would be to detect strings that start and and with a forward slash.  For example, if the prop is `/myRegexExample.*/`, the UI layout would be different and explicitly say something like "Any property matching `myRegexExample.*`"

**Comment by Shecki** [comment]
Hey my suggestion:
![image](https://user-images.githubusercontent.com/28807759/116982363-f774dd80-acc8-11eb-949c-2f24ab2718d9.png)
all regex start with the blue slashes and end with them.

color-info | #078cdf

and we will have  more generic text below: "Any property matching string above"
if we would repeat the text from the field, it could get really long.
With the generic text, we avoid to long descriptions
