### ISSUE TITLE
The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type"

### ISSUE THREAD

**Issue by emmenko** [commercetools/commercetools-docs-kit#865]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/1110551/107791874-bd90dc80-6d54-11eb-8816-39185aa1522f.png">

Caused by #853

**Comment by nkuehn** [comment]
In this specific situation we need the ':first-child`operator because we do not know the type of the first child (they are the markdown generated content)
