### ISSUE TITLE
Proposal: Allow or encourage absolute imports in MDX content

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#87]
To make the way content is written easier to refactor (i.e. rename or move around in the content hierarchy) it would be helpful to allow authors to make import statements absolute. 

e.g. when including an image or other MDX or code example file, instead of 

```js
import OptimisticConcurrencyDefinition from "../../topics/definitions/optimistic-concurrency.mdx"
```
writing 

```js
import OptimisticConcurrencyDefinition from "topics/definitions/optimistic-concurrency.mdx"
```
would yield less problem when e.g. moving the file that includes the content. 

Root should be the `src` directory of the current package. 

Gatsby supports this explicitly but it has to be configured:
https://www.gatsbyjs.org/docs/add-custom-webpack-config/#absolute-imports

**Comment by emmenko** [comment]
Sounds like a good idea 💯
