### ISSUE TITLE
Type Linking: Resolve {FooBar}PagedQueryResponses to "PagedQueryResponse with results ... {FooBar}"

### ISSUE THREAD

**Issue by TohruKohrita** [commercetools/commercetools-docs-kit#870]
It would make a slick documentation if we could use a link in a response documentation in the endpoint documentation. I would like to refer to the already documented (handwritten MDX) PagedQueryResult in the following case:
<img width="839" alt="Screenshot 2021-02-19 at 14 25 40" src="https://user-images.githubusercontent.com/63338357/108510068-5a57fa80-72be-11eb-86f9-2543af65f094.png">

Ideally, I would like to have 

Response: [PagedQueryResult](link url) with `results` containing an array of [Changes](automatic link). 

At minimum, I would like to enable a link for ChangedHistoryPagedQueryResponse, which is documented in the same page either by hand (current status) or by auto-doc-generator.

**Comment by nkuehn** [comment]
@TohruKohrita  the current implementation is already doing the automatic linking here, you can see the smoke test output here: https://commercetools-docs-kit.vercel.app/api-docs-smoke-test/endpoints/methods#get-resource-by-key 

So putting "ChangeHistoryPagedQueryResult" on some page in the same website would already yield the link. 

But I agree that the pattern of the current handwritted docs is more usable.  The question we need to clarify is whether this is a generic pattern that also repeats in other places in the API or an actual "hack" just of the paged query result case.

**Comment by TohruKohrita** [comment]
> @TohruKohrita the current implementation is already doing the automatic linking here, you can see the smoke test output here: https://commercetools-docs-kit.vercel.app/api-docs-smoke-test/endpoints/methods#get-resource-by-key
> 
> So putting "ChangeHistoryPagedQueryResult" on some page in the same website would already yield the link.

Yes, I am aware of this. But thank you for pointing this out.

I wanted to avoid documenting PagedQueryResult for this particular data type. It will be a practical duplicate of the PagedQueryResult documentation. If we auto-generate the http api doc in the future, this issue come up everywhere where PagedQueryResult appear as a response.

**Comment by nkuehn** [comment]
Grooming: 
 * tech writers need to decide what is the lesser evil  
 * starting to document the specific paged query results would have the advantage that we do not have to make 100% sure that every single API does not have any additional fields in the FooBarPagedQueryResult  (e.g. special meta fields or the stuff that change history originally had (and has))

**Comment by TohruKohrita** [comment]
The docs lectors decided to document each paged query result in each corresponding resource page (at the top of the page, eg. CartPagedQueryReuslt before Cart).
