### ISSUE TITLE
Vale check start not reliable

### ISSUE THREAD

**Issue by adinakleine** [commercetools/commercetools-docs-kit#872]
We have seen several times that the Vale check is not always performed automatically in the commercetools-docs repository. A workaround is to trigger a build via an empty commit. This works, but is not a general solution.
Please investigate the reason. 
![Vale checker message](https://user-images.githubusercontent.com/58512719/108691329-ac399400-74fb-11eb-9625-41d156c33362.png)

**Comment by stmeissner** [comment]
The workaround is executing following command:
`git commit --allow-empty -m "Trigger Build"`
followed by a `git push`.

**Comment by nkuehn** [comment]
I just checked on a trivial branch that just does a README update.  The vale check is not reported as having run there but it actually did run if I look into the Actions UI and its logs.  It did not find anything to complain about  though. 

@adinakleine @stmeissner  did you observe in other branches that the problem typically occurs when vale had nothing to report?  Just a guess, it could be any other reason too.  

PS: this issue actually belongs into the internal content repository, it's about the configuration of the github action there.

**Comment by davifantasia** [comment]
Proposal after Docs weekly:

* Make Vale GitHub check optional to prevent it from blocking merges.
* Run Vale in cli for enforcement.
