### ISSUE TITLE
Child Section Navigator for union-like type documentation

### ISSUE THREAD

**Issue by TohruKohrita** [commercetools/commercetools-docs-kit#876]
Let T be the union-like type, "representing" the union of, say, types A, B, and C. The custom component for T renders the documentation of A, B, and C under the "section" heading of T. 

We would like to have a child section navigator for A, B and C in the "section" T. I think it is more useful if this function comes with an on-off switch.

**Comment by nkuehn** [comment]
I think the requirements are clear here, but it requires a technical exploration whether we are able to "simulate" actual MDX headings to the ChildsectionNavigator component.

**Comment by nkuehn** [comment]
I do wonder whether the union rendering is a rabbithole of details that will always be less usable to the readers than manually positioning all the union members on a given MDX page.   
Manual placement would give us:
 * a consistent authoring structure
 * ability to group them into chapters (e.g. like the Message Types)
 * meaningful ordering on the page
 * abiltiy to use the standard ChildSectionNavigator
 * no special handling for linking and ToC generation (index nav)

**Comment by TohruKohrita** [comment]
We decided not to use union-type rendering feature in the docs daily on 23.03.2021.
