### ISSUE TITLE
Re-evaluate API data loading architecture (e.g. dynamic import / loadable components)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#887]
**Problem Statement:**
 * Currently, to implement the `<ApiType .. />` and `<ApiEndpoint ... />` components we are using a hook that provides the complete API data from a GatsbyJS static query. The hook locally searches the right API type or endpoint from the query result.   That way the complete API specs become part of the javascript bundles loaded to hydrate the page after it has been statically loaded.  It's in all MDX pages no matter whether they use the component or not because the components are provided centrally by the MDXProvider. 
 * Dynamic queries have been much discussed by the gatsbyJS maintainers but have finally been decided to not become reality. 
 * We did try other approaches but were not successful at the time. 
 * We are now adding the complete commercetools API specification to the site, consisting of overall ca. 3000 RAML files and json examples. Overall ca. 8 MB of data.  This will very likely "go boom" and affect UX becasue it may take ages for a page to become interactive.

**Ideas:**

The main idea discussed at the time was to try to provide the RAML data as loadable modules (via webpack, re-using the YAML loading that is available OOTB) and then dynamically import them in the `<ApiType ... />` component depending on what type was passed via properties.  We did not get it running but concluded that it should fundamentally be possible. 

An additional problem was that the RAML had to be parsed and resolved by a gatsbyJS plugin. That need is now not a blocker any more because we are preprocessing and "flattening" the RAML using the rmf-codegen tooling. 

I just spent a few minutes researching (a.k.a. googling) the problem and the most specific and promising blog post is this one that concludes to resort to the "loadable-components" library:
https://dev.to/itmayziii/better-performance-using-dynamic-code-splitting-in-gatsby-with-loadable-components-6am

Similar-but-different post here: https://medium.com/billie-finanzratgeber/how-to-build-a-super-dynamic-website-with-gatsby-js-and-contentful-129b4d00b6c3  

@davifantasia @emmenko do you think it's worth trying the approach again?  We's still need the "hook-with-some-query-data" for some purposes but none has the problem with such massive data sizes.

**Comment by emmenko** [comment]
One "simple" thing I can think of, that we can try as a first step, would be to run the graphql queries in `gatsby-node` (essentially on startup in the `gatsby-theme-api-docs`).
The results then are written into files in the filesystem within the website folders. Each file is then really specific for each type, endpoint, or whatever we need.

Then the react components use a dynamic import to load the correct file (according to naming conventions, types etc).

This way, we don't need to mess up with things like Webpack, etc.

I'll see if I can find some time this week to have a prototype working.

**Comment by nkuehn** [comment]
I'm not aware that it's possible to do graphQL queries in arbitrary places in gatsbyJS, but would be cool if we could.  

To be honest I do not see the advantage of keeping the graphQL facade for the RAML files when we just end up writing files from the graphQL data that we then load through dynamic imports anyways.  

If we run through the complexity of getting dynamic imports to work anyways where's the advantage of that indirection vs directly importing the YAML file? 
 * RAML = YAML just with a different file extension;  
 * YAML can be imported already in our gatsbyJS setup; 
 * the RAML types and endpoints do already have a hard filesystem convention that can be leveraged - that's how the plugin that loads them into GraphQL is working anyway.  It's interpreting them "dumb" as YAML and leverages the filesystem naming convetion for type vs. endpoint ("resource")

**Comment by davifantasia** [comment]
We'll try a minimal approach that

* renames raml to yaml
* use [loadable components](https://loadable-components.com/docs/dynamic-import/) to load the name of the API type as a property. `<LoadableComponent apiType="name-of-type" apiKey="key" />`
* No formatting, just dumping of the RAML data
* Must run on dev and prod build
* The loadable component should replace the current ApiType component for testing the bundle size.

**Comment by nkuehn** [comment]
FYI I spent two experimental tech time hours to set it up as drafted but can't make sense of the errors that occur (see code comments).  Configuration went relatively fine following that blog post but it just does not run.

branch: https://github.com/commercetools/commercetools-docs-kit/tree/nk-raml-loading-as-module

I also started to doubt whether the approach to completely code split every single type and resource is actually smart.  We may first want to evaluate the actual bundle structure (e.g. by throwing the big main API spec in) and try to only split the actual static query hooks into own bundles hoping that they do not go into the weight of non-API pages any more.  Numbers and real sizes first?

**Comment by nkuehn** [comment]
PS: A quick check in the public build output of the api docs smoke test site shows that the static query data actually _is_  already an own JSON file and not duplicated in other chunks (except the statically generated content in the .html files).    But that json file's ID is referred from every page-data.json file in the whole site, including the home and 404 pages, including being prefetched by all.  This is most likely because we are providing the ApiType components in the MDX Provider which is in every page. 

A side isse of the static query JSON file is that it contains unbelievable numbers of null values because most of our types do not actually use the more special features of our annotations and RAML but GraphQL response data is not sparse but has all fields with null values.   That alone could be a 50% saving.  

Thinking out of the box, we could also go back and consider a less "magic" approach, too that puts a bit of burden on the authors:  Forcing the pages that use an API to explicitly include that APIs data in a given MDX page and then passing the actual API spec to the <ApiType ...> components instead of the API key.  That would move the data down to page level and leverage Gatsby's default assumption. 

Lastly, another approach is the one outlined by Nicola above: Generate actual React components at build time for each and every type and endpoint.  But I am still a bit scared of the user experience on typos, the caching and cleaning of the generated code etc.  - it might be overkill if we can achieve enough in simpler ways.

**Comment by nkuehn** [comment]
Summary of our findings and decisions how to proceed:

"analysis" step (this issue) concluded with finding that a data loading architecture that does not go through GatsbyJS's GraphQL layer might theoretically work but is hard to debug, hard to find solultions to typical issues and would (if mapping RAML files to bundles) lead to another problem which is massive (houndreds) numbers of component files to be lazy loaded on a single API docs page for hydration.    The current big fat API spec is a 2,6 MB JSON file loaded independently of the bundles and is 111kb on the wire gzipped.  It's not a nice size but it is acceptable for hydration to "time to interactive".  

**conclusions from the finding:**

  * We will rather optimize the curreent architecture: (priority order)
      1. improve the react performance of the API reference pages (first two changes done, next follow after they are applied and we can measure the rest after these are applied)
      2. start watching the general site bundle size better again - the big bundle was/is not due to the API dataset but due to moment.js,  parse5, the UI Kit icons being loaded all-at-once and not individual and other contributing "fat" pieces.
      3. make sure the API data is only loaded on pages that use it.   The straightforward "gatsby way" of doing this would be to not inject the components in the MDXProvider by default but rather import them explicitly in the MDX pages that need them ( #994 ).  
      4. A next step would be to be able to load only specific APIs.   A simple way to do this would be to provide site-local  wrapper components that provide e.g. `<HistoryEndpoint  path="/foo/bar"  method="POST"> ...`.  The kit components would have to provide the necessary building blocks (a React fragment for the query and an internal component that takes the data as an argument and not the api key).  ( see #995)

Implicit basic decisions:
 * tech writers and users have to learn writing an import statement for the API docs (acceptable, they have to use the syntax for content fragments anyways)
 * further optimization would be through site-specific wrapper components that optimize the specific use case of the specific site.
