### ISSUE TITLE
Child navigation section visual regression

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#899]
Link: https://docs.commercetools.com/api/projects/order-edits#detailed-list-of-stagedorderupdateactions

Image:
![Screenshot 2021-03-10 at 15 05 57](https://user-images.githubusercontent.com/8238495/110641429-4b27e680-81b2-11eb-8acf-5cf8210a7712.png)

**Comment by Shecki** [comment]
@nkuehn @adinakleine 
**Question:** within the update actions we have a mix of different writing styles.
Some words are written together as "One" long word and some are divided.
I can´t see consistency behind it.

Could someone of you please confirm, that the writing style is intended?
We could get rit of those issues by dividing the word in multiple words.

cc @TimonRey @emmenko

**Comment by nkuehn** [comment]
Hi, this needs to be addressed independently of whether the current content is intended or not.  Please create an issue in the commercetools-docs repo for fixing the content.  

There will always be some content that is the weirdo outlier.   

I spoke to @TimonRey - there is  a simple solution in the CSS spec that addresses exactly this problem:  https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

**Comment by TimonRey** [comment]
I think this issue is resolved now. I created a new issue for the content writing style issue [here](https://github.com/commercetools/commercetools-docs/issues/966)
The actual bug was fixed [here](https://github.com/commercetools/commercetools-docs-kit/pull/911)
