### ISSUE TITLE
search dialog does not work properly if you navigate to the same page

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#961]
We've noticed that if you open the search dialog and search for the same page (or a section in this page), the search dialog does not handle this case properly. You can click on the link but you won't be redirected to the page nor is the searchbox automatically closing to show that you are already on this page.
Example:

![Kapture 2021-05-07 at 09 44 48](https://user-images.githubusercontent.com/31767369/117415796-ff2ac100-af18-11eb-8b22-c529d44c3e71.gif)

My favorite solution would be that the search box checks if the user is already on the same page, in this case the search dialog should simply close or maybe reload the page.

**Comment by nkuehn** [comment]
@timonrey  I cannot reproduce this in Chrome and Firefox.   

It's working on the same page, both for navigating to the top heading (page title) or to something down in the content.   the search dialog closes, too.  

can you reproduce again?  For me it works

**Comment by timonrey** [comment]
Interesting, I tried to reproduce it but it seems to work now. I assume the cause was some kind of artifact, fixed by regular mantainance.
I will close the issue for now. If it occurs again, we can reopen it easily.
